/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.bankrefund;

import java.util.List;
import java.util.Map;

import com.pay.fundout.withdraw.model.bankrefund.BackfundOrder;
import com.pay.fundout.withdraw.model.bankrefund.BankRefundOrder;
import com.pay.fundout.withdraw.model.bankrefund.BankRefundOrderQueryResult;
import com.pay.inf.dao.BaseDAO;
import com.pay.inf.dao.Page;

public interface BankRefundOrderDAO extends BaseDAO {
	/**
	 * 查询出款失败原因列表 20110309 liwei
	 * 
	 * @return
	 */
	List<Map<String, String>> getFailDesc();

	/**
	 * 存储银行退款订单
	 * 
	 * @param order
	 * @return
	 */
	Long createOrder(BankRefundOrder order);

	/**
	 * 更新订单信息
	 * 
	 * @param order
	 * @return
	 */
	boolean updateOrder(BankRefundOrder order);

	/**
	 * 根据原交易订单号获取退款订单信息
	 * 
	 * @param tradeOrderId
	 * @return
	 */
	BankRefundOrder getOrderByTradeOrderId(Long tradeOrderId);

	/**
	 * 获取可退款订单列表
	 * 
	 * @param page
	 * @param params
	 * @return
	 */
	Page<BankRefundOrderQueryResult> getAllowRefundList(
			final Page<BankRefundOrderQueryResult> page, Object... params);

	/**
	 * 获取待审核退款订单列表
	 * 
	 * @param page
	 * @param params
	 * @return
	 */
	Page<BankRefundOrderQueryResult> getAuditRefundList(
			final Page<BankRefundOrderQueryResult> page, Object... params);

	/**
	 * 根据订单号获取可退款订单信息
	 * 
	 * @param orderId
	 * @return
	 */
	BankRefundOrderQueryResult getAllowRefundOrderById(String orderId);

	/**
	 * 根据订单号获取待审核订单信息
	 * 
	 * @param orderId
	 * @return
	 */
	BankRefundOrderQueryResult getAuditRefundOrderById(String orderId);

	/**
	 * 得到已审核的退款订单
	 * 
	 * @param page
	 * @param params
	 * @return
	 */
	Page<BankRefundOrderQueryResult> getAuditedRefundList(
			final Page<BankRefundOrderQueryResult> page, Object... params);

	BackfundOrder queryBackfundOrderByInnerOrderId(Map<String, String> param);

}