/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.model.CommonAudit;

public interface CommonAuditDAO extends BaseDAO<CommonAudit> {

}