/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.model.DepositOrder;
import com.pay.txncore.model.DepositOrderExpand;

public interface DepositOrderExpandDAO extends BaseDAO<DepositOrderExpand> {

	/**
	 * 
	 * @param depositOrderNo
	 * @return
	 */
	public Long querySurplusStatusByDepositOrder(Long depositOrderNo);

	/**
	 * 
	 * @param depositOrderNo
	 * @return
	 */
	public DepositOrder querySurplusOrderByDepositOrder(Long depositOrderNo);

}