/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import java.util.List;
import java.util.Map;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.crosspay.model.OrderQueryResult;
import com.pay.txncore.dto.DepositQueryParamDTO;
import com.pay.txncore.dto.OrderQueryResultDetail;
import com.pay.txncore.dto.ReconcileOrder;
import com.pay.txncore.model.RefundOrderQueryResultDetail;

public interface OrderQueryResultDAO extends BaseDAO<OrderQueryResult> {

	/***
	 * 单笔/网关订单 根据商户订单号OrderId 和 商户ID 查询 TRADE_ORDER,PAYMENT_ORDER
	 * 
	 * @param map
	 * @return
	 */
	public OrderQueryResultDetail queryTradeInfo(Map<String, Object> map);

	/**
	 * 单笔 / 支付订单 根据商户订单号orderID 查询TRADE_BASE，TRADE_ORDER，PAYMENT_ORDER表记录
	 * 
	 * @param orderQueryParam
	 * @return
	 */
	public List<OrderQueryResultDetail> queryTradeUnionPayment(
			Map<String, Object> map);

	/**
	 * 单笔 / 退款订单 根据商户订单号orderID 查询TRADE_BASE，TRADE_ORDER，REFUND_ORDER表记录
	 * 
	 * @param orderQueryParam
	 * @return
	 */
	public List<RefundOrderQueryResultDetail> queryTradeUnionRefund(
			Map<String, Object> map);

	/**
	 * 批量 / 支付订单 根据时间段查询 TRADE_BASE，TRADE_ORDER，PAYMENT_ORDER表记录 最大范围 15天
	 * 如果时间段为空查询 默认为当天0点-24点
	 * 
	 * @param orderQueryParam
	 * @return
	 */
	public List<OrderQueryResultDetail> queryAllTradeUnionPayment(
			Map<String, Object> map);

	/**
	 * 批量 / 退款订单 根据时间段查询 TRADE_BASE，TRADE_ORDER，REFUND_ORDER表记录 最大范围 15天
	 * 如果时间段为空查询 默认为当天0点-24点
	 * 
	 * @param orderQueryParam
	 * @return
	 */
	public List<RefundOrderQueryResultDetail> queryAllTradeUnionRefund(
			Map<String, Object> map);

	/**
	 * 商户对账单下载
	 * 
	 * @param map
	 * @return
	 */
	public List<ReconcileOrder> queryReconcileOrder(Map<String, Object> map);

	/**
	 * 记录商户请求历史
	 * 
	 * @param gatewayRequestDTO
	 * @return
	 */
	//public Long createGateRequest(GatewayRequest gatewayRequest);

	/**
	 * 记录商户返回历史
	 * 
	 * @param gatewayResponse
	 * @return
	 */
	//public void createGateResponse(GatewayResponse gatewayResponse);

	/**
	 * 根据请求序列号获取商户请求网关历史信息
	 * 
	 * @param serId
	 * @return
	 */
	//public List<GatewayRequest> queryGateRequestInfo(String serId);


	/**
	 * FO 充值订单查询接口
	 * 
	 * @param map
	 * @return
	 */
	//public List<DepositOrderQueryDetail> queryDepositOrderForFO(Map<String, Object> map, int pageSize, int page);

	/***
	 * FO 查询重复支付订单接口
	 * 
	 * @param map
	 * @param pageSize
	 * @param page
	 * @return
	 * @author xiaodong.liu
	 * @date 2012-05-30
	 */
//	public List<DepositOrderQueryDetail> queryDuplicatePaymentOrderForFO(
//			Map<String, Object> map, int pageSize, int page);

	/**
	 * FO 查询重复支付订单接口
	 * 
	 * @param map
	 * @return
	 */
	public Integer queryDuplicatePaymentOrderCountForFO(Map<String, Object> map);

	/**
	 * FO 充值订单查询接口
	 * 
	 * @param map
	 * @return
	 */
	public Integer queryDepositOrderCountForFO(Map<String, Object> map);

	/**
	 * 查询充值订单
	 * 
	 * @param depositOrderNo
	 * @return
	 */
	//public DepositOrderQueryDetail queryDepositOrderByNo(Long depositOrderNo);

	public boolean isDepositAmountLimit(
			DepositQueryParamDTO depositQueryParamDTO);

	public boolean isDepositNumLimit(DepositQueryParamDTO depositQueryParamDTO);

}