/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.model.PartnerConfig;

public interface PartnerConfigDAO extends BaseDAO<PartnerConfig> {
	
	/**
	 * 
	 * @param id
	 */
	void delete(Long id);

	/**
	 * 
	 * @param partnerID
	 * @param paramCode
	 * @return
	 */
	PartnerConfig findConfig(Long partnerID, String paramCode);

}