/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import java.util.List;
import java.util.Map;

import com.pay.inf.dao.BaseDAO;
import com.pay.inf.dao.Page;
import com.pay.txncore.dto.AutoTradeOrderDTO;
import com.pay.txncore.dto.PayLinkDetailDTO;
import com.pay.txncore.dto.PayLinkTemplateDTO;
import com.pay.txncore.dto.TradeOrderDetailDTO;
import com.pay.txncore.dto.TradeOrderDetailMpsDTO;
import com.pay.txncore.model.TradeOrder;

public interface TradeOrderDAO extends BaseDAO {

	/**
	 * 更新网关订单为已锁定
	 * 
	 * @param tradeOrderNo
	 * @return
	 */
	boolean updateForTradeOrderLock(Long tradeOrderNo);

	/**
	 * 解锁网关订单
	 * 
	 * @param tradeOrderNo
	 * @return
	 */
	boolean updateForTradeOrderUNLock(Long tradeOrderNo);

	/**
	 * 增加网关可退款金额
	 * 
	 * @param tradeOrderNo
	 * @param refundAmount
	 * @param status
	 * @return
	 */
	boolean updateAddRefundAmount(Long tradeOrderNo, String refundAmount,
			Integer status);

	/**
	 * 增加网关可退款金额
	 * 
	 * @param tradeOrderNo
	 * @param refundAmount
	 * @param status
	 * @return
	 */
	boolean updateAddRefundAmount(Long tradeOrderNo, String refundAmount);

	/**
	 * 减少网关可退款金额
	 * 
	 * @param tradeOrderNo
	 * @param refundAmount
	 * @param status
	 * @return
	 */
	boolean updateSubRefundAmount(Long tradeOrderNo, String refundAmount,
			Integer status);

	/**
	 * 更新网关订单状态
	 * 
	 * @param tradeOrderNo
	 * @param oldStatus
	 * @param status
	 * @return
	 */
	boolean updateStatus(Long tradeOrderNo, Integer oldStatus, Integer status);

	/**
	 * 锁定网关订单
	 * 
	 * @param tradeOrderNo
	 * @return
	 */
	boolean lockedOrderForUpdate(Long tradeOrderNo);

	/**
	 * 查询网关订单
	 * 
	 * @param partnerId
	 * @param orderId
	 * @return
	 */
	List<TradeOrder> queryTradeOrder(Long partnerId, String orderId);

	public TradeOrder findByIdAndStatusForUpdate(TradeOrder order);

	public boolean updateAddRefundAmount(Long tradeOrderNo,
			String refundAmount, String status);

	public boolean updateSubRefundAmount(Long tradeOrderNo,
			String refundAmount, String status);

	/**
	 * 
	 * @param tradeOrderNo
	 * @param refundAmount
	 * @param status
	 * @return
	 */
	boolean updateRefundAmount(Long tradeOrderNo, String refundAmount,
			String status);
	
	
	public TradeOrder queryTradeOrder(Map<String,String> paraMap);
	
	public List<TradeOrderDetailDTO> getTradeOrderDetail(Map<String, String> prameters);

	List<AutoTradeOrderDTO> queryAutoTradeOrder(AutoTradeOrderDTO tradeOrder,Page page);

	TradeOrderDetailMpsDTO getTradeOrderDetailMps(TradeOrderDetailMpsDTO  detailMpsDTO);
	
	public List<PayLinkDetailDTO> getPayLinkDetail(Map<String, String> prameters);
	
	public List<PayLinkTemplateDTO> payLinkTemplateDownload(Map<String, String> prameters);
}