/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dto;

import java.util.Date;

import com.pay.inf.model.BaseObject;

/**
 * RECONCILE_IMPORT_RECORD
 */

public class ReconcileImportRecordDTO extends BaseObject {

	private static final long serialVersionUID = 1L;
	private Long recordId;
	private Long fileId;
	private String busiType;
	private String bankOrderNo;
	private String bankAmount;
	private java.util.Date tradeDate;
	private String orgCode;
	private Long busiStatus;
	private String tradeOrderNo;
	private Date createDate;

	public Long getRecordId() {
		return recordId;
	}

	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	public Long getFileId() {
		return fileId;
	}

	public void setFileId(Long fileId) {
		this.fileId = fileId;
	}

	public String getBusiType() {
		return busiType;
	}

	public void setBusiType(String busiType) {
		this.busiType = busiType;
	}

	public String getBankOrderNo() {
		return bankOrderNo;
	}

	public void setBankOrderNo(String bankOrderNo) {
		this.bankOrderNo = bankOrderNo;
	}

	public String getBankAmount() {
		return bankAmount;
	}

	public void setBankAmount(String bankAmount) {
		this.bankAmount = bankAmount;
	}

	public java.util.Date getTradeDate() {
		return tradeDate;
	}

	public void setTradeDate(java.util.Date tradeDate) {
		this.tradeDate = tradeDate;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public Long getBusiStatus() {
		return busiStatus;
	}

	public void setBusiStatus(Long busiStatus) {
		this.busiStatus = busiStatus;
	}

	public String getTradeOrderNo() {
		return tradeOrderNo;
	}

	public void setTradeOrderNo(String tradeOrderNo) {
		this.tradeOrderNo = tradeOrderNo;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}