/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.poss.report.dto;
/**
* T_MEMBER_FLOW
*/

public class MemberFlowDTO  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
    private Long fiMobilePosCount;
    private Long refundCount;
    private Long fiDepositAmount;
    private Long allAmount;
    private Integer memberType;
    private Long foAccOutCount;
    private Long fiDepositRefundCount;
    private Long fiDepositRefundAmount;
    private Long foAccInAmount;
    private Long foWithdrowAmount;
    private Long refundAmount;
    private Long allCount;
    private String name;
    private Long fiAccOutAmount;
    private Long fiConsumeCardAmount;
    private Long fiPrepaidCardCount;
    private java.util.Date reportDate;
    private Long refund2AccAmount;
    private Long foAccInCount;
    private Long foAccOutAmount;
    private String memberCode;
    private Long fiConsumeCardCount;
    private java.util.Date cteateDate;
    private Long foBankAmount;
    private Long fiAccInCount;
    private Long foBankCount;
    private Long bankWithholdingCount;
    private Long foWithdrowCount;
    private Long fiAccInAmount;
    private Long fiDepositCount;
    private Long bankWithholdingAmount;
    private Long fiPrepaidCardAmount;
    private Long fiBankAmount;
    private Long fiBankCount;
    private Long sequenceId;
    private Long fiAccOutCount;
    private Long refund2AccCount;
    private Long fiMobilePosAmount;
    private String signName;
    
    private Long creditQuickPayAmount;
    private Long creditQuickPayCount;
    private Long debitQuickPayAmount;
    private Long debitQuickPayCount;

    public String getSignName() {
		return signName;
	}

	public void setSignName(String signName) {
		this.signName = signName;
	}

	public Long getFiMobilePosCount (){
        return fiMobilePosCount;
    }
    
    public void setFiMobilePosCount (Long fiMobilePosCount){
        this.fiMobilePosCount = fiMobilePosCount;
    }
    public Long getRefundCount (){
        return refundCount;
    }
    
    public void setRefundCount (Long refundCount){
        this.refundCount = refundCount;
    }
    public Long getFiDepositAmount (){
        return fiDepositAmount;
    }
    
    public void setFiDepositAmount (Long fiDepositAmount){
        this.fiDepositAmount = fiDepositAmount;
    }
    public Long getAllAmount (){
        return allAmount;
    }
    
    public void setAllAmount (Long allAmount){
        this.allAmount = allAmount;
    }
    public Integer getMemberType (){
        return memberType;
    }
    
    public void setMemberType (Integer memberType){
        this.memberType = memberType;
    }
    public Long getFoAccOutCount (){
        return foAccOutCount;
    }
    
    public void setFoAccOutCount (Long foAccOutCount){
        this.foAccOutCount = foAccOutCount;
    }
    public Long getFiDepositRefundCount (){
        return fiDepositRefundCount;
    }
    
    public void setFiDepositRefundCount (Long fiDepositRefundCount){
        this.fiDepositRefundCount = fiDepositRefundCount;
    }
    public Long getFiDepositRefundAmount (){
        return fiDepositRefundAmount;
    }
    
    public void setFiDepositRefundAmount (Long fiDepositRefundAmount){
        this.fiDepositRefundAmount = fiDepositRefundAmount;
    }
    public Long getFoAccInAmount (){
        return foAccInAmount;
    }
    
    public void setFoAccInAmount (Long foAccInAmount){
        this.foAccInAmount = foAccInAmount;
    }
    public Long getFoWithdrowAmount (){
        return foWithdrowAmount;
    }
    
    public void setFoWithdrowAmount (Long foWithdrowAmount){
        this.foWithdrowAmount = foWithdrowAmount;
    }
    public Long getRefundAmount (){
        return refundAmount;
    }
    
    public void setRefundAmount (Long refundAmount){
        this.refundAmount = refundAmount;
    }
    public Long getAllCount (){
        return allCount;
    }
    
    public void setAllCount (Long allCount){
        this.allCount = allCount;
    }
    public String getName (){
        return name;
    }
    
    public void setName (String name){
        this.name = name;
    }
    public Long getFiAccOutAmount (){
        return fiAccOutAmount;
    }
    
    public void setFiAccOutAmount (Long fiAccOutAmount){
        this.fiAccOutAmount = fiAccOutAmount;
    }
    public Long getFiConsumeCardAmount (){
        return fiConsumeCardAmount;
    }
    
    public void setFiConsumeCardAmount (Long fiConsumeCardAmount){
        this.fiConsumeCardAmount = fiConsumeCardAmount;
    }
    public Long getFiPrepaidCardCount (){
        return fiPrepaidCardCount;
    }
    
    public void setFiPrepaidCardCount (Long fiPrepaidCardCount){
        this.fiPrepaidCardCount = fiPrepaidCardCount;
    }
    public java.util.Date getReportDate (){
        return reportDate;
    }
    
    public void setReportDate (java.util.Date reportDate){
        this.reportDate = reportDate;
    }
    public Long getRefund2AccAmount (){
        return refund2AccAmount;
    }
    
    public void setRefund2AccAmount (Long refund2AccAmount){
        this.refund2AccAmount = refund2AccAmount;
    }
    public Long getFoAccInCount (){
        return foAccInCount;
    }
    
    public void setFoAccInCount (Long foAccInCount){
        this.foAccInCount = foAccInCount;
    }
    public Long getFoAccOutAmount (){
        return foAccOutAmount;
    }
    
    public void setFoAccOutAmount (Long foAccOutAmount){
        this.foAccOutAmount = foAccOutAmount;
    }
    public String getMemberCode (){
        return memberCode;
    }
    
    public void setMemberCode (String memberCode){
        this.memberCode = memberCode;
    }
    public Long getFiConsumeCardCount (){
        return fiConsumeCardCount;
    }
    
    public void setFiConsumeCardCount (Long fiConsumeCardCount){
        this.fiConsumeCardCount = fiConsumeCardCount;
    }
    public java.util.Date getCteateDate (){
        return cteateDate;
    }
    
    public void setCteateDate (java.util.Date cteateDate){
        this.cteateDate = cteateDate;
    }
    public Long getFoBankAmount (){
        return foBankAmount;
    }
    
    public void setFoBankAmount (Long foBankAmount){
        this.foBankAmount = foBankAmount;
    }
    public Long getFiAccInCount (){
        return fiAccInCount;
    }
    
    public void setFiAccInCount (Long fiAccInCount){
        this.fiAccInCount = fiAccInCount;
    }
    public Long getFoBankCount (){
        return foBankCount;
    }
    
    public void setFoBankCount (Long foBankCount){
        this.foBankCount = foBankCount;
    }
    public Long getBankWithholdingCount (){
        return bankWithholdingCount;
    }
    
    public void setBankWithholdingCount (Long bankWithholdingCount){
        this.bankWithholdingCount = bankWithholdingCount;
    }
    public Long getFoWithdrowCount (){
        return foWithdrowCount;
    }
    
    public void setFoWithdrowCount (Long foWithdrowCount){
        this.foWithdrowCount = foWithdrowCount;
    }
    public Long getFiAccInAmount (){
        return fiAccInAmount;
    }
    
    public void setFiAccInAmount (Long fiAccInAmount){
        this.fiAccInAmount = fiAccInAmount;
    }
    public Long getFiDepositCount (){
        return fiDepositCount;
    }
    
    public void setFiDepositCount (Long fiDepositCount){
        this.fiDepositCount = fiDepositCount;
    }
    public Long getBankWithholdingAmount (){
        return bankWithholdingAmount;
    }
    
    public void setBankWithholdingAmount (Long bankWithholdingAmount){
        this.bankWithholdingAmount = bankWithholdingAmount;
    }
    public Long getFiPrepaidCardAmount (){
        return fiPrepaidCardAmount;
    }
    
    public void setFiPrepaidCardAmount (Long fiPrepaidCardAmount){
        this.fiPrepaidCardAmount = fiPrepaidCardAmount;
    }
    public Long getFiBankAmount (){
        return fiBankAmount;
    }
    
    public void setFiBankAmount (Long fiBankAmount){
        this.fiBankAmount = fiBankAmount;
    }
    public Long getFiBankCount (){
        return fiBankCount;
    }
    
    public void setFiBankCount (Long fiBankCount){
        this.fiBankCount = fiBankCount;
    }
    public Long getSequenceId (){
        return sequenceId;
    }
    
    public void setSequenceId (Long sequenceId){
        this.sequenceId = sequenceId;
    }
    public Long getFiAccOutCount (){
        return fiAccOutCount;
    }
    
    public void setFiAccOutCount (Long fiAccOutCount){
        this.fiAccOutCount = fiAccOutCount;
    }
    public Long getRefund2AccCount (){
        return refund2AccCount;
    }
    
    public void setRefund2AccCount (Long refund2AccCount){
        this.refund2AccCount = refund2AccCount;
    }
    public Long getFiMobilePosAmount (){
        return fiMobilePosAmount;
    }
    
    public void setFiMobilePosAmount (Long fiMobilePosAmount){
        this.fiMobilePosAmount = fiMobilePosAmount;
    }

	public Long getCreditQuickPayAmount() {
		return creditQuickPayAmount;
	}

	public void setCreditQuickPayAmount(Long creditQuickPayAmount) {
		this.creditQuickPayAmount = creditQuickPayAmount;
	}

	public Long getCreditQuickPayCount() {
		return creditQuickPayCount;
	}

	public void setCreditQuickPayCount(Long creditQuickPayCount) {
		this.creditQuickPayCount = creditQuickPayCount;
	}

	public Long getDebitQuickPayAmount() {
		return debitQuickPayAmount;
	}

	public void setDebitQuickPayAmount(Long debitQuickPayAmount) {
		this.debitQuickPayAmount = debitQuickPayAmount;
	}

	public Long getDebitQuickPayCount() {
		return debitQuickPayCount;
	}

	public void setDebitQuickPayCount(Long debitQuickPayCount) {
		this.debitQuickPayCount = debitQuickPayCount;
	}
}