/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.masspaytobank.impl;

import java.util.List;

import com.pay.fundout.withdraw.dao.masspaytobank.MassPaytobankOrderDAO;
import com.pay.fundout.withdraw.model.masspaytobank.MassPaytobankOrder;
import com.pay.fundout.withdraw.model.masspaytobank.MassPaytobankOrderTotalInfo;
import com.pay.inf.dao.impl.BaseDAOImpl;

@SuppressWarnings("unchecked")
public class MassPaytobankOrderDAOImpl extends BaseDAOImpl<MassPaytobankOrder>
		implements MassPaytobankOrderDAO {

	@Override
	public List<MassPaytobankOrder> getCompleteMassPaytobankOrder() {
		return getSqlMapClientTemplate().queryForList(
				this.namespace.concat("queryCompleteMassPaytobankOrder"));
	}

	@Override
	public MassPaytobankOrderTotalInfo totalComplateMassPaytobankOrderInfo(
			Long massOrderSeq) {
		return (MassPaytobankOrderTotalInfo) getSqlMapClientTemplate()
				.queryForObject(
						this.namespace
								.concat("totalCompleteMassPaytobankOrderDetails"),
						massOrderSeq);
	}

}