/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.withdrawbusiness.impl;

import com.pay.fundout.withdraw.dao.withdrawbusiness.WithdrawBusinessDAO;
import com.pay.inf.dao.impl.BaseDAOImpl;

@SuppressWarnings("unchecked")
public class WithdrawBusinessDAOImpl extends BaseDAOImpl implements
		WithdrawBusinessDAO {
}