package com.pay.fo.order.model.base;

import java.util.Date;

public class FundoutOrder {

	private String riskLeveCode;
	private String accountMode;
	private Integer isLoaning;// 是否垫资
	private String channelCode;// 出款渠道编号

	private Long orderId;
	private Integer orderType;
	private String orderSmallType;
	private Integer orderStatus;
	private Long orderAmount;
	private Integer isPayerPayFee;
	private Long fee;
	private Long realpayAmount;
	private Long realoutAmount;
	private String payerName;
	private String payerLoginName;
	private Long payerMemberCode;
	private Integer payerMemberType;
	private String payerAcctCode;
	private Integer payerAcctType;
	private String payeeName;
	private String payeeBankAcctCode;
	private Integer payeeBankAcctType;
	private String payeeBankCode;
	private String payeeBankName;
	private String payeeOpeningBankName;
	private String payeeBankProvince;
	private String payeeBankProvinceName;
	private String payeeBankCity;
	
	private Long balance ;
	
	public Long getBalance() {
		return balance;
	}

	public void setBalance(Long balance) {
		this.balance = balance;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.PAYEE_BANKCITYNAME
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String payeeBankCityName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.PAYMENT_REASON
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String paymentReason;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.FAILED_REASON
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String failedReason;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.CREATE_DATE
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private Date createDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.UPDATE_DATE
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private Date updateDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.TRADE_ALIAS
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String tradeAlias;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.TRADE_TYPE
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private Integer tradeType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.PAYEE_MOBILE
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String payeeMobile;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.BANK_ORDERID
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String bankOrderId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.FOREIGN_ORDERID
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String foreignOrderId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.FUNDOUT_BANKCODE
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String fundoutBankCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.FUNDOUT_BANKNAME
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private String fundoutBankName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.FUNDOUT_MODE
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private Integer fundoutMode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.PRIORITY
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private Integer priority;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FO.FUNDOUT_ORDER.PARENT_ORDERID
	 * 
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	private Long parentOrderId;

	private String bankNumber;

	private String fundoutRate;
	
	
	public String getFundoutRate() {
		return fundoutRate;
	}

	public void setFundoutRate(String fundoutRate) {
		this.fundoutRate = fundoutRate;
	}

	public String getBankNumber() {
		return bankNumber;
	}

	public void setBankNumber(String bankNumber) {
		this.bankNumber = bankNumber;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_ID
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.ORDER_ID
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_ID
	 * 
	 * @param orderId
	 *            the value for FO.FUNDOUT_ORDER.ORDER_ID
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_TYPE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.ORDER_TYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_TYPE
	 * 
	 * @param orderType
	 *            the value for FO.FUNDOUT_ORDER.ORDER_TYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_SMALLTYPE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.ORDER_SMALLTYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getOrderSmallType() {
		return orderSmallType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_SMALLTYPE
	 * 
	 * @param orderSmallType
	 *            the value for FO.FUNDOUT_ORDER.ORDER_SMALLTYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setOrderSmallType(String orderSmallType) {
		this.orderSmallType = orderSmallType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_STATUS
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.ORDER_STATUS
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_STATUS
	 * 
	 * @param orderStatus
	 *            the value for FO.FUNDOUT_ORDER.ORDER_STATUS
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_AMOUNT
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.ORDER_AMOUNT
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Long getOrderAmount() {
		return orderAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.ORDER_AMOUNT
	 * 
	 * @param orderAmount
	 *            the value for FO.FUNDOUT_ORDER.ORDER_AMOUNT
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setOrderAmount(Long orderAmount) {
		this.orderAmount = orderAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.IS_PAYERPAYFEE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.IS_PAYERPAYFEE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getIsPayerPayFee() {
		return isPayerPayFee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.IS_PAYERPAYFEE
	 * 
	 * @param isPayerPayFee
	 *            the value for FO.FUNDOUT_ORDER.IS_PAYERPAYFEE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setIsPayerPayFee(Integer isPayerPayFee) {
		this.isPayerPayFee = isPayerPayFee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.FEE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.FEE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Long getFee() {
		return fee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.FEE
	 * 
	 * @param fee
	 *            the value for FO.FUNDOUT_ORDER.FEE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setFee(Long fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.REALPAY_AMOUNT
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.REALPAY_AMOUNT
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Long getRealpayAmount() {
		return realpayAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.REALPAY_AMOUNT
	 * 
	 * @param realpayAmount
	 *            the value for FO.FUNDOUT_ORDER.REALPAY_AMOUNT
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setRealpayAmount(Long realpayAmount) {
		this.realpayAmount = realpayAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.REALOUT_AMOUNT
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.REALOUT_AMOUNT
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Long getRealoutAmount() {
		return realoutAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.REALOUT_AMOUNT
	 * 
	 * @param realoutAmount
	 *            the value for FO.FUNDOUT_ORDER.REALOUT_AMOUNT
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setRealoutAmount(Long realoutAmount) {
		this.realoutAmount = realoutAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_NAME
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYER_NAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayerName() {
		return payerName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_NAME
	 * 
	 * @param payerName
	 *            the value for FO.FUNDOUT_ORDER.PAYER_NAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_LOGINNAME
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYER_LOGINNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayerLoginName() {
		return payerLoginName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_LOGINNAME
	 * 
	 * @param payerLoginName
	 *            the value for FO.FUNDOUT_ORDER.PAYER_LOGINNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayerLoginName(String payerLoginName) {
		this.payerLoginName = payerLoginName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_MEMBERCODE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYER_MEMBERCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Long getPayerMemberCode() {
		return payerMemberCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_MEMBERCODE
	 * 
	 * @param payerMemberCode
	 *            the value for FO.FUNDOUT_ORDER.PAYER_MEMBERCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayerMemberCode(Long payerMemberCode) {
		this.payerMemberCode = payerMemberCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_MEMBERTYPE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYER_MEMBERTYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getPayerMemberType() {
		return payerMemberType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_MEMBERTYPE
	 * 
	 * @param payerMemberType
	 *            the value for FO.FUNDOUT_ORDER.PAYER_MEMBERTYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayerMemberType(Integer payerMemberType) {
		this.payerMemberType = payerMemberType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_ACCTCODE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYER_ACCTCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayerAcctCode() {
		return payerAcctCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_ACCTCODE
	 * 
	 * @param payerAcctCode
	 *            the value for FO.FUNDOUT_ORDER.PAYER_ACCTCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayerAcctCode(String payerAcctCode) {
		this.payerAcctCode = payerAcctCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_ACCTTYPE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYER_ACCTTYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getPayerAcctType() {
		return payerAcctType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYER_ACCTTYPE
	 * 
	 * @param payerAcctType
	 *            the value for FO.FUNDOUT_ORDER.PAYER_ACCTTYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayerAcctType(Integer payerAcctType) {
		this.payerAcctType = payerAcctType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_NAME
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_NAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeName() {
		return payeeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_NAME
	 * 
	 * @param payeeName
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_NAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKACCTCODE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_BANKACCTCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeBankAcctCode() {
		return payeeBankAcctCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKACCTCODE
	 * 
	 * @param payeeBankAcctCode
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_BANKACCTCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeBankAcctCode(String payeeBankAcctCode) {
		this.payeeBankAcctCode = payeeBankAcctCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKACCTTYPE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_BANKACCTTYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getPayeeBankAcctType() {
		return payeeBankAcctType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKACCTTYPE
	 * 
	 * @param payeeBankAcctType
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_BANKACCTTYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeBankAcctType(Integer payeeBankAcctType) {
		this.payeeBankAcctType = payeeBankAcctType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKCODE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_BANKCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeBankCode() {
		return payeeBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKCODE
	 * 
	 * @param payeeBankCode
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_BANKCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeBankCode(String payeeBankCode) {
		this.payeeBankCode = payeeBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKNAME
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_BANKNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeBankName() {
		return payeeBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKNAME
	 * 
	 * @param payeeBankName
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_BANKNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeBankName(String payeeBankName) {
		this.payeeBankName = payeeBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_OPENINGBANKNAME
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_OPENINGBANKNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeOpeningBankName() {
		return payeeOpeningBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_OPENINGBANKNAME
	 * 
	 * @param payeeOpeningBankName
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_OPENINGBANKNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeOpeningBankName(String payeeOpeningBankName) {
		this.payeeOpeningBankName = payeeOpeningBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKPROVINCE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_BANKPROVINCE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeBankProvince() {
		return payeeBankProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKPROVINCE
	 * 
	 * @param payeeBankProvince
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_BANKPROVINCE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeBankProvince(String payeeBankProvince) {
		this.payeeBankProvince = payeeBankProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKPROVINCENAME
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_BANKPROVINCENAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeBankProvinceName() {
		return payeeBankProvinceName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKPROVINCENAME
	 * 
	 * @param payeeBankProvinceName
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_BANKPROVINCENAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeBankProvinceName(String payeeBankProvinceName) {
		this.payeeBankProvinceName = payeeBankProvinceName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKCITY
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_BANKCITY
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeBankCity() {
		return payeeBankCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKCITY
	 * 
	 * @param payeeBankCity
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_BANKCITY
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeBankCity(String payeeBankCity) {
		this.payeeBankCity = payeeBankCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKCITYNAME
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_BANKCITYNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeBankCityName() {
		return payeeBankCityName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_BANKCITYNAME
	 * 
	 * @param payeeBankCityName
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_BANKCITYNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeBankCityName(String payeeBankCityName) {
		this.payeeBankCityName = payeeBankCityName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYMENT_REASON
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYMENT_REASON
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPaymentReason() {
		return paymentReason;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYMENT_REASON
	 * 
	 * @param paymentReason
	 *            the value for FO.FUNDOUT_ORDER.PAYMENT_REASON
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPaymentReason(String paymentReason) {
		this.paymentReason = paymentReason;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.FAILED_REASON
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.FAILED_REASON
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getFailedReason() {
		return failedReason;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.FAILED_REASON
	 * 
	 * @param failedReason
	 *            the value for FO.FUNDOUT_ORDER.FAILED_REASON
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setFailedReason(String failedReason) {
		this.failedReason = failedReason;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.CREATE_DATE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.CREATE_DATE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for FO.FUNDOUT_ORDER.CREATE_DATE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.UPDATE_DATE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.UPDATE_DATE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.UPDATE_DATE
	 * 
	 * @param updateDate
	 *            the value for FO.FUNDOUT_ORDER.UPDATE_DATE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.TRADE_ALIAS
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.TRADE_ALIAS
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getTradeAlias() {
		return tradeAlias;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.TRADE_ALIAS
	 * 
	 * @param tradeAlias
	 *            the value for FO.FUNDOUT_ORDER.TRADE_ALIAS
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setTradeAlias(String tradeAlias) {
		this.tradeAlias = tradeAlias;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.TRADE_TYPE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.TRADE_TYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.TRADE_TYPE
	 * 
	 * @param tradeType
	 *            the value for FO.FUNDOUT_ORDER.TRADE_TYPE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setTradeType(Integer tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_MOBILE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PAYEE_MOBILE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getPayeeMobile() {
		return payeeMobile;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PAYEE_MOBILE
	 * 
	 * @param payeeMobile
	 *            the value for FO.FUNDOUT_ORDER.PAYEE_MOBILE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPayeeMobile(String payeeMobile) {
		this.payeeMobile = payeeMobile;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.BANK_ORDERID
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.BANK_ORDERID
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getBankOrderId() {
		return bankOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.BANK_ORDERID
	 * 
	 * @param bankOrderId
	 *            the value for FO.FUNDOUT_ORDER.BANK_ORDERID
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setBankOrderId(String bankOrderId) {
		this.bankOrderId = bankOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.FOREIGN_ORDERID
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.FOREIGN_ORDERID
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getForeignOrderId() {
		return foreignOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.FOREIGN_ORDERID
	 * 
	 * @param foreignOrderId
	 *            the value for FO.FUNDOUT_ORDER.FOREIGN_ORDERID
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setForeignOrderId(String foreignOrderId) {
		this.foreignOrderId = foreignOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.FUNDOUT_BANKCODE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.FUNDOUT_BANKCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getFundoutBankCode() {
		return fundoutBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.FUNDOUT_BANKCODE
	 * 
	 * @param fundoutBankCode
	 *            the value for FO.FUNDOUT_ORDER.FUNDOUT_BANKCODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setFundoutBankCode(String fundoutBankCode) {
		this.fundoutBankCode = fundoutBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.FUNDOUT_BANKNAME
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.FUNDOUT_BANKNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public String getFundoutBankName() {
		return fundoutBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.FUNDOUT_BANKNAME
	 * 
	 * @param fundoutBankName
	 *            the value for FO.FUNDOUT_ORDER.FUNDOUT_BANKNAME
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setFundoutBankName(String fundoutBankName) {
		this.fundoutBankName = fundoutBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.FUNDOUT_MODE
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.FUNDOUT_MODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getFundoutMode() {
		return fundoutMode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.FUNDOUT_MODE
	 * 
	 * @param fundoutMode
	 *            the value for FO.FUNDOUT_ORDER.FUNDOUT_MODE
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setFundoutMode(Integer fundoutMode) {
		this.fundoutMode = fundoutMode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PRIORITY
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PRIORITY
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PRIORITY
	 * 
	 * @param priority
	 *            the value for FO.FUNDOUT_ORDER.PRIORITY
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FO.FUNDOUT_ORDER.PARENT_ORDERID
	 * 
	 * @return the value of FO.FUNDOUT_ORDER.PARENT_ORDERID
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public Long getParentOrderId() {
		return parentOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FO.FUNDOUT_ORDER.PARENT_ORDERID
	 * 
	 * @param parentOrderId
	 *            the value for FO.FUNDOUT_ORDER.PARENT_ORDERID
	 * @abatorgenerated Mon Jun 13 18:02:15 CST 2011
	 */
	public void setParentOrderId(Long parentOrderId) {
		this.parentOrderId = parentOrderId;
	}

	public String getChannelCode() {
		return channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	/**
	 * @return the riskLeveCode
	 */
	public String getRiskLeveCode() {
		return riskLeveCode;
	}

	public Integer getIsLoaning() {
		return isLoaning;
	}

	public void setIsLoaning(Integer isLoaning) {
		this.isLoaning = isLoaning;
	}

	/**
	 * @param riskLeveCode
	 *            the riskLeveCode to set
	 */
	public void setRiskLeveCode(String riskLeveCode) {
		this.riskLeveCode = riskLeveCode;
	}

	/**
	 * @return the accountMode
	 */
	public String getAccountMode() {
		return accountMode;
	}

	/**
	 * @param accountMode
	 *            the accountMode to set
	 */
	public void setAccountMode(String accountMode) {
		this.accountMode = accountMode;
	}
}