package com.pay.fo.order.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FundoutOrderExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	public FundoutOrderExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	protected FundoutOrderExample(FundoutOrderExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table FO.FUNDOUT_ORDER
	 * @abatorgenerated  Mon Jun 13 18:02:15 CST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("ORDER_ID is null");
			return this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("ORDER_ID is not null");
			return this;
		}

		public Criteria andOrderIdEqualTo(Long value) {
			addCriterion("ORDER_ID =", value, "orderId");
			return this;
		}

		public Criteria andOrderIdNotEqualTo(Long value) {
			addCriterion("ORDER_ID <>", value, "orderId");
			return this;
		}

		public Criteria andOrderIdGreaterThan(Long value) {
			addCriterion("ORDER_ID >", value, "orderId");
			return this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ORDER_ID >=", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLessThan(Long value) {
			addCriterion("ORDER_ID <", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Long value) {
			addCriterion("ORDER_ID <=", value, "orderId");
			return this;
		}

		public Criteria andOrderIdIn(List values) {
			addCriterion("ORDER_ID in", values, "orderId");
			return this;
		}

		public Criteria andOrderIdNotIn(List values) {
			addCriterion("ORDER_ID not in", values, "orderId");
			return this;
		}

		public Criteria andOrderIdBetween(Long value1, Long value2) {
			addCriterion("ORDER_ID between", value1, value2, "orderId");
			return this;
		}

		public Criteria andOrderIdNotBetween(Long value1,
				Long value2) {
			addCriterion("ORDER_ID not between", value1, value2, "orderId");
			return this;
		}

		public Criteria andOrderTypeIsNull() {
			addCriterion("ORDER_TYPE is null");
			return this;
		}

		public Criteria andOrderTypeIsNotNull() {
			addCriterion("ORDER_TYPE is not null");
			return this;
		}

		public Criteria andOrderTypeEqualTo(Integer value) {
			addCriterion("ORDER_TYPE =", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotEqualTo(Integer value) {
			addCriterion("ORDER_TYPE <>", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeGreaterThan(Integer value) {
			addCriterion("ORDER_TYPE >", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORDER_TYPE >=", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeLessThan(Integer value) {
			addCriterion("ORDER_TYPE <", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeLessThanOrEqualTo(Integer value) {
			addCriterion("ORDER_TYPE <=", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeIn(List values) {
			addCriterion("ORDER_TYPE in", values, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotIn(List values) {
			addCriterion("ORDER_TYPE not in", values, "orderType");
			return this;
		}

		public Criteria andOrderTypeBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_TYPE between", value1, value2, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_TYPE not between", value1, value2, "orderType");
			return this;
		}

		public Criteria andOrderSmallTypeIsNull() {
			addCriterion("ORDER_SMALLTYPE is null");
			return this;
		}

		public Criteria andOrderSmallTypeIsNotNull() {
			addCriterion("ORDER_SMALLTYPE is not null");
			return this;
		}

		public Criteria andOrderSmallTypeEqualTo(String value) {
			addCriterion("ORDER_SMALLTYPE =", value, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeNotEqualTo(String value) {
			addCriterion("ORDER_SMALLTYPE <>", value, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeGreaterThan(String value) {
			addCriterion("ORDER_SMALLTYPE >", value, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_SMALLTYPE >=", value, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeLessThan(String value) {
			addCriterion("ORDER_SMALLTYPE <", value, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeLessThanOrEqualTo(String value) {
			addCriterion("ORDER_SMALLTYPE <=", value, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeLike(String value) {
			addCriterion("ORDER_SMALLTYPE like", value, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeNotLike(String value) {
			addCriterion("ORDER_SMALLTYPE not like", value, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeIn(List values) {
			addCriterion("ORDER_SMALLTYPE in", values, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeNotIn(List values) {
			addCriterion("ORDER_SMALLTYPE not in", values, "orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeBetween(String value1, String value2) {
			addCriterion("ORDER_SMALLTYPE between", value1, value2,
					"orderSmallType");
			return this;
		}

		public Criteria andOrderSmallTypeNotBetween(String value1, String value2) {
			addCriterion("ORDER_SMALLTYPE not between", value1, value2,
					"orderSmallType");
			return this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("ORDER_STATUS is null");
			return this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("ORDER_STATUS is not null");
			return this;
		}

		public Criteria andOrderStatusEqualTo(Integer value) {
			addCriterion("ORDER_STATUS =", value, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusNotEqualTo(Integer value) {
			addCriterion("ORDER_STATUS <>", value, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusGreaterThan(Integer value) {
			addCriterion("ORDER_STATUS >", value, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORDER_STATUS >=", value, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusLessThan(Integer value) {
			addCriterion("ORDER_STATUS <", value, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
			addCriterion("ORDER_STATUS <=", value, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusIn(List values) {
			addCriterion("ORDER_STATUS in", values, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusNotIn(List values) {
			addCriterion("ORDER_STATUS not in", values, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_STATUS between", value1, value2, "orderStatus");
			return this;
		}

		public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_STATUS not between", value1, value2,
					"orderStatus");
			return this;
		}

		public Criteria andOrderAmountIsNull() {
			addCriterion("ORDER_AMOUNT is null");
			return this;
		}

		public Criteria andOrderAmountIsNotNull() {
			addCriterion("ORDER_AMOUNT is not null");
			return this;
		}

		public Criteria andOrderAmountEqualTo(Long value) {
			addCriterion("ORDER_AMOUNT =", value, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountNotEqualTo(Long value) {
			addCriterion("ORDER_AMOUNT <>", value, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountGreaterThan(Long value) {
			addCriterion("ORDER_AMOUNT >", value, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountGreaterThanOrEqualTo(Long value) {
			addCriterion("ORDER_AMOUNT >=", value, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountLessThan(Long value) {
			addCriterion("ORDER_AMOUNT <", value, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountLessThanOrEqualTo(Long value) {
			addCriterion("ORDER_AMOUNT <=", value, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountIn(List values) {
			addCriterion("ORDER_AMOUNT in", values, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountNotIn(List values) {
			addCriterion("ORDER_AMOUNT not in", values, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountBetween(Long value1,
				Long value2) {
			addCriterion("ORDER_AMOUNT between", value1, value2, "orderAmount");
			return this;
		}

		public Criteria andOrderAmountNotBetween(Long value1,
				Long value2) {
			addCriterion("ORDER_AMOUNT not between", value1, value2,
					"orderAmount");
			return this;
		}

		public Criteria andIsPayerPayFeeIsNull() {
			addCriterion("IS_PAYERPAYFEE is null");
			return this;
		}

		public Criteria andIsPayerPayFeeIsNotNull() {
			addCriterion("IS_PAYERPAYFEE is not null");
			return this;
		}

		public Criteria andIsPayerPayFeeEqualTo(Integer value) {
			addCriterion("IS_PAYERPAYFEE =", value, "isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeNotEqualTo(Integer value) {
			addCriterion("IS_PAYERPAYFEE <>", value, "isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeGreaterThan(Integer value) {
			addCriterion("IS_PAYERPAYFEE >", value, "isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeGreaterThanOrEqualTo(Integer value) {
			addCriterion("IS_PAYERPAYFEE >=", value, "isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeLessThan(Integer value) {
			addCriterion("IS_PAYERPAYFEE <", value, "isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeLessThanOrEqualTo(Integer value) {
			addCriterion("IS_PAYERPAYFEE <=", value, "isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeIn(List values) {
			addCriterion("IS_PAYERPAYFEE in", values, "isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeNotIn(List values) {
			addCriterion("IS_PAYERPAYFEE not in", values, "isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeBetween(Integer value1, Integer value2) {
			addCriterion("IS_PAYERPAYFEE between", value1, value2,
					"isPayerPayFee");
			return this;
		}

		public Criteria andIsPayerPayFeeNotBetween(Integer value1, Integer value2) {
			addCriterion("IS_PAYERPAYFEE not between", value1, value2,
					"isPayerPayFee");
			return this;
		}

		public Criteria andFeeIsNull() {
			addCriterion("FEE is null");
			return this;
		}

		public Criteria andFeeIsNotNull() {
			addCriterion("FEE is not null");
			return this;
		}

		public Criteria andFeeEqualTo(Long value) {
			addCriterion("FEE =", value, "fee");
			return this;
		}

		public Criteria andFeeNotEqualTo(Long value) {
			addCriterion("FEE <>", value, "fee");
			return this;
		}

		public Criteria andFeeGreaterThan(Long value) {
			addCriterion("FEE >", value, "fee");
			return this;
		}

		public Criteria andFeeGreaterThanOrEqualTo(Long value) {
			addCriterion("FEE >=", value, "fee");
			return this;
		}

		public Criteria andFeeLessThan(Long value) {
			addCriterion("FEE <", value, "fee");
			return this;
		}

		public Criteria andFeeLessThanOrEqualTo(Long value) {
			addCriterion("FEE <=", value, "fee");
			return this;
		}

		public Criteria andFeeIn(List values) {
			addCriterion("FEE in", values, "fee");
			return this;
		}

		public Criteria andFeeNotIn(List values) {
			addCriterion("FEE not in", values, "fee");
			return this;
		}

		public Criteria andFeeBetween(Long value1, Long value2) {
			addCriterion("FEE between", value1, value2, "fee");
			return this;
		}

		public Criteria andFeeNotBetween(Long value1, Long value2) {
			addCriterion("FEE not between", value1, value2, "fee");
			return this;
		}

		public Criteria andRealpayAmountIsNull() {
			addCriterion("REALPAY_AMOUNT is null");
			return this;
		}

		public Criteria andRealpayAmountIsNotNull() {
			addCriterion("REALPAY_AMOUNT is not null");
			return this;
		}

		public Criteria andRealpayAmountEqualTo(Long value) {
			addCriterion("REALPAY_AMOUNT =", value, "realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountNotEqualTo(Long value) {
			addCriterion("REALPAY_AMOUNT <>", value, "realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountGreaterThan(Long value) {
			addCriterion("REALPAY_AMOUNT >", value, "realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountGreaterThanOrEqualTo(Long value) {
			addCriterion("REALPAY_AMOUNT >=", value, "realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountLessThan(Long value) {
			addCriterion("REALPAY_AMOUNT <", value, "realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountLessThanOrEqualTo(Long value) {
			addCriterion("REALPAY_AMOUNT <=", value, "realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountIn(List values) {
			addCriterion("REALPAY_AMOUNT in", values, "realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountNotIn(List values) {
			addCriterion("REALPAY_AMOUNT not in", values, "realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountBetween(Long value1,
				Long value2) {
			addCriterion("REALPAY_AMOUNT between", value1, value2,
					"realpayAmount");
			return this;
		}

		public Criteria andRealpayAmountNotBetween(Long value1,
				Long value2) {
			addCriterion("REALPAY_AMOUNT not between", value1, value2,
					"realpayAmount");
			return this;
		}

		public Criteria andRealoutAmountIsNull() {
			addCriterion("REALOUT_AMOUNT is null");
			return this;
		}

		public Criteria andRealoutAmountIsNotNull() {
			addCriterion("REALOUT_AMOUNT is not null");
			return this;
		}

		public Criteria andRealoutAmountEqualTo(Long value) {
			addCriterion("REALOUT_AMOUNT =", value, "realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountNotEqualTo(Long value) {
			addCriterion("REALOUT_AMOUNT <>", value, "realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountGreaterThan(Long value) {
			addCriterion("REALOUT_AMOUNT >", value, "realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountGreaterThanOrEqualTo(Long value) {
			addCriterion("REALOUT_AMOUNT >=", value, "realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountLessThan(Long value) {
			addCriterion("REALOUT_AMOUNT <", value, "realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountLessThanOrEqualTo(Long value) {
			addCriterion("REALOUT_AMOUNT <=", value, "realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountIn(List values) {
			addCriterion("REALOUT_AMOUNT in", values, "realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountNotIn(List values) {
			addCriterion("REALOUT_AMOUNT not in", values, "realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountBetween(Long value1,
				Long value2) {
			addCriterion("REALOUT_AMOUNT between", value1, value2,
					"realoutAmount");
			return this;
		}

		public Criteria andRealoutAmountNotBetween(Long value1,
				Long value2) {
			addCriterion("REALOUT_AMOUNT not between", value1, value2,
					"realoutAmount");
			return this;
		}

		public Criteria andPayerNameIsNull() {
			addCriterion("PAYER_NAME is null");
			return this;
		}

		public Criteria andPayerNameIsNotNull() {
			addCriterion("PAYER_NAME is not null");
			return this;
		}

		public Criteria andPayerNameEqualTo(String value) {
			addCriterion("PAYER_NAME =", value, "payerName");
			return this;
		}

		public Criteria andPayerNameNotEqualTo(String value) {
			addCriterion("PAYER_NAME <>", value, "payerName");
			return this;
		}

		public Criteria andPayerNameGreaterThan(String value) {
			addCriterion("PAYER_NAME >", value, "payerName");
			return this;
		}

		public Criteria andPayerNameGreaterThanOrEqualTo(String value) {
			addCriterion("PAYER_NAME >=", value, "payerName");
			return this;
		}

		public Criteria andPayerNameLessThan(String value) {
			addCriterion("PAYER_NAME <", value, "payerName");
			return this;
		}

		public Criteria andPayerNameLessThanOrEqualTo(String value) {
			addCriterion("PAYER_NAME <=", value, "payerName");
			return this;
		}

		public Criteria andPayerNameLike(String value) {
			addCriterion("PAYER_NAME like", value, "payerName");
			return this;
		}

		public Criteria andPayerNameNotLike(String value) {
			addCriterion("PAYER_NAME not like", value, "payerName");
			return this;
		}

		public Criteria andPayerNameIn(List values) {
			addCriterion("PAYER_NAME in", values, "payerName");
			return this;
		}

		public Criteria andPayerNameNotIn(List values) {
			addCriterion("PAYER_NAME not in", values, "payerName");
			return this;
		}

		public Criteria andPayerNameBetween(String value1, String value2) {
			addCriterion("PAYER_NAME between", value1, value2, "payerName");
			return this;
		}

		public Criteria andPayerNameNotBetween(String value1, String value2) {
			addCriterion("PAYER_NAME not between", value1, value2, "payerName");
			return this;
		}

		public Criteria andPayerLoginNameIsNull() {
			addCriterion("PAYER_LOGINNAME is null");
			return this;
		}

		public Criteria andPayerLoginNameIsNotNull() {
			addCriterion("PAYER_LOGINNAME is not null");
			return this;
		}

		public Criteria andPayerLoginNameEqualTo(String value) {
			addCriterion("PAYER_LOGINNAME =", value, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameNotEqualTo(String value) {
			addCriterion("PAYER_LOGINNAME <>", value, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameGreaterThan(String value) {
			addCriterion("PAYER_LOGINNAME >", value, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("PAYER_LOGINNAME >=", value, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameLessThan(String value) {
			addCriterion("PAYER_LOGINNAME <", value, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameLessThanOrEqualTo(String value) {
			addCriterion("PAYER_LOGINNAME <=", value, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameLike(String value) {
			addCriterion("PAYER_LOGINNAME like", value, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameNotLike(String value) {
			addCriterion("PAYER_LOGINNAME not like", value, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameIn(List values) {
			addCriterion("PAYER_LOGINNAME in", values, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameNotIn(List values) {
			addCriterion("PAYER_LOGINNAME not in", values, "payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameBetween(String value1, String value2) {
			addCriterion("PAYER_LOGINNAME between", value1, value2,
					"payerLoginName");
			return this;
		}

		public Criteria andPayerLoginNameNotBetween(String value1, String value2) {
			addCriterion("PAYER_LOGINNAME not between", value1, value2,
					"payerLoginName");
			return this;
		}

		public Criteria andPayerMemberCodeIsNull() {
			addCriterion("PAYER_MEMBERCODE is null");
			return this;
		}

		public Criteria andPayerMemberCodeIsNotNull() {
			addCriterion("PAYER_MEMBERCODE is not null");
			return this;
		}

		public Criteria andPayerMemberCodeEqualTo(Long value) {
			addCriterion("PAYER_MEMBERCODE =", value, "payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeNotEqualTo(Long value) {
			addCriterion("PAYER_MEMBERCODE <>", value, "payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeGreaterThan(Long value) {
			addCriterion("PAYER_MEMBERCODE >", value, "payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeGreaterThanOrEqualTo(Long value) {
			addCriterion("PAYER_MEMBERCODE >=", value, "payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeLessThan(Long value) {
			addCriterion("PAYER_MEMBERCODE <", value, "payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeLessThanOrEqualTo(Long value) {
			addCriterion("PAYER_MEMBERCODE <=", value, "payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeIn(List values) {
			addCriterion("PAYER_MEMBERCODE in", values, "payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeNotIn(List values) {
			addCriterion("PAYER_MEMBERCODE not in", values, "payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeBetween(Long value1, Long value2) {
			addCriterion("PAYER_MEMBERCODE between", value1, value2,
					"payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberCodeNotBetween(Long value1, Long value2) {
			addCriterion("PAYER_MEMBERCODE not between", value1, value2,
					"payerMemberCode");
			return this;
		}

		public Criteria andPayerMemberTypeIsNull() {
			addCriterion("PAYER_MEMBERTYPE is null");
			return this;
		}

		public Criteria andPayerMemberTypeIsNotNull() {
			addCriterion("PAYER_MEMBERTYPE is not null");
			return this;
		}

		public Criteria andPayerMemberTypeEqualTo(Integer value) {
			addCriterion("PAYER_MEMBERTYPE =", value, "payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeNotEqualTo(Integer value) {
			addCriterion("PAYER_MEMBERTYPE <>", value, "payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeGreaterThan(Integer value) {
			addCriterion("PAYER_MEMBERTYPE >", value, "payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("PAYER_MEMBERTYPE >=", value, "payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeLessThan(Integer value) {
			addCriterion("PAYER_MEMBERTYPE <", value, "payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeLessThanOrEqualTo(Integer value) {
			addCriterion("PAYER_MEMBERTYPE <=", value, "payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeIn(List values) {
			addCriterion("PAYER_MEMBERTYPE in", values, "payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeNotIn(List values) {
			addCriterion("PAYER_MEMBERTYPE not in", values, "payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeBetween(Integer value1, Integer value2) {
			addCriterion("PAYER_MEMBERTYPE between", value1, value2,
					"payerMemberType");
			return this;
		}

		public Criteria andPayerMemberTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("PAYER_MEMBERTYPE not between", value1, value2,
					"payerMemberType");
			return this;
		}

		public Criteria andPayerAcctCodeIsNull() {
			addCriterion("PAYER_ACCTCODE is null");
			return this;
		}

		public Criteria andPayerAcctCodeIsNotNull() {
			addCriterion("PAYER_ACCTCODE is not null");
			return this;
		}

		public Criteria andPayerAcctCodeEqualTo(String value) {
			addCriterion("PAYER_ACCTCODE =", value, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeNotEqualTo(String value) {
			addCriterion("PAYER_ACCTCODE <>", value, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeGreaterThan(String value) {
			addCriterion("PAYER_ACCTCODE >", value, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeGreaterThanOrEqualTo(String value) {
			addCriterion("PAYER_ACCTCODE >=", value, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeLessThan(String value) {
			addCriterion("PAYER_ACCTCODE <", value, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeLessThanOrEqualTo(String value) {
			addCriterion("PAYER_ACCTCODE <=", value, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeLike(String value) {
			addCriterion("PAYER_ACCTCODE like", value, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeNotLike(String value) {
			addCriterion("PAYER_ACCTCODE not like", value, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeIn(List values) {
			addCriterion("PAYER_ACCTCODE in", values, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeNotIn(List values) {
			addCriterion("PAYER_ACCTCODE not in", values, "payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeBetween(String value1, String value2) {
			addCriterion("PAYER_ACCTCODE between", value1, value2,
					"payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctCodeNotBetween(String value1, String value2) {
			addCriterion("PAYER_ACCTCODE not between", value1, value2,
					"payerAcctCode");
			return this;
		}

		public Criteria andPayerAcctTypeIsNull() {
			addCriterion("PAYER_ACCTTYPE is null");
			return this;
		}

		public Criteria andPayerAcctTypeIsNotNull() {
			addCriterion("PAYER_ACCTTYPE is not null");
			return this;
		}

		public Criteria andPayerAcctTypeEqualTo(Integer value) {
			addCriterion("PAYER_ACCTTYPE =", value, "payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeNotEqualTo(Integer value) {
			addCriterion("PAYER_ACCTTYPE <>", value, "payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeGreaterThan(Integer value) {
			addCriterion("PAYER_ACCTTYPE >", value, "payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("PAYER_ACCTTYPE >=", value, "payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeLessThan(Integer value) {
			addCriterion("PAYER_ACCTTYPE <", value, "payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeLessThanOrEqualTo(Integer value) {
			addCriterion("PAYER_ACCTTYPE <=", value, "payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeIn(List values) {
			addCriterion("PAYER_ACCTTYPE in", values, "payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeNotIn(List values) {
			addCriterion("PAYER_ACCTTYPE not in", values, "payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeBetween(Integer value1, Integer value2) {
			addCriterion("PAYER_ACCTTYPE between", value1, value2,
					"payerAcctType");
			return this;
		}

		public Criteria andPayerAcctTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("PAYER_ACCTTYPE not between", value1, value2,
					"payerAcctType");
			return this;
		}

		public Criteria andPayeeNameIsNull() {
			addCriterion("PAYEE_NAME is null");
			return this;
		}

		public Criteria andPayeeNameIsNotNull() {
			addCriterion("PAYEE_NAME is not null");
			return this;
		}

		public Criteria andPayeeNameEqualTo(String value) {
			addCriterion("PAYEE_NAME =", value, "payeeName");
			return this;
		}

		public Criteria andPayeeNameNotEqualTo(String value) {
			addCriterion("PAYEE_NAME <>", value, "payeeName");
			return this;
		}

		public Criteria andPayeeNameGreaterThan(String value) {
			addCriterion("PAYEE_NAME >", value, "payeeName");
			return this;
		}

		public Criteria andPayeeNameGreaterThanOrEqualTo(String value) {
			addCriterion("PAYEE_NAME >=", value, "payeeName");
			return this;
		}

		public Criteria andPayeeNameLessThan(String value) {
			addCriterion("PAYEE_NAME <", value, "payeeName");
			return this;
		}

		public Criteria andPayeeNameLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_NAME <=", value, "payeeName");
			return this;
		}

		public Criteria andPayeeNameLike(String value) {
			addCriterion("PAYEE_NAME like", value, "payeeName");
			return this;
		}

		public Criteria andPayeeNameNotLike(String value) {
			addCriterion("PAYEE_NAME not like", value, "payeeName");
			return this;
		}

		public Criteria andPayeeNameIn(List values) {
			addCriterion("PAYEE_NAME in", values, "payeeName");
			return this;
		}

		public Criteria andPayeeNameNotIn(List values) {
			addCriterion("PAYEE_NAME not in", values, "payeeName");
			return this;
		}

		public Criteria andPayeeNameBetween(String value1, String value2) {
			addCriterion("PAYEE_NAME between", value1, value2, "payeeName");
			return this;
		}

		public Criteria andPayeeNameNotBetween(String value1, String value2) {
			addCriterion("PAYEE_NAME not between", value1, value2, "payeeName");
			return this;
		}

		public Criteria andPayeeBankAcctCodeIsNull() {
			addCriterion("PAYEE_BANKACCTCODE is null");
			return this;
		}

		public Criteria andPayeeBankAcctCodeIsNotNull() {
			addCriterion("PAYEE_BANKACCTCODE is not null");
			return this;
		}

		public Criteria andPayeeBankAcctCodeEqualTo(String value) {
			addCriterion("PAYEE_BANKACCTCODE =", value, "payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeNotEqualTo(String value) {
			addCriterion("PAYEE_BANKACCTCODE <>", value, "payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeGreaterThan(String value) {
			addCriterion("PAYEE_BANKACCTCODE >", value, "payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeGreaterThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKACCTCODE >=", value, "payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeLessThan(String value) {
			addCriterion("PAYEE_BANKACCTCODE <", value, "payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKACCTCODE <=", value, "payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeLike(String value) {
			addCriterion("PAYEE_BANKACCTCODE like", value, "payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeNotLike(String value) {
			addCriterion("PAYEE_BANKACCTCODE not like", value,
					"payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeIn(List values) {
			addCriterion("PAYEE_BANKACCTCODE in", values, "payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeNotIn(List values) {
			addCriterion("PAYEE_BANKACCTCODE not in", values,
					"payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeBetween(String value1, String value2) {
			addCriterion("PAYEE_BANKACCTCODE between", value1, value2,
					"payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctCodeNotBetween(String value1,
				String value2) {
			addCriterion("PAYEE_BANKACCTCODE not between", value1, value2,
					"payeeBankAcctCode");
			return this;
		}

		public Criteria andPayeeBankAcctTypeIsNull() {
			addCriterion("PAYEE_BANKACCTTYPE is null");
			return this;
		}

		public Criteria andPayeeBankAcctTypeIsNotNull() {
			addCriterion("PAYEE_BANKACCTTYPE is not null");
			return this;
		}

		public Criteria andPayeeBankAcctTypeEqualTo(Integer value) {
			addCriterion("PAYEE_BANKACCTTYPE =", value, "payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeNotEqualTo(Integer value) {
			addCriterion("PAYEE_BANKACCTTYPE <>", value, "payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeGreaterThan(Integer value) {
			addCriterion("PAYEE_BANKACCTTYPE >", value, "payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("PAYEE_BANKACCTTYPE >=", value, "payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeLessThan(Integer value) {
			addCriterion("PAYEE_BANKACCTTYPE <", value, "payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeLessThanOrEqualTo(Integer value) {
			addCriterion("PAYEE_BANKACCTTYPE <=", value, "payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeIn(List values) {
			addCriterion("PAYEE_BANKACCTTYPE in", values, "payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeNotIn(List values) {
			addCriterion("PAYEE_BANKACCTTYPE not in", values,
					"payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeBetween(Integer value1, Integer value2) {
			addCriterion("PAYEE_BANKACCTTYPE between", value1, value2,
					"payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankAcctTypeNotBetween(Integer value1,
				Integer value2) {
			addCriterion("PAYEE_BANKACCTTYPE not between", value1, value2,
					"payeeBankAcctType");
			return this;
		}

		public Criteria andPayeeBankCodeIsNull() {
			addCriterion("PAYEE_BANKCODE is null");
			return this;
		}

		public Criteria andPayeeBankCodeIsNotNull() {
			addCriterion("PAYEE_BANKCODE is not null");
			return this;
		}

		public Criteria andPayeeBankCodeEqualTo(Long value) {
			addCriterion("PAYEE_BANKCODE =", value, "payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeNotEqualTo(Long value) {
			addCriterion("PAYEE_BANKCODE <>", value, "payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeGreaterThan(Long value) {
			addCriterion("PAYEE_BANKCODE >", value, "payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeGreaterThanOrEqualTo(Long value) {
			addCriterion("PAYEE_BANKCODE >=", value, "payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeLessThan(Long value) {
			addCriterion("PAYEE_BANKCODE <", value, "payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeLessThanOrEqualTo(Long value) {
			addCriterion("PAYEE_BANKCODE <=", value, "payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeIn(List values) {
			addCriterion("PAYEE_BANKCODE in", values, "payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeNotIn(List values) {
			addCriterion("PAYEE_BANKCODE not in", values, "payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeBetween(Long value1, Long value2) {
			addCriterion("PAYEE_BANKCODE between", value1, value2,
					"payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankCodeNotBetween(Long value1, Long value2) {
			addCriterion("PAYEE_BANKCODE not between", value1, value2,
					"payeeBankCode");
			return this;
		}

		public Criteria andPayeeBankNameIsNull() {
			addCriterion("PAYEE_BANKNAME is null");
			return this;
		}

		public Criteria andPayeeBankNameIsNotNull() {
			addCriterion("PAYEE_BANKNAME is not null");
			return this;
		}

		public Criteria andPayeeBankNameEqualTo(String value) {
			addCriterion("PAYEE_BANKNAME =", value, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameNotEqualTo(String value) {
			addCriterion("PAYEE_BANKNAME <>", value, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameGreaterThan(String value) {
			addCriterion("PAYEE_BANKNAME >", value, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKNAME >=", value, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameLessThan(String value) {
			addCriterion("PAYEE_BANKNAME <", value, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKNAME <=", value, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameLike(String value) {
			addCriterion("PAYEE_BANKNAME like", value, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameNotLike(String value) {
			addCriterion("PAYEE_BANKNAME not like", value, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameIn(List values) {
			addCriterion("PAYEE_BANKNAME in", values, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameNotIn(List values) {
			addCriterion("PAYEE_BANKNAME not in", values, "payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameBetween(String value1, String value2) {
			addCriterion("PAYEE_BANKNAME between", value1, value2,
					"payeeBankName");
			return this;
		}

		public Criteria andPayeeBankNameNotBetween(String value1, String value2) {
			addCriterion("PAYEE_BANKNAME not between", value1, value2,
					"payeeBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameIsNull() {
			addCriterion("PAYEE_OPENINGBANKNAME is null");
			return this;
		}

		public Criteria andPayeeOpeningBankNameIsNotNull() {
			addCriterion("PAYEE_OPENINGBANKNAME is not null");
			return this;
		}

		public Criteria andPayeeOpeningBankNameEqualTo(String value) {
			addCriterion("PAYEE_OPENINGBANKNAME =", value,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameNotEqualTo(String value) {
			addCriterion("PAYEE_OPENINGBANKNAME <>", value,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameGreaterThan(String value) {
			addCriterion("PAYEE_OPENINGBANKNAME >", value,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("PAYEE_OPENINGBANKNAME >=", value,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameLessThan(String value) {
			addCriterion("PAYEE_OPENINGBANKNAME <", value,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_OPENINGBANKNAME <=", value,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameLike(String value) {
			addCriterion("PAYEE_OPENINGBANKNAME like", value,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameNotLike(String value) {
			addCriterion("PAYEE_OPENINGBANKNAME not like", value,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameIn(List values) {
			addCriterion("PAYEE_OPENINGBANKNAME in", values,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameNotIn(List values) {
			addCriterion("PAYEE_OPENINGBANKNAME not in", values,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameBetween(String value1,
				String value2) {
			addCriterion("PAYEE_OPENINGBANKNAME between", value1, value2,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeOpeningBankNameNotBetween(String value1,
				String value2) {
			addCriterion("PAYEE_OPENINGBANKNAME not between", value1, value2,
					"payeeOpeningBankName");
			return this;
		}

		public Criteria andPayeeBankProvinceIsNull() {
			addCriterion("PAYEE_BANKPROVINCE is null");
			return this;
		}

		public Criteria andPayeeBankProvinceIsNotNull() {
			addCriterion("PAYEE_BANKPROVINCE is not null");
			return this;
		}

		public Criteria andPayeeBankProvinceEqualTo(String value) {
			addCriterion("PAYEE_BANKPROVINCE =", value, "payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceNotEqualTo(String value) {
			addCriterion("PAYEE_BANKPROVINCE <>", value, "payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceGreaterThan(String value) {
			addCriterion("PAYEE_BANKPROVINCE >", value, "payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKPROVINCE >=", value, "payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceLessThan(String value) {
			addCriterion("PAYEE_BANKPROVINCE <", value, "payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKPROVINCE <=", value, "payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceLike(String value) {
			addCriterion("PAYEE_BANKPROVINCE like", value, "payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceNotLike(String value) {
			addCriterion("PAYEE_BANKPROVINCE not like", value,
					"payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceIn(List values) {
			addCriterion("PAYEE_BANKPROVINCE in", values, "payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceNotIn(List values) {
			addCriterion("PAYEE_BANKPROVINCE not in", values,
					"payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceBetween(String value1, String value2) {
			addCriterion("PAYEE_BANKPROVINCE between", value1, value2,
					"payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceNotBetween(String value1,
				String value2) {
			addCriterion("PAYEE_BANKPROVINCE not between", value1, value2,
					"payeeBankProvince");
			return this;
		}

		public Criteria andPayeeBankProvinceNameIsNull() {
			addCriterion("PAYEE_BANKPROVINCENAME is null");
			return this;
		}

		public Criteria andPayeeBankProvinceNameIsNotNull() {
			addCriterion("PAYEE_BANKPROVINCENAME is not null");
			return this;
		}

		public Criteria andPayeeBankProvinceNameEqualTo(String value) {
			addCriterion("PAYEE_BANKPROVINCENAME =", value,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameNotEqualTo(String value) {
			addCriterion("PAYEE_BANKPROVINCENAME <>", value,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameGreaterThan(String value) {
			addCriterion("PAYEE_BANKPROVINCENAME >", value,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameGreaterThanOrEqualTo(
				String value) {
			addCriterion("PAYEE_BANKPROVINCENAME >=", value,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameLessThan(String value) {
			addCriterion("PAYEE_BANKPROVINCENAME <", value,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKPROVINCENAME <=", value,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameLike(String value) {
			addCriterion("PAYEE_BANKPROVINCENAME like", value,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameNotLike(String value) {
			addCriterion("PAYEE_BANKPROVINCENAME not like", value,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameIn(List values) {
			addCriterion("PAYEE_BANKPROVINCENAME in", values,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameNotIn(List values) {
			addCriterion("PAYEE_BANKPROVINCENAME not in", values,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameBetween(String value1,
				String value2) {
			addCriterion("PAYEE_BANKPROVINCENAME between", value1, value2,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankProvinceNameNotBetween(String value1,
				String value2) {
			addCriterion("PAYEE_BANKPROVINCENAME not between", value1, value2,
					"payeeBankProvinceName");
			return this;
		}

		public Criteria andPayeeBankCityIsNull() {
			addCriterion("PAYEE_BANKCITY is null");
			return this;
		}

		public Criteria andPayeeBankCityIsNotNull() {
			addCriterion("PAYEE_BANKCITY is not null");
			return this;
		}

		public Criteria andPayeeBankCityEqualTo(String value) {
			addCriterion("PAYEE_BANKCITY =", value, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityNotEqualTo(String value) {
			addCriterion("PAYEE_BANKCITY <>", value, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityGreaterThan(String value) {
			addCriterion("PAYEE_BANKCITY >", value, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityGreaterThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKCITY >=", value, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityLessThan(String value) {
			addCriterion("PAYEE_BANKCITY <", value, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKCITY <=", value, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityLike(String value) {
			addCriterion("PAYEE_BANKCITY like", value, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityNotLike(String value) {
			addCriterion("PAYEE_BANKCITY not like", value, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityIn(List values) {
			addCriterion("PAYEE_BANKCITY in", values, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityNotIn(List values) {
			addCriterion("PAYEE_BANKCITY not in", values, "payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityBetween(String value1, String value2) {
			addCriterion("PAYEE_BANKCITY between", value1, value2,
					"payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityNotBetween(String value1, String value2) {
			addCriterion("PAYEE_BANKCITY not between", value1, value2,
					"payeeBankCity");
			return this;
		}

		public Criteria andPayeeBankCityNameIsNull() {
			addCriterion("PAYEE_BANKCITYNAME is null");
			return this;
		}

		public Criteria andPayeeBankCityNameIsNotNull() {
			addCriterion("PAYEE_BANKCITYNAME is not null");
			return this;
		}

		public Criteria andPayeeBankCityNameEqualTo(String value) {
			addCriterion("PAYEE_BANKCITYNAME =", value, "payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameNotEqualTo(String value) {
			addCriterion("PAYEE_BANKCITYNAME <>", value, "payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameGreaterThan(String value) {
			addCriterion("PAYEE_BANKCITYNAME >", value, "payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameGreaterThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKCITYNAME >=", value, "payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameLessThan(String value) {
			addCriterion("PAYEE_BANKCITYNAME <", value, "payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_BANKCITYNAME <=", value, "payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameLike(String value) {
			addCriterion("PAYEE_BANKCITYNAME like", value, "payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameNotLike(String value) {
			addCriterion("PAYEE_BANKCITYNAME not like", value,
					"payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameIn(List values) {
			addCriterion("PAYEE_BANKCITYNAME in", values, "payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameNotIn(List values) {
			addCriterion("PAYEE_BANKCITYNAME not in", values,
					"payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameBetween(String value1, String value2) {
			addCriterion("PAYEE_BANKCITYNAME between", value1, value2,
					"payeeBankCityName");
			return this;
		}

		public Criteria andPayeeBankCityNameNotBetween(String value1,
				String value2) {
			addCriterion("PAYEE_BANKCITYNAME not between", value1, value2,
					"payeeBankCityName");
			return this;
		}

		public Criteria andPaymentReasonIsNull() {
			addCriterion("PAYMENT_REASON is null");
			return this;
		}

		public Criteria andPaymentReasonIsNotNull() {
			addCriterion("PAYMENT_REASON is not null");
			return this;
		}

		public Criteria andPaymentReasonEqualTo(String value) {
			addCriterion("PAYMENT_REASON =", value, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonNotEqualTo(String value) {
			addCriterion("PAYMENT_REASON <>", value, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonGreaterThan(String value) {
			addCriterion("PAYMENT_REASON >", value, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonGreaterThanOrEqualTo(String value) {
			addCriterion("PAYMENT_REASON >=", value, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonLessThan(String value) {
			addCriterion("PAYMENT_REASON <", value, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonLessThanOrEqualTo(String value) {
			addCriterion("PAYMENT_REASON <=", value, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonLike(String value) {
			addCriterion("PAYMENT_REASON like", value, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonNotLike(String value) {
			addCriterion("PAYMENT_REASON not like", value, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonIn(List values) {
			addCriterion("PAYMENT_REASON in", values, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonNotIn(List values) {
			addCriterion("PAYMENT_REASON not in", values, "paymentReason");
			return this;
		}

		public Criteria andPaymentReasonBetween(String value1, String value2) {
			addCriterion("PAYMENT_REASON between", value1, value2,
					"paymentReason");
			return this;
		}

		public Criteria andPaymentReasonNotBetween(String value1, String value2) {
			addCriterion("PAYMENT_REASON not between", value1, value2,
					"paymentReason");
			return this;
		}

		public Criteria andFailedReasonIsNull() {
			addCriterion("FAILED_REASON is null");
			return this;
		}

		public Criteria andFailedReasonIsNotNull() {
			addCriterion("FAILED_REASON is not null");
			return this;
		}

		public Criteria andFailedReasonEqualTo(String value) {
			addCriterion("FAILED_REASON =", value, "failedReason");
			return this;
		}

		public Criteria andFailedReasonNotEqualTo(String value) {
			addCriterion("FAILED_REASON <>", value, "failedReason");
			return this;
		}

		public Criteria andFailedReasonGreaterThan(String value) {
			addCriterion("FAILED_REASON >", value, "failedReason");
			return this;
		}

		public Criteria andFailedReasonGreaterThanOrEqualTo(String value) {
			addCriterion("FAILED_REASON >=", value, "failedReason");
			return this;
		}

		public Criteria andFailedReasonLessThan(String value) {
			addCriterion("FAILED_REASON <", value, "failedReason");
			return this;
		}

		public Criteria andFailedReasonLessThanOrEqualTo(String value) {
			addCriterion("FAILED_REASON <=", value, "failedReason");
			return this;
		}

		public Criteria andFailedReasonLike(String value) {
			addCriterion("FAILED_REASON like", value, "failedReason");
			return this;
		}

		public Criteria andFailedReasonNotLike(String value) {
			addCriterion("FAILED_REASON not like", value, "failedReason");
			return this;
		}

		public Criteria andFailedReasonIn(List values) {
			addCriterion("FAILED_REASON in", values, "failedReason");
			return this;
		}

		public Criteria andFailedReasonNotIn(List values) {
			addCriterion("FAILED_REASON not in", values, "failedReason");
			return this;
		}

		public Criteria andFailedReasonBetween(String value1, String value2) {
			addCriterion("FAILED_REASON between", value1, value2,
					"failedReason");
			return this;
		}

		public Criteria andFailedReasonNotBetween(String value1, String value2) {
			addCriterion("FAILED_REASON not between", value1, value2,
					"failedReason");
			return this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("CREATE_DATE =", value, "createDate");
			return this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("CREATE_DATE <>", value, "createDate");
			return this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("CREATE_DATE >", value, "createDate");
			return this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE >=", value, "createDate");
			return this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("CREATE_DATE <", value, "createDate");
			return this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE <=", value, "createDate");
			return this;
		}

		public Criteria andCreateDateIn(List values) {
			addCriterion("CREATE_DATE in", values, "createDate");
			return this;
		}

		public Criteria andCreateDateNotIn(List values) {
			addCriterion("CREATE_DATE not in", values, "createDate");
			return this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE between", value1, value2, "createDate");
			return this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE not between", value1, value2,
					"createDate");
			return this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateIn(List values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotIn(List values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE not between", value1, value2,
					"updateDate");
			return this;
		}

		public Criteria andTradeAliasIsNull() {
			addCriterion("TRADE_ALIAS is null");
			return this;
		}

		public Criteria andTradeAliasIsNotNull() {
			addCriterion("TRADE_ALIAS is not null");
			return this;
		}

		public Criteria andTradeAliasEqualTo(String value) {
			addCriterion("TRADE_ALIAS =", value, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasNotEqualTo(String value) {
			addCriterion("TRADE_ALIAS <>", value, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasGreaterThan(String value) {
			addCriterion("TRADE_ALIAS >", value, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasGreaterThanOrEqualTo(String value) {
			addCriterion("TRADE_ALIAS >=", value, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasLessThan(String value) {
			addCriterion("TRADE_ALIAS <", value, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasLessThanOrEqualTo(String value) {
			addCriterion("TRADE_ALIAS <=", value, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasLike(String value) {
			addCriterion("TRADE_ALIAS like", value, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasNotLike(String value) {
			addCriterion("TRADE_ALIAS not like", value, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasIn(List values) {
			addCriterion("TRADE_ALIAS in", values, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasNotIn(List values) {
			addCriterion("TRADE_ALIAS not in", values, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasBetween(String value1, String value2) {
			addCriterion("TRADE_ALIAS between", value1, value2, "tradeAlias");
			return this;
		}

		public Criteria andTradeAliasNotBetween(String value1, String value2) {
			addCriterion("TRADE_ALIAS not between", value1, value2,
					"tradeAlias");
			return this;
		}

		public Criteria andTradeTypeIsNull() {
			addCriterion("TRADE_TYPE is null");
			return this;
		}

		public Criteria andTradeTypeIsNotNull() {
			addCriterion("TRADE_TYPE is not null");
			return this;
		}

		public Criteria andTradeTypeEqualTo(Integer value) {
			addCriterion("TRADE_TYPE =", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeNotEqualTo(Integer value) {
			addCriterion("TRADE_TYPE <>", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeGreaterThan(Integer value) {
			addCriterion("TRADE_TYPE >", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("TRADE_TYPE >=", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeLessThan(Integer value) {
			addCriterion("TRADE_TYPE <", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeLessThanOrEqualTo(Integer value) {
			addCriterion("TRADE_TYPE <=", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeIn(List values) {
			addCriterion("TRADE_TYPE in", values, "tradeType");
			return this;
		}

		public Criteria andTradeTypeNotIn(List values) {
			addCriterion("TRADE_TYPE not in", values, "tradeType");
			return this;
		}

		public Criteria andTradeTypeBetween(Integer value1, Integer value2) {
			addCriterion("TRADE_TYPE between", value1, value2, "tradeType");
			return this;
		}

		public Criteria andTradeTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("TRADE_TYPE not between", value1, value2, "tradeType");
			return this;
		}

		public Criteria andPayeeMobileIsNull() {
			addCriterion("PAYEE_MOBILE is null");
			return this;
		}

		public Criteria andPayeeMobileIsNotNull() {
			addCriterion("PAYEE_MOBILE is not null");
			return this;
		}

		public Criteria andPayeeMobileEqualTo(String value) {
			addCriterion("PAYEE_MOBILE =", value, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileNotEqualTo(String value) {
			addCriterion("PAYEE_MOBILE <>", value, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileGreaterThan(String value) {
			addCriterion("PAYEE_MOBILE >", value, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileGreaterThanOrEqualTo(String value) {
			addCriterion("PAYEE_MOBILE >=", value, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileLessThan(String value) {
			addCriterion("PAYEE_MOBILE <", value, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileLessThanOrEqualTo(String value) {
			addCriterion("PAYEE_MOBILE <=", value, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileLike(String value) {
			addCriterion("PAYEE_MOBILE like", value, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileNotLike(String value) {
			addCriterion("PAYEE_MOBILE not like", value, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileIn(List values) {
			addCriterion("PAYEE_MOBILE in", values, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileNotIn(List values) {
			addCriterion("PAYEE_MOBILE not in", values, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileBetween(String value1, String value2) {
			addCriterion("PAYEE_MOBILE between", value1, value2, "payeeMobile");
			return this;
		}

		public Criteria andPayeeMobileNotBetween(String value1, String value2) {
			addCriterion("PAYEE_MOBILE not between", value1, value2,
					"payeeMobile");
			return this;
		}

		public Criteria andBankOrderIdIsNull() {
			addCriterion("BANK_ORDERID is null");
			return this;
		}

		public Criteria andBankOrderIdIsNotNull() {
			addCriterion("BANK_ORDERID is not null");
			return this;
		}

		public Criteria andBankOrderIdEqualTo(String value) {
			addCriterion("BANK_ORDERID =", value, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdNotEqualTo(String value) {
			addCriterion("BANK_ORDERID <>", value, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdGreaterThan(String value) {
			addCriterion("BANK_ORDERID >", value, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("BANK_ORDERID >=", value, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdLessThan(String value) {
			addCriterion("BANK_ORDERID <", value, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdLessThanOrEqualTo(String value) {
			addCriterion("BANK_ORDERID <=", value, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdLike(String value) {
			addCriterion("BANK_ORDERID like", value, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdNotLike(String value) {
			addCriterion("BANK_ORDERID not like", value, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdIn(List values) {
			addCriterion("BANK_ORDERID in", values, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdNotIn(List values) {
			addCriterion("BANK_ORDERID not in", values, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdBetween(String value1, String value2) {
			addCriterion("BANK_ORDERID between", value1, value2, "bankOrderId");
			return this;
		}

		public Criteria andBankOrderIdNotBetween(String value1, String value2) {
			addCriterion("BANK_ORDERID not between", value1, value2,
					"bankOrderId");
			return this;
		}

		public Criteria andForeignOrderIdIsNull() {
			addCriterion("FOREIGN_ORDERID is null");
			return this;
		}

		public Criteria andForeignOrderIdIsNotNull() {
			addCriterion("FOREIGN_ORDERID is not null");
			return this;
		}

		public Criteria andForeignOrderIdEqualTo(String value) {
			addCriterion("FOREIGN_ORDERID =", value, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdNotEqualTo(String value) {
			addCriterion("FOREIGN_ORDERID <>", value, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdGreaterThan(String value) {
			addCriterion("FOREIGN_ORDERID >", value, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("FOREIGN_ORDERID >=", value, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdLessThan(String value) {
			addCriterion("FOREIGN_ORDERID <", value, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdLessThanOrEqualTo(String value) {
			addCriterion("FOREIGN_ORDERID <=", value, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdLike(String value) {
			addCriterion("FOREIGN_ORDERID like", value, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdNotLike(String value) {
			addCriterion("FOREIGN_ORDERID not like", value, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdIn(List values) {
			addCriterion("FOREIGN_ORDERID in", values, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdNotIn(List values) {
			addCriterion("FOREIGN_ORDERID not in", values, "foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdBetween(String value1, String value2) {
			addCriterion("FOREIGN_ORDERID between", value1, value2,
					"foreignOrderId");
			return this;
		}

		public Criteria andForeignOrderIdNotBetween(String value1, String value2) {
			addCriterion("FOREIGN_ORDERID not between", value1, value2,
					"foreignOrderId");
			return this;
		}

		public Criteria andFundoutBankCodeIsNull() {
			addCriterion("FUNDOUT_BANKCODE is null");
			return this;
		}

		public Criteria andFundoutBankCodeIsNotNull() {
			addCriterion("FUNDOUT_BANKCODE is not null");
			return this;
		}

		public Criteria andFundoutBankCodeEqualTo(Long value) {
			addCriterion("FUNDOUT_BANKCODE =", value, "fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeNotEqualTo(Long value) {
			addCriterion("FUNDOUT_BANKCODE <>", value, "fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeGreaterThan(Long value) {
			addCriterion("FUNDOUT_BANKCODE >", value, "fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeGreaterThanOrEqualTo(Long value) {
			addCriterion("FUNDOUT_BANKCODE >=", value, "fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeLessThan(Long value) {
			addCriterion("FUNDOUT_BANKCODE <", value, "fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeLessThanOrEqualTo(Long value) {
			addCriterion("FUNDOUT_BANKCODE <=", value, "fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeIn(List values) {
			addCriterion("FUNDOUT_BANKCODE in", values, "fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeNotIn(List values) {
			addCriterion("FUNDOUT_BANKCODE not in", values, "fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeBetween(Long value1, Long value2) {
			addCriterion("FUNDOUT_BANKCODE between", value1, value2,
					"fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankCodeNotBetween(Long value1, Long value2) {
			addCriterion("FUNDOUT_BANKCODE not between", value1, value2,
					"fundoutBankCode");
			return this;
		}

		public Criteria andFundoutBankNameIsNull() {
			addCriterion("FUNDOUT_BANKNAME is null");
			return this;
		}

		public Criteria andFundoutBankNameIsNotNull() {
			addCriterion("FUNDOUT_BANKNAME is not null");
			return this;
		}

		public Criteria andFundoutBankNameEqualTo(String value) {
			addCriterion("FUNDOUT_BANKNAME =", value, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameNotEqualTo(String value) {
			addCriterion("FUNDOUT_BANKNAME <>", value, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameGreaterThan(String value) {
			addCriterion("FUNDOUT_BANKNAME >", value, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("FUNDOUT_BANKNAME >=", value, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameLessThan(String value) {
			addCriterion("FUNDOUT_BANKNAME <", value, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameLessThanOrEqualTo(String value) {
			addCriterion("FUNDOUT_BANKNAME <=", value, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameLike(String value) {
			addCriterion("FUNDOUT_BANKNAME like", value, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameNotLike(String value) {
			addCriterion("FUNDOUT_BANKNAME not like", value, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameIn(List values) {
			addCriterion("FUNDOUT_BANKNAME in", values, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameNotIn(List values) {
			addCriterion("FUNDOUT_BANKNAME not in", values, "fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameBetween(String value1, String value2) {
			addCriterion("FUNDOUT_BANKNAME between", value1, value2,
					"fundoutBankName");
			return this;
		}

		public Criteria andFundoutBankNameNotBetween(String value1,
				String value2) {
			addCriterion("FUNDOUT_BANKNAME not between", value1, value2,
					"fundoutBankName");
			return this;
		}

		public Criteria andFundoutModeIsNull() {
			addCriterion("FUNDOUT_MODE is null");
			return this;
		}

		public Criteria andFundoutModeIsNotNull() {
			addCriterion("FUNDOUT_MODE is not null");
			return this;
		}

		public Criteria andFundoutModeEqualTo(Integer value) {
			addCriterion("FUNDOUT_MODE =", value, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeNotEqualTo(Integer value) {
			addCriterion("FUNDOUT_MODE <>", value, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeGreaterThan(Integer value) {
			addCriterion("FUNDOUT_MODE >", value, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeGreaterThanOrEqualTo(Integer value) {
			addCriterion("FUNDOUT_MODE >=", value, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeLessThan(Integer value) {
			addCriterion("FUNDOUT_MODE <", value, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeLessThanOrEqualTo(Integer value) {
			addCriterion("FUNDOUT_MODE <=", value, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeIn(List values) {
			addCriterion("FUNDOUT_MODE in", values, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeNotIn(List values) {
			addCriterion("FUNDOUT_MODE not in", values, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeBetween(Integer value1, Integer value2) {
			addCriterion("FUNDOUT_MODE between", value1, value2, "fundoutMode");
			return this;
		}

		public Criteria andFundoutModeNotBetween(Integer value1, Integer value2) {
			addCriterion("FUNDOUT_MODE not between", value1, value2,
					"fundoutMode");
			return this;
		}

		public Criteria andPriorityIsNull() {
			addCriterion("PRIORITY is null");
			return this;
		}

		public Criteria andPriorityIsNotNull() {
			addCriterion("PRIORITY is not null");
			return this;
		}

		public Criteria andPriorityEqualTo(Integer value) {
			addCriterion("PRIORITY =", value, "priority");
			return this;
		}

		public Criteria andPriorityNotEqualTo(Integer value) {
			addCriterion("PRIORITY <>", value, "priority");
			return this;
		}

		public Criteria andPriorityGreaterThan(Integer value) {
			addCriterion("PRIORITY >", value, "priority");
			return this;
		}

		public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
			addCriterion("PRIORITY >=", value, "priority");
			return this;
		}

		public Criteria andPriorityLessThan(Integer value) {
			addCriterion("PRIORITY <", value, "priority");
			return this;
		}

		public Criteria andPriorityLessThanOrEqualTo(Integer value) {
			addCriterion("PRIORITY <=", value, "priority");
			return this;
		}

		public Criteria andPriorityIn(List values) {
			addCriterion("PRIORITY in", values, "priority");
			return this;
		}

		public Criteria andPriorityNotIn(List values) {
			addCriterion("PRIORITY not in", values, "priority");
			return this;
		}

		public Criteria andPriorityBetween(Integer value1, Integer value2) {
			addCriterion("PRIORITY between", value1, value2, "priority");
			return this;
		}

		public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
			addCriterion("PRIORITY not between", value1, value2, "priority");
			return this;
		}

		public Criteria andParentOrderIdIsNull() {
			addCriterion("PARENT_ORDERID is null");
			return this;
		}

		public Criteria andParentOrderIdIsNotNull() {
			addCriterion("PARENT_ORDERID is not null");
			return this;
		}

		public Criteria andParentOrderIdEqualTo(Long value) {
			addCriterion("PARENT_ORDERID =", value, "parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdNotEqualTo(Long value) {
			addCriterion("PARENT_ORDERID <>", value, "parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdGreaterThan(Long value) {
			addCriterion("PARENT_ORDERID >", value, "parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("PARENT_ORDERID >=", value, "parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdLessThan(Long value) {
			addCriterion("PARENT_ORDERID <", value, "parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdLessThanOrEqualTo(Long value) {
			addCriterion("PARENT_ORDERID <=", value, "parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdIn(List values) {
			addCriterion("PARENT_ORDERID in", values, "parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdNotIn(List values) {
			addCriterion("PARENT_ORDERID not in", values, "parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdBetween(Long value1,
				Long value2) {
			addCriterion("PARENT_ORDERID between", value1, value2,
					"parentOrderId");
			return this;
		}

		public Criteria andParentOrderIdNotBetween(Long value1,
				Long value2) {
			addCriterion("PARENT_ORDERID not between", value1, value2,
					"parentOrderId");
			return this;
		}
	}
}