package com.pay.fo.order.model.base;

import java.util.Date;

public class PayToAcctOrder {
	
	/**
	 * 收款方手续费
	 */
	private Long payeeFee;

	/**
	 * 付款方手续费
	 */
	private Long payerFee;
	
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.ORDER_ID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Long orderId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.ORDER_TYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Integer orderType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.ORDER_SMALLTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String orderSmallType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.ORDER_STATUS
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Integer orderStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.ORDER_AMOUNT
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Long orderAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYER_NAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String payerName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYER_LOGINNAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String payerLoginName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYER_MEMBERCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Long payerMemberCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYER_MEMBERTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Integer payerMemberType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYER_ACCTCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String payerAcctCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYER_ACCTTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Integer payerAcctType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYEE_NAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String payeeName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYEE_LOGINNAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String payeeLoginName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYEE_MEMBERCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Long payeeMemberCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYEE_MEMBERTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Integer payeeMemberType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYEE_ACCTCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String payeeAcctCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYEE_ACCTTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Integer payeeAcctType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PAYMENT_REASON
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String paymentReason;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.FAILED_REASON
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String failedReason;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.CREATE_DATE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.UPDATE_DATE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Date updateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.TRADE_ALIAS
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String tradeAlias;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.TRADE_TYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Integer tradeType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.FOREIGN_ORDERID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private String foreignOrderId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FO.PAY_TOACCTORDER.PARENT_ORDERID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private Long parentOrderId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.ORDER_ID
     *
     * @return the value of FO.PAY_TOACCTORDER.ORDER_ID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.ORDER_ID
     *
     * @param orderId the value for FO.PAY_TOACCTORDER.ORDER_ID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.ORDER_TYPE
     *
     * @return the value of FO.PAY_TOACCTORDER.ORDER_TYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.ORDER_TYPE
     *
     * @param orderType the value for FO.PAY_TOACCTORDER.ORDER_TYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.ORDER_SMALLTYPE
     *
     * @return the value of FO.PAY_TOACCTORDER.ORDER_SMALLTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getOrderSmallType() {
        return orderSmallType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.ORDER_SMALLTYPE
     *
     * @param orderSmallType the value for FO.PAY_TOACCTORDER.ORDER_SMALLTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setOrderSmallType(String orderSmallType) {
        this.orderSmallType = orderSmallType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.ORDER_STATUS
     *
     * @return the value of FO.PAY_TOACCTORDER.ORDER_STATUS
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.ORDER_STATUS
     *
     * @param orderStatus the value for FO.PAY_TOACCTORDER.ORDER_STATUS
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.ORDER_AMOUNT
     *
     * @return the value of FO.PAY_TOACCTORDER.ORDER_AMOUNT
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Long getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.ORDER_AMOUNT
     *
     * @param orderAmount the value for FO.PAY_TOACCTORDER.ORDER_AMOUNT
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYER_NAME
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYER_NAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYER_NAME
     *
     * @param payerName the value for FO.PAY_TOACCTORDER.PAYER_NAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYER_LOGINNAME
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYER_LOGINNAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getPayerLoginName() {
        return payerLoginName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYER_LOGINNAME
     *
     * @param payerLoginName the value for FO.PAY_TOACCTORDER.PAYER_LOGINNAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayerLoginName(String payerLoginName) {
        this.payerLoginName = payerLoginName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYER_MEMBERCODE
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYER_MEMBERCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Long getPayerMemberCode() {
        return payerMemberCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYER_MEMBERCODE
     *
     * @param payerMemberCode the value for FO.PAY_TOACCTORDER.PAYER_MEMBERCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayerMemberCode(Long payerMemberCode) {
        this.payerMemberCode = payerMemberCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYER_MEMBERTYPE
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYER_MEMBERTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Integer getPayerMemberType() {
        return payerMemberType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYER_MEMBERTYPE
     *
     * @param payerMemberType the value for FO.PAY_TOACCTORDER.PAYER_MEMBERTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayerMemberType(Integer payerMemberType) {
        this.payerMemberType = payerMemberType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYER_ACCTCODE
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYER_ACCTCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getPayerAcctCode() {
        return payerAcctCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYER_ACCTCODE
     *
     * @param payerAcctCode the value for FO.PAY_TOACCTORDER.PAYER_ACCTCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayerAcctCode(String payerAcctCode) {
        this.payerAcctCode = payerAcctCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYER_ACCTTYPE
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYER_ACCTTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Integer getPayerAcctType() {
        return payerAcctType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYER_ACCTTYPE
     *
     * @param payerAcctType the value for FO.PAY_TOACCTORDER.PAYER_ACCTTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayerAcctType(Integer payerAcctType) {
        this.payerAcctType = payerAcctType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYEE_NAME
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYEE_NAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYEE_NAME
     *
     * @param payeeName the value for FO.PAY_TOACCTORDER.PAYEE_NAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYEE_LOGINNAME
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYEE_LOGINNAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getPayeeLoginName() {
        return payeeLoginName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYEE_LOGINNAME
     *
     * @param payeeLoginName the value for FO.PAY_TOACCTORDER.PAYEE_LOGINNAME
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayeeLoginName(String payeeLoginName) {
        this.payeeLoginName = payeeLoginName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYEE_MEMBERCODE
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYEE_MEMBERCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Long getPayeeMemberCode() {
        return payeeMemberCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYEE_MEMBERCODE
     *
     * @param payeeMemberCode the value for FO.PAY_TOACCTORDER.PAYEE_MEMBERCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayeeMemberCode(Long payeeMemberCode) {
        this.payeeMemberCode = payeeMemberCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYEE_MEMBERTYPE
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYEE_MEMBERTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Integer getPayeeMemberType() {
        return payeeMemberType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYEE_MEMBERTYPE
     *
     * @param payeeMemberType the value for FO.PAY_TOACCTORDER.PAYEE_MEMBERTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayeeMemberType(Integer payeeMemberType) {
        this.payeeMemberType = payeeMemberType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYEE_ACCTCODE
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYEE_ACCTCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getPayeeAcctCode() {
        return payeeAcctCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYEE_ACCTCODE
     *
     * @param payeeAcctCode the value for FO.PAY_TOACCTORDER.PAYEE_ACCTCODE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayeeAcctCode(String payeeAcctCode) {
        this.payeeAcctCode = payeeAcctCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYEE_ACCTTYPE
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYEE_ACCTTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Integer getPayeeAcctType() {
        return payeeAcctType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYEE_ACCTTYPE
     *
     * @param payeeAcctType the value for FO.PAY_TOACCTORDER.PAYEE_ACCTTYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPayeeAcctType(Integer payeeAcctType) {
        this.payeeAcctType = payeeAcctType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PAYMENT_REASON
     *
     * @return the value of FO.PAY_TOACCTORDER.PAYMENT_REASON
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getPaymentReason() {
        return paymentReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PAYMENT_REASON
     *
     * @param paymentReason the value for FO.PAY_TOACCTORDER.PAYMENT_REASON
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setPaymentReason(String paymentReason) {
        this.paymentReason = paymentReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.FAILED_REASON
     *
     * @return the value of FO.PAY_TOACCTORDER.FAILED_REASON
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getFailedReason() {
        return failedReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.FAILED_REASON
     *
     * @param failedReason the value for FO.PAY_TOACCTORDER.FAILED_REASON
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setFailedReason(String failedReason) {
        this.failedReason = failedReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.CREATE_DATE
     *
     * @return the value of FO.PAY_TOACCTORDER.CREATE_DATE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.CREATE_DATE
     *
     * @param createDate the value for FO.PAY_TOACCTORDER.CREATE_DATE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.UPDATE_DATE
     *
     * @return the value of FO.PAY_TOACCTORDER.UPDATE_DATE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.UPDATE_DATE
     *
     * @param updateDate the value for FO.PAY_TOACCTORDER.UPDATE_DATE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.TRADE_ALIAS
     *
     * @return the value of FO.PAY_TOACCTORDER.TRADE_ALIAS
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getTradeAlias() {
        return tradeAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.TRADE_ALIAS
     *
     * @param tradeAlias the value for FO.PAY_TOACCTORDER.TRADE_ALIAS
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setTradeAlias(String tradeAlias) {
        this.tradeAlias = tradeAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.TRADE_TYPE
     *
     * @return the value of FO.PAY_TOACCTORDER.TRADE_TYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Integer getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.TRADE_TYPE
     *
     * @param tradeType the value for FO.PAY_TOACCTORDER.TRADE_TYPE
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setTradeType(Integer tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.FOREIGN_ORDERID
     *
     * @return the value of FO.PAY_TOACCTORDER.FOREIGN_ORDERID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public String getForeignOrderId() {
        return foreignOrderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.FOREIGN_ORDERID
     *
     * @param foreignOrderId the value for FO.PAY_TOACCTORDER.FOREIGN_ORDERID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setForeignOrderId(String foreignOrderId) {
        this.foreignOrderId = foreignOrderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FO.PAY_TOACCTORDER.PARENT_ORDERID
     *
     * @return the value of FO.PAY_TOACCTORDER.PARENT_ORDERID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Long getParentOrderId() {
        return parentOrderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FO.PAY_TOACCTORDER.PARENT_ORDERID
     *
     * @param parentOrderId the value for FO.PAY_TOACCTORDER.PARENT_ORDERID
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public void setParentOrderId(Long parentOrderId) {
        this.parentOrderId = parentOrderId;
    }

	public Long getPayeeFee() {
		return payeeFee;
	}

	public void setPayeeFee(Long payeeFee) {
		this.payeeFee = payeeFee;
	}

	public Long getPayerFee() {
		return payerFee;
	}

	public void setPayerFee(Long payerFee) {
		this.payerFee = payerFee;
	}
    
    
}