package com.pay.acc.member.dao.model;

import java.util.Date;

/**
 * ### Generated by Oracle TopLink Workbench 10.1.3.0.0 - Wed Dec 13 12:03:29
 * CST 2006. ###
 */

public class MemberIdentity {

	private Long memberCode;
	private Date createDate;
	private String idContent;
	private Integer idType;
	private Integer isPrimaryId;
	private Integer status;
	private Date validationDate;
	private Date updateDate;

	public Integer getIsPrimaryId() {
		return this.isPrimaryId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setIsPrimaryId(Integer isPrimaryId) {
		this.isPrimaryId = isPrimaryId;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getValidationDate() {
		return validationDate;
	}

	public void setValidationDate(Date validationDate) {
		this.validationDate = validationDate;
	}

	public Long getMemberCode() {
		return memberCode;
	}

	public void setMemberCode(Long memberCode) {
		this.memberCode = memberCode;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getIdContent() {
		return idContent;
	}

	public void setIdContent(String idContent) {
		this.idContent = idContent;
	}

	public Integer getIdType() {
		return idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
