/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao.impl;

import com.pay.inf.dao.impl.BaseDAOImpl;
import com.pay.txncore.dao.PartnerConfigDAO;
import com.pay.txncore.model.PartnerConfig;

public class PartnerConfigDAOImpl extends BaseDAOImpl<PartnerConfig> implements
		PartnerConfigDAO {

	@Override
	public void delete(Long id) {
		getSqlMapClientTemplate().delete("fipartnerconfig.deleteByPrimaryKey",
				id);
	}

	@Override
	public PartnerConfig findConfig(Long partnerID, String paramCode) {

		PartnerConfig partnerConfig = new PartnerConfig();
		partnerConfig.setMemberCode(partnerID);
		partnerConfig.setParamCode(paramCode);

		partnerConfig = (PartnerConfig) getSqlMapClientTemplate()
				.queryForObject("fipartnerconfig.findBySelective",
						partnerConfig);

		if ((null != partnerConfig)) {
			return partnerConfig;
		}
		return null;
		// throw new BusinessException();
		// ("商场配置参数根据memberCode和pramaCode查询出错。 memberCode=" +memberCode
		// +",paramCode="+paramCode)
	}
}