/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.channel.model;

/**
 * ORG_RESPONSE_HISTORY
 */

public class ChannelResponse implements java.io.Serializable {

	private String result;
	private Long id;
	private String channelCode;
	private String submitChannelId;
	private Long protocolNo;
	private String responseContext;
	private String returnChannelId;
	private String resultInfo;
	private java.util.Date createDate;

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getChannelCode() {
		return channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	public String getSubmitChannelId() {
		return submitChannelId;
	}

	public void setSubmitChannelId(String submitChannelId) {
		this.submitChannelId = submitChannelId;
	}

	public String getResponseContext() {
		return responseContext;
	}

	public void setResponseContext(String responseContext) {
		this.responseContext = responseContext;
	}

	public String getReturnChannelId() {
		return returnChannelId;
	}

	public void setReturnChannelId(String returnChannelId) {
		this.returnChannelId = returnChannelId;
	}

	public String getResultInfo() {
		return resultInfo;
	}

	public void setResultInfo(String resultInfo) {
		this.resultInfo = resultInfo;
	}

	public java.util.Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getProtocolNo() {
		return protocolNo;
	}

	public void setProtocolNo(Long protocolNo) {
		this.protocolNo = protocolNo;
	}

}