/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.channel.model;

/**
 * ORG_REQUEST_HISTORY
 */

public class ChannelRequest implements java.io.Serializable {

	private String channelCode;
	private Long protocolType;
	private Long submitChannelId;
	private Long id;
	private String responseContext;
	private Long protocolNo;
	private java.util.Date createDate;

	public String getChannelCode() {
		return channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	public Long getProtocolType() {
		return protocolType;
	}

	public void setProtocolType(Long protocolType) {
		this.protocolType = protocolType;
	}

	public Long getSubmitChannelId() {
		return submitChannelId;
	}

	public void setSubmitChannelId(Long submitChannelId) {
		this.submitChannelId = submitChannelId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getResponseContext() {
		return responseContext;
	}

	public void setResponseContext(String responseContext) {
		this.responseContext = responseContext;
	}

	public Long getProtocolNo() {
		return protocolNo;
	}

	public void setProtocolNo(Long protocolNo) {
		this.protocolNo = protocolNo;
	}

	public java.util.Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

}