/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.quartzruninfo;

import com.pay.fundout.withdraw.model.quartzruninfo.QuartzRunInfo;
import com.pay.inf.dao.BaseDAO;

public interface QuartzRunInfoDAO extends BaseDAO<QuartzRunInfo> {
}