/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.withdrawrule;

import com.pay.fundout.withdraw.model.rule.WithdrawRule;
import com.pay.inf.dao.BaseDAO;

@SuppressWarnings("hiding")
public interface WithdrawRuleDAO extends BaseDAO {
	public WithdrawRule getRule(int destBankId, long amount, int mtype,
			int bankAccoutType);
}