package com.pay.fo.order.dao.base;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pay.fo.order.model.base.FundoutRefundOrder;
import com.pay.fo.order.model.base.FundoutRefundOrderExample;

public class FundoutRefundOrderDAOImpl extends SqlMapClientDaoSupport implements FundoutRefundOrderDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public FundoutRefundOrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public Long insert(FundoutRefundOrder record) {
      Object newKey =  getSqlMapClientTemplate().insert("FO_FUNDOUT_REFUNDORDER.abatorgenerated_insert", record);
      return (Long)newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public int updateByPrimaryKey(FundoutRefundOrder record) {
        int rows = getSqlMapClientTemplate().update("FO_FUNDOUT_REFUNDORDER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public int updateByPrimaryKeySelective(FundoutRefundOrder record) {
        int rows = getSqlMapClientTemplate().update("FO_FUNDOUT_REFUNDORDER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public List selectByExample(FundoutRefundOrderExample example) {
        List list = getSqlMapClientTemplate().queryForList("FO_FUNDOUT_REFUNDORDER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public FundoutRefundOrder selectByPrimaryKey(Long orderId) {
        FundoutRefundOrder key = new FundoutRefundOrder();
        key.setOrderId(orderId);
        FundoutRefundOrder record = (FundoutRefundOrder) getSqlMapClientTemplate().queryForObject("FO_FUNDOUT_REFUNDORDER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public int deleteByExample(FundoutRefundOrderExample example) {
        int rows = getSqlMapClientTemplate().delete("FO_FUNDOUT_REFUNDORDER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public int deleteByPrimaryKey(Long orderId) {
        FundoutRefundOrder key = new FundoutRefundOrder();
        key.setOrderId(orderId);
        int rows = getSqlMapClientTemplate().delete("FO_FUNDOUT_REFUNDORDER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public int countByExample(FundoutRefundOrderExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("FO_FUNDOUT_REFUNDORDER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public int updateByExampleSelective(FundoutRefundOrder record, FundoutRefundOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("FO_FUNDOUT_REFUNDORDER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    public int updateByExample(FundoutRefundOrder record, FundoutRefundOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("FO_FUNDOUT_REFUNDORDER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table FO.FUNDOUT_REFUNDORDER
     *
     * @abatorgenerated Mon Jul 25 14:49:57 CST 2011
     */
    private static class UpdateByExampleParms extends FundoutRefundOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, FundoutRefundOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}