package com.pay.fo.order.dao.base;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pay.fo.order.model.base.PayToAcctOrder;
import com.pay.fo.order.model.base.PayToAcctOrder;
import com.pay.fo.order.model.base.PayToAcctOrderExample;

public class PayToAcctOrderDAOImpl extends SqlMapClientDaoSupport implements PayToAcctOrderDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public PayToAcctOrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public Long insert(PayToAcctOrder record) {
      Object newKey =  getSqlMapClientTemplate().insert("FO_PAY_TOACCTORDER.abatorgenerated_insert", record);
      return (Long)newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public int updateByPrimaryKey(PayToAcctOrder record) {
        int rows = getSqlMapClientTemplate().update("FO_PAY_TOACCTORDER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public int updateByPrimaryKeySelective(PayToAcctOrder record) {
        int rows = getSqlMapClientTemplate().update("FO_PAY_TOACCTORDER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public List selectByExample(PayToAcctOrderExample example) {
        List list = getSqlMapClientTemplate().queryForList("FO_PAY_TOACCTORDER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public PayToAcctOrder selectByPrimaryKey(Long orderId) {
        PayToAcctOrder key = new PayToAcctOrder();
        key.setOrderId(orderId);
        PayToAcctOrder record = (PayToAcctOrder) getSqlMapClientTemplate().queryForObject("FO_PAY_TOACCTORDER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public int deleteByExample(PayToAcctOrderExample example) {
        int rows = getSqlMapClientTemplate().delete("FO_PAY_TOACCTORDER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public int deleteByPrimaryKey(Long orderId) {
        PayToAcctOrder key = new PayToAcctOrder();
        key.setOrderId(orderId);
        int rows = getSqlMapClientTemplate().delete("FO_PAY_TOACCTORDER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public int countByExample(PayToAcctOrderExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("FO_PAY_TOACCTORDER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public int updateByExampleSelective(PayToAcctOrder record, PayToAcctOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("FO_PAY_TOACCTORDER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    public int updateByExample(PayToAcctOrder record, PayToAcctOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("FO_PAY_TOACCTORDER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table FO.PAY_TOACCTORDER
     *
     * @abatorgenerated Mon Jun 13 17:56:39 CST 2011
     */
    private static class UpdateByExampleParms extends PayToAcctOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, PayToAcctOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    @Override
	public Long sumCurrentDayPaymentAmount(PayToAcctOrder record) {
		Object obj = getSqlMapClientTemplate()
		.queryForObject(
				"FO_PAY_TOACCTORDER.SumCurrentDayPaymentAmount",
				record);
		return (Long)obj;
	}

	@Override
	public Long sumCurrentMonthPaymentAmount(PayToAcctOrder record) {
		Object obj = getSqlMapClientTemplate()
		.queryForObject(
				"FO_PAY_TOACCTORDER.SumCurrentMonthPaymentAmount",
				record);
		return (Long)obj;
	}

	@Override
	public Integer countCurrentDayPaymentTimes(PayToAcctOrder record) {
		Object obj = getSqlMapClientTemplate()
		.queryForObject(
				"FO_PAY_TOACCTORDER.CountCurrentDayPaymentTimes",
				record);
		return (Integer)obj;
	}

	@Override
	public Integer countCurrentMonthPaymentTimes(PayToAcctOrder record) {
		Object obj = getSqlMapClientTemplate()
		.queryForObject(
				"FO_PAY_TOACCTORDER.CountCurrentMonthPaymentTimes",
				record);
		return (Integer)obj;
	}
}