/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.channel.dao.impl;

import com.pay.channel.dao.ChannelResponseDAO;
import com.pay.channel.model.ChannelResponse;
import com.pay.inf.dao.impl.BaseDAOImpl;

public class ChannelResponseDAOImpl extends BaseDAOImpl<ChannelResponse>
		implements ChannelResponseDAO {

}