/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.txncore.model;
/**
* BATCH_REFUND_DETAIL
*/

public class BatchRefundDetail  implements java.io.Serializable {

    private Integer status;
    private String reason;
    private Long refundDetailNo;
    private String partnerId;
    private String errorMsg;
    private Integer refundType;
    private Long refundOrderNo;
    private Long orderAmount;
    private String resultCode;
    private Integer refundDest;
    private Long batchRefundNo;
    private Long applyAmount;
    private String orderId;
    private Long itemNo;

    
    
    public Long getItemNo() {
		return itemNo;
	}

	public void setItemNo(Long itemNo) {
		this.itemNo = itemNo;
	}

	public Integer getStatus (){
        return status;
    }
    
    public void setStatus (Integer status){
        this.status = status;
    }
    public String getReason (){
        return reason;
    }
    
    public void setReason (String reason){
        this.reason = reason;
    }
    public Long getRefundDetailNo (){
        return refundDetailNo;
    }
    
    public void setRefundDetailNo (Long refundDetailNo){
        this.refundDetailNo = refundDetailNo;
    }
    public String getPartnerId (){
        return partnerId;
    }
    
    public void setPartnerId (String partnerId){
        this.partnerId = partnerId;
    }
    public String getErrorMsg (){
        return errorMsg;
    }
    
    public void setErrorMsg (String errorMsg){
        this.errorMsg = errorMsg;
    }
    public Integer getRefundType (){
        return refundType;
    }
    
    public void setRefundType (Integer refundType){
        this.refundType = refundType;
    }
    public Long getRefundOrderNo (){
        return refundOrderNo;
    }
    
    public void setRefundOrderNo (Long refundOrderNo){
        this.refundOrderNo = refundOrderNo;
    }
    public Long getOrderAmount (){
        return orderAmount;
    }
    
    public void setOrderAmount (Long orderAmount){
        this.orderAmount = orderAmount;
    }
    public String getResultCode (){
        return resultCode;
    }
    
    public void setResultCode (String resultCode){
        this.resultCode = resultCode;
    }
    public Integer getRefundDest (){
        return refundDest;
    }
    
    public void setRefundDest (Integer refundDest){
        this.refundDest = refundDest;
    }
    public Long getBatchRefundNo (){
        return batchRefundNo;
    }
    
    public void setBatchRefundNo (Long batchRefundNo){
        this.batchRefundNo = batchRefundNo;
    }
    public Long getApplyAmount (){
        return applyAmount;
    }
    
    public void setApplyAmount (Long applyAmount){
        this.applyAmount = applyAmount;
    }
    public String getOrderId (){
        return orderId;
    }
    
    public void setOrderId (String orderId){
        this.orderId = orderId;
    }

}