/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.txncore.model;
/**
* DEPOSIT_BACK_PROTOCOL
*/

public class DepositBackProtocol  implements java.io.Serializable {

    private Long depositBackNo;
    private String status;
    private Long depositProtocolNo;
    private java.util.Date createDate;
    private Long depositBackProtocolNo;
    private java.util.Date updateDate;
    private Long depositBackAmount;
    
    public Long getDepositBackAmount() {
		return depositBackAmount;
	}

	public void setDepositBackAmount(Long depositBackAmount) {
		this.depositBackAmount = depositBackAmount;
	}

	public Long getDepositBackNo (){
        return depositBackNo;
    }
    
    public void setDepositBackNo (Long depositBackNo){
        this.depositBackNo = depositBackNo;
    }
    public String getStatus (){
        return status;
    }
    
    public void setStatus (String status){
        this.status = status;
    }
    public Long getDepositProtocolNo (){
        return depositProtocolNo;
    }
    
    public void setDepositProtocolNo (Long depositProtocolNo){
        this.depositProtocolNo = depositProtocolNo;
    }
    public java.util.Date getCreateDate (){
        return createDate;
    }
    
    public void setCreateDate (java.util.Date createDate){
        this.createDate = createDate;
    }
    public Long getDepositBackProtocolNo (){
        return depositBackProtocolNo;
    }
    
    public void setDepositBackProtocolNo (Long depositBackProtocolNo){
        this.depositBackProtocolNo = depositBackProtocolNo;
    }
    public java.util.Date getUpdateDate (){
        return updateDate;
    }
    
    public void setUpdateDate (java.util.Date updateDate){
        this.updateDate = updateDate;
    }

}