/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.txncore.model;
/**
* DOUBT_ORDER
*/

public class DoubtOrder  implements java.io.Serializable {

    private Long tradeOrderNo;
    private String status;
    private String remark;
    private Long doubtOrderNo;
    private String partnerId;
    private String requestUrl;
    private String payeeName;
    private String payerIp;
    private String payer;
    private Long orderAmount;
    private String requestIp;
    private String partnerUrl;
    private java.util.Date createDate;
    private String orderId;

    public Long getTradeOrderNo (){
        return tradeOrderNo;
    }
    
    public void setTradeOrderNo (Long tradeOrderNo){
        this.tradeOrderNo = tradeOrderNo;
    }
    public String getStatus (){
        return status;
    }
    
    public void setStatus (String status){
        this.status = status;
    }
    public String getRemark (){
        return remark;
    }
    
    public void setRemark (String remark){
        this.remark = remark;
    }
    public Long getDoubtOrderNo (){
        return doubtOrderNo;
    }
    
    public void setDoubtOrderNo (Long doubtOrderNo){
        this.doubtOrderNo = doubtOrderNo;
    }
    public String getPartnerId (){
        return partnerId;
    }
    
    public void setPartnerId (String partnerId){
        this.partnerId = partnerId;
    }
    public String getRequestUrl (){
        return requestUrl;
    }
    
    public void setRequestUrl (String requestUrl){
        this.requestUrl = requestUrl;
    }
    public String getPayeeName (){
        return payeeName;
    }
    
    public void setPayeeName (String payeeName){
        this.payeeName = payeeName;
    }
    public String getPayerIp (){
        return payerIp;
    }
    
    public void setPayerIp (String payerIp){
        this.payerIp = payerIp;
    }
    public String getPayer (){
        return payer;
    }
    
    public void setPayer (String payer){
        this.payer = payer;
    }
    public Long getOrderAmount (){
        return orderAmount;
    }
    
    public void setOrderAmount (Long orderAmount){
        this.orderAmount = orderAmount;
    }
    public String getRequestIp (){
        return requestIp;
    }
    
    public void setRequestIp (String requestIp){
        this.requestIp = requestIp;
    }
    public String getPartnerUrl (){
        return partnerUrl;
    }
    
    public void setPartnerUrl (String partnerUrl){
        this.partnerUrl = partnerUrl;
    }
    public java.util.Date getCreateDate (){
        return createDate;
    }
    
    public void setCreateDate (java.util.Date createDate){
        this.createDate = createDate;
    }
    public String getOrderId (){
        return orderId;
    }
    
    public void setOrderId (String orderId){
        this.orderId = orderId;
    }

}