/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.quartzruninfo.impl;

import com.pay.fundout.withdraw.dao.quartzruninfo.QuartzRunInfoDAO;
import com.pay.fundout.withdraw.model.quartzruninfo.QuartzRunInfo;
import com.pay.inf.dao.impl.BaseDAOImpl;

@SuppressWarnings("unchecked")
public class QuartzRunInfoDAOImpl extends BaseDAOImpl<QuartzRunInfo> implements
		QuartzRunInfoDAO {
}