/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.poss.report.dao;

import java.util.List;
import java.util.Map;

import com.pay.inf.dao.BaseDAO;
import com.pay.inf.dao.Page;
import com.pay.poss.report.dto.MemberFeeDTO;

public interface MemberFeeDAO extends BaseDAO<MemberFeeDTO> {

	/**
	 * 查询会员信息带分页
	 * 
	 * @param page
	 * @param map
	 * @return
	 */
	public Page<MemberFeeDTO> queryMemberFee(Page<MemberFeeDTO> page,
			Map<String, Object> map);

	/**
	 * 查询分页信息
	 * 
	 * @param map
	 * @return
	 */
	public List<MemberFeeDTO> queryMemberFee(Map<String, Object> map);

}