/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.poss.report.dao;

import java.util.Map;

import com.pay.inf.dao.BaseDAO;
import com.pay.inf.dao.Page;
import com.pay.poss.report.dto.MemberFlowPackageMonitorDTO;

public interface MemberFlowPackageMonitorDAO extends
		BaseDAO<MemberFlowPackageMonitorDTO> {

	/**
	 * 查询包量会员流量监控列表
	 * 
	 * @param page
	 * @param map
	 * @return
	 */
	public Page<MemberFlowPackageMonitorDTO> queryMemberFlowPackageMonitor(
			Page<MemberFlowPackageMonitorDTO> page, Map<String, Object> map);

}