/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.txncore.model;
/**
* BATCH_REFUND
*/

public class BatchRefund  implements java.io.Serializable {

    private Long total;
    private Integer auditStatus;
    private java.util.Date auditDate;
    private String remark;
    private String partnerId;
    private Long totalAmount;
    private Long fileNo;
    private Long batchRefundNo;
    private Integer actionStatus;
    private String applyOperator;
    private java.util.Date applyDate;
    private String auditOperator;
    private String fileName;
    
    public Long getTotal (){
        return total;
    }
    
    public void setTotal (Long total){
        this.total = total;
    }
    public Integer getAuditStatus (){
        return auditStatus;
    }
    
    public void setAuditStatus (Integer auditStatus){
        this.auditStatus = auditStatus;
    }
    public java.util.Date getAuditDate (){
        return auditDate;
    }
    
    public void setAuditDate (java.util.Date auditDate){
        this.auditDate = auditDate;
    }
    public String getRemark (){
        return remark;
    }
    
    public void setRemark (String remark){
        this.remark = remark;
    }
    public String getPartnerId (){
        return partnerId;
    }
    
    public void setPartnerId (String partnerId){
        this.partnerId = partnerId;
    }
    public Long getTotalAmount (){
        return totalAmount;
    }
    
    public void setTotalAmount (Long totalAmount){
        this.totalAmount = totalAmount;
    }
    public Long getFileNo (){
        return fileNo;
    }
    
    public void setFileNo (Long fileNo){
        this.fileNo = fileNo;
    }
    public Long getBatchRefundNo (){
        return batchRefundNo;
    }
    
    public void setBatchRefundNo (Long batchRefundNo){
        this.batchRefundNo = batchRefundNo;
    }
    public Integer getActionStatus (){
        return actionStatus;
    }
    
    public void setActionStatus (Integer actionStatus){
        this.actionStatus = actionStatus;
    }
    public String getApplyOperator (){
        return applyOperator;
    }
    
    public void setApplyOperator (String applyOperator){
        this.applyOperator = applyOperator;
    }
    public java.util.Date getApplyDate (){
        return applyDate;
    }
    
    public void setApplyDate (java.util.Date applyDate){
        this.applyDate = applyDate;
    }
    public String getAuditOperator (){
        return auditOperator;
    }
    
    public void setAuditOperator (String auditOperator){
        this.auditOperator = auditOperator;
    }

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

    
}