/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.txncore.model;
/**
* COMMON_UPLOAD_FILE
*/

public class CommonUploadFile  implements java.io.Serializable {

    private Long fileSize;
    private String fileName;
    private Long fileNo;
    private java.util.Date uploadTime;
    private byte[] fileContent;
    private String operator;
    private String fileFormat;

    public Long getFileSize (){
        return fileSize;
    }
    
    public void setFileSize (Long fileSize){
        this.fileSize = fileSize;
    }
    public String getFileName (){
        return fileName;
    }
    
    public void setFileName (String fileName){
        this.fileName = fileName;
    }
    public Long getFileNo (){
        return fileNo;
    }
    
    public void setFileNo (Long fileNo){
        this.fileNo = fileNo;
    }
    public java.util.Date getUploadTime (){
        return uploadTime;
    }
    
    public void setUploadTime (java.util.Date uploadTime){
        this.uploadTime = uploadTime;
    }
    public byte[] getFileContent (){
        return fileContent;
    }
    
    public void setFileContent (byte[] fileContent){
        this.fileContent = fileContent;
    }
    public String getOperator (){
        return operator;
    }
    
    public void setOperator (String operator){
        this.operator = operator;
    }
    public String getFileFormat (){
        return fileFormat;
    }
    
    public void setFileFormat (String fileFormat){
        this.fileFormat = fileFormat;
    }

}