/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.txncore.model;
/**
* PARTNER_CONFIG
*/

public class PartnerConfig  implements java.io.Serializable {

    private String remark;
    private String description;
    private String value;
    private Long partnerConfigNo;
    private Long memberCode;
    private String paramCode;

    public String getRemark (){
        return remark;
    }
    
    public void setRemark (String remark){
        this.remark = remark;
    }
    public String getDescription (){
        return description;
    }
    
    public void setDescription (String description){
        this.description = description;
    }
    public String getValue (){
        return value;
    }
    
    public void setValue (String value){
        this.value = value;
    }
    public Long getPartnerConfigNo (){
        return partnerConfigNo;
    }
    
    public void setPartnerConfigNo (Long partnerConfigNo){
        this.partnerConfigNo = partnerConfigNo;
    }
    public Long getMemberCode (){
        return memberCode;
    }
    
    public void setMemberCode (Long memberCode){
        this.memberCode = memberCode;
    }
    public String getParamCode (){
        return paramCode;
    }
    
    public void setParamCode (String paramCode){
        this.paramCode = paramCode;
    }

}