/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.channel.dao;

import com.pay.channel.model.ChannelResponse;
import com.pay.inf.dao.BaseDAO;

public interface ChannelResponseDAO extends BaseDAO<ChannelResponse> {

}