package com.pay.fo.order.dao.task;

import com.pay.fo.order.model.task.PaymentTaskInfo;
import com.pay.fo.order.model.task.PaymentTaskInfoExample;
import java.util.List;

public interface PaymentTaskInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FO.PAYMENT_TASK_INFO
     *
     * @ibatorgenerated Tue Nov 01 17:25:26 CST 2011
     */
    int countByExample(PaymentTaskInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FO.PAYMENT_TASK_INFO
     *
     * @ibatorgenerated Tue Nov 01 17:25:26 CST 2011
     */
    void insert(PaymentTaskInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FO.PAYMENT_TASK_INFO
     *
     * @ibatorgenerated Tue Nov 01 17:25:26 CST 2011
     */
    void insertSelective(PaymentTaskInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FO.PAYMENT_TASK_INFO
     *
     * @ibatorgenerated Tue Nov 01 17:25:26 CST 2011
     */
    List selectByExample(PaymentTaskInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FO.PAYMENT_TASK_INFO
     *
     * @ibatorgenerated Tue Nov 01 17:25:26 CST 2011
     */
    int updateByExampleSelective(PaymentTaskInfo record, PaymentTaskInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FO.PAYMENT_TASK_INFO
     *
     * @ibatorgenerated Tue Nov 01 17:25:26 CST 2011
     */
    int updateByExample(PaymentTaskInfo record, PaymentTaskInfoExample example);
}