/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.workflowlog.impl;

import com.pay.fundout.withdraw.dao.workflowlog.WithdrawWfLogDAO;
import com.pay.fundout.withdraw.model.workflowlog.WithdrawWfLog;
import com.pay.inf.dao.impl.BaseDAOImpl;

@SuppressWarnings("unchecked")
public class WithdrawWfLogDAOImpl extends BaseDAOImpl<WithdrawWfLog> implements
		WithdrawWfLogDAO {
}