package com.pay.poss.util;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableSet;

import java.math.BigDecimal;

/**
 * Created by songyilin on 2016/10/13 0013.
 */
public class ExcelColNameUtil {

    public static final ImmutableMap<String, String> colMap = new ImmutableMap.Builder<String, String>()
            .put("entryAcctCode", "ACCT_CODE")
            .put("entryDealId", "DEALID")
            .put("entryValue", "VALUE")
            .put("entryBalance", "BALANCE")
            .put("entryCrdr", "CRDR")
            .put("entryBalanceDirect", "BALANCE_DIRECT")
            .put("entryDealCode", "DEAL_CODE")
            .put("entryCreationDate", "CREATION_DATE")
            .put("entryBentryId", "BENTRY_ID")
            .put("entryPaymentServiceCode", "PAYMENT_SERVICE_CODE")
            .put("entryTransactionDate", "TRANSACTION_DATE")
            .put("entryPayDate", "PAY_DATE")
            .put("entryPostDate", "POST_DATE")
            .put("entryCurrencyCode", "CURRENCY_CODE")
            .put("entryExchangeRate", "EXCHANGE_RATE")
            .put("entryType", "ENTRY_TYPE")
            .put("entryStatus", "STATUS")
            .put("partnerId", "商户号")
            .put("orderId", "商户订单号")
            .put("tradeOrderNo", "网关订单号")
            .put("paymentOrderNo", "支付订单号")
            .put("channelOrderNo", "渠道订单号")
            .put("orgCode", "渠道号")
            .put("amount", "交易金额")
            .put("currencyCode", "交易币种")
            .put("transferRate", "交易汇率")
            .put("channelStatus", "渠道结果")
            .put("gatewayStatus", "网关结果")
            .put("tradeDate", "交易时间")
            .put("payAmount", "支付金额")
            .put("transferCurrencyCode", "支付币种")
            .put("settlementCurrencyCode", "清算币种")
            .put("settlementRate", "清算汇率")
            .put("feeRate", "手续费汇率")
            .put("merchantNo", "渠道二级号")
            .put("authorisation", "授权码")
            .put("settlementDate", "清算日期")
            .put("settlementCreatedate", "清算创建时间")
            .put("settlementFlg", "清算标志")
            .put("area", "地区")
            .put("refundAmount", "退款金额")
            .put("settlementAmount", "清算金额")
            .put("refundOrder", "退款交易号")
            .put("refundType", "退款类型")
            .put("refundStatus", "状态")
            .put("reconciliationFlg", "是否对账")
            .put("createDate", "创建时间")
            .put("payRate", "支付汇率")
            .put("preAmount", "原金额")
            .put("channelReturnNo", "参考号")
            .put("completeDate", "完成时间")
            .put("cardType", "卡种")
            .put("succeedCount", "成功交易笔数")
            .put("failedCount", "失败交易笔数")
            .put("succeedRate", "成功率")
            .put("allCount", "总笔数")
            .put("succeedAmt", "成功交易金额")
            .put("date", "日期")
            .put("dataDate", "日期")
            .put("gatewayDate", "日期时间")
            .put("riskRefuseCount", "风控拒绝笔数")
            .put("riskRefuseRate", "风控拒绝笔数")
            .put("notGrantCount", "银行不授权笔数")
            .put("notGrantRate", "银行不授权比率")
            .put("cheatCount", "欺诈卡笔数")
            .put("cheatRate", "欺诈比率")
            .put("cardNo", "卡号")
            .put("name", "姓名")
            .put("mail", "邮箱")
            .put("ip", "IP")
            .put("mobile", "手机号")
            .put("orderAmount", "交易金额")
            .put("weburl", "网址")
            .put("respCode", "商户返回码")
            .put("respMsg", "商户返回原因")
            .put("errorCode", "渠道错误代码")
            .put("errorMsg", "银行返回原因")
            .put("billName", "账单名称")
            .put("billAdress", "账单地址")
            .put("billEmail", "账单邮箱")
            .put("billPhonenumber", "账单手机号")
            .put("billPostalcode", "账单邮编")
            .put("billStreet", "账单街道")
            .put("billCity", "账单城市")
            .put("billState", "账单州")
            .put("billCountrycode", "账单国家")
            .put("shippingName", "收货人")
            .put("shippingAddress", "收货地址")
            .put("shippingMail", "收货邮箱")
            .put("shippingPhonenumber", "收货手机号")
            .put("shippingPostalcode", "收货邮编")
            .put("shippingCompany", "收货公司")
            .put("shippingStreet", "收货街道")
            .put("shippingCity", "收货城市")
            .put("shippingState", "收货大州")
            .put("shippingCountrycode", "收货国家")
            .put("cardholderNumber", "持卡人卡号")
            .put("cardholderFirstname", "持卡人名")
            .put("cardholderLastname", "持卡人姓")
            .put("cardholderEmail", "持卡人邮箱")
            .put("cardholderPhonenumber", "持卡人手机")
            .put("cardBin", "卡BIN")
            .put("orderSucceedAmount", "成功总金额")
            .put("orderSucceedCount", "成功总笔数")
            .put("refundCount", "退款笔数")
            .put("vcardRmbAmount", "V成功交易金额")
            .put("vCardCount", "V卡成功交易笔数")
            .put("mcardRmbAmount", "M卡成功交易金额")
            .put("mcardCount", "M卡成功交易笔数")
            .put("returnNo", "银行提供的订单号")
            .put("tradeDateTemplate", "交易时间(格式: YYYY-MM-DD)")
            .put("oriTransNo", "原始订单号")
            .put("partnerIdTwo", "会员号")
            .put("issuerCountry", "ISSUER_COUNTRY")
            .put("merchantNoTwo", "通道二级号")
            .build();



    public static final ImmutableSet<String> euCountrySet = new ImmutableSet.Builder<String>()
            .add("AUSTRIA")
            .add("BELGIUM")
            .add("BULGARIA")
            .add("CYPRUS")
            .add("CROATIA")
            .add("CZECH_REPUBLIC")
            .add("DENMARK")
            .add("ESTONIA")
            .add("FINLAND")
            .add("FRANCE")
            .add("GERMANY")
            .add("GREECE")
            .add("HUNGARY")
            .add("IRELAND")
            .add("ITALY")
            .add("LATVIA")
            .add("LITHUANIA")
            .add("LUXEMBOURG")
            .add("MALTA")
            .add("NETHERLANDS")
            .add("POLAND")
            .add("PORTUGAL")
            .add("ROMANIA")
            .add("SLOVAKIA")
            .add("SLOVENIA")
            .add("SPAIN")
            .add("SWEDEN")
            .build();

    public static String getExcelColName(String name){
        return colMap.get(name);
    }

    public static boolean isEuCountry(String countryName){
        return euCountrySet.contains(countryName);
    }



}
