/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.fundout.channel.dto.configbank;

import com.pay.inf.model.BaseObject;

/**
* fundout_config_bank
*/

public class FundoutConfigBankDTO  extends BaseObject {

    private String configName;
    private Long channelId;
    private Long status;
    private String mark;
    private java.util.Date createDate;
    private Long targetBankId;
    private String operator;
    private java.util.Date updateDate;
    private Long configId;
    private Long modeId;
    private Long businessId;

    public Long getModeId() {
		return modeId;
	}

	public void setModeId(Long modeId) {
		this.modeId = modeId;
	}

	public Long getBusinessId() {
		return businessId;
	}

	public void setBusinessId(Long businessId) {
		this.businessId = businessId;
	}

	public String getConfigName (){
        return configName;
    }
    
    public void setConfigName (String configName){
        this.configName = configName;
    }
    public Long getChannelId (){
        return channelId;
    }
    
    public void setChannelId (Long channelId){
        this.channelId = channelId;
    }
    public Long getStatus (){
        return status;
    }
    
    public void setStatus (Long status){
        this.status = status;
    }
    public String getMark (){
        return mark;
    }
    
    public void setMark (String mark){
        this.mark = mark;
    }
    public java.util.Date getCreateDate (){
        return createDate;
    }
    
    public void setCreateDate (java.util.Date createDate){
        this.createDate = createDate;
    }
    public Long getTargetBankId (){
        return targetBankId;
    }
    
    public void setTargetBankId (Long targetBankId){
        this.targetBankId = targetBankId;
    }
    public String getOperator (){
        return operator;
    }
    
    public void setOperator (String operator){
        this.operator = operator;
    }
    public java.util.Date getUpdateDate (){
        return updateDate;
    }
    
    public void setUpdateDate (java.util.Date updateDate){
        this.updateDate = updateDate;
    }
    public Long getConfigId (){
        return configId;
    }
    
    public void setConfigId (Long configId){
        this.configId = configId;
    }

}