/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import java.util.List;
import java.util.Map;

import com.pay.inf.dao.BaseDAO;
import com.pay.inf.dao.Page;
import com.pay.txncore.model.BatchRefund;
import com.pay.txncore.model.BatchRefundResult;

public interface BatchRefundDAO extends BaseDAO {

	/**
	 * 
	 * @param param
	 * @param page
	 * @return
	 */
	List<BatchRefund> queryBatchRefundList(Map param, Page page);

	/**
	 * 
	 * @param param
	 * @return
	 */
	int countBatchRefundList(Map param);

	/**
	 * 
	 * @param param
	 * @param page
	 * @return
	 */
	List<BatchRefundResult> queryBatchRefundOrder(Map param, Page page);

	/**
	 * 
	 * @param param
	 * @return
	 */
	Map countBatchRefundOrder(Map param);
}