/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.model.RefundOrderConfirm;

public interface RefundOrderConfirmDAO extends BaseDAO {

	/**
	 * 
	 * @param refundConfirmId
	 * @param status
	 * @return
	 */
	public boolean updateRefundOrderConfirmState(Long refundConfirmId, String status);
	
	/**
	 * 
	 * @param refundConfirmId
	 * @param status
	 * @return
	 */
	public boolean updateRefundOrderConfirmStateAfter(Long refundConfirmId, String status, Date preStartTime);

	/**
	 * 根据退款订单号获取退款确认订单
	 * 
	 * @param refundOrderNo
	 * @return
	 */
	List<RefundOrderConfirm> findByRefundOrderNo(Long refundOrderNo);
	
	/**
	 * 查询退款确认订单
	 * 
	 * @param param
	 * @return
	 */
	List<RefundOrderConfirm> queryRefundConfirmList(Map param);
	
}