/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.model.DepositBackProtocol;

public interface DepositBackProtocolDAO extends BaseDAO<DepositBackProtocol> {

	/**
	 * 通过充退订单号获取充退协议
	 * 
	 * @param depositBackNo
	 * @return
	 */
	public DepositBackProtocol queryBydepositBackNo(Long depositBackNo);
}