/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.model.DepositBackOrder;
import com.pay.txncore.model.DepositBackProtocol;

public interface DepositBackOrderDAO extends BaseDAO<DepositBackOrder> {

	/**
	 * 根据充退订单Id 查询充退协议
	 * 
	 * @param id
	 * @return
	 */
	public DepositBackProtocol queryDepositBackProtocol(long id);

	/**
	 * 根据充值订单流水号depositOrderNo 查询充退订单
	 * 
	 * @param depositOrderNo
	 * @return
	 */
	public DepositBackOrder findByBackNoForUpdate(long depositOrderNo);

}