/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import java.util.List;
import java.util.Map;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.model.RefundApply;

public interface RefundApplyDAO extends BaseDAO<RefundApply> {

	/**
	 * 
	 * @param param
	 * @param pageSize
	 * @param page
	 * @return
	 */
	public List<RefundApply> queryRefundApplyList(Map param, int pageSize,
			int page);

	/**
	 * 
	 * @param param
	 * @return
	 */
	public String[] totalItemNumAndAmount(Map param);

	/**
	 * 
	 * @param refundApply
	 * @return
	 */
	public boolean modifyApply(RefundApply refundApply);
}