/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao;

import com.pay.inf.dao.BaseDAO;
import com.pay.txncore.model.TradeExtends;

public interface TradeExtendsDAO extends BaseDAO<TradeExtends> {

	/**
	 * 
	 * @param tradeOrderNo
	 * @return
	 */
	TradeExtends findByTradeOrderNo(Long tradeOrderNo);

}