/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.txncore.dao.impl;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.SqlMapClientCallback;

import com.ibatis.sqlmap.client.SqlMapExecutor;
import com.pay.inf.dao.impl.BaseDAOImpl;
import com.pay.txncore.dao.CreditFilterDAO;
import com.pay.txncore.model.CreditFilter;

public class CreditFilterDAOImpl extends BaseDAOImpl  implements CreditFilterDAO {

	@Override
	public String queryCreditFilterMaxDate() {
		return (String) getSqlMapClientTemplate()
				.queryForObject(namespace.concat("queryCreditFilterMaxDate"),
						null);
	}
	
	@Override
	public List<CreditFilter> queryCreditFilterList(CreditFilter creditFilter) {

		return super.findByCriteria("queryCreditFilterList", creditFilter);
	}
	@Override
	public List<CreditFilter> queryCreditBalanceList(Map map) {
		
		return super.findByCriteria("queryCreditBalanceList", map);
	}
	
	@Override
	public List<CreditFilter> queryChageBackOrderList(Map map) {
		
		return super.findByCriteria("queryChageBackOrderList", map);
	}
	@Override
	public String queryBatchStatus(Map map) {
		
		return (String) getSqlMapClientTemplate()
				.queryForObject(namespace.concat("queryBatchStatus"),
						map);
	}
	@Override
	public void updateBatchStatus(Map map) {
		super.update("update", map);
		//getSqlMapClientTemplate().update(namespace.concat("update"), map);
	}
	
	@Override
	public void create(CreditFilter pojo) {
		getSqlMapClientTemplate().insert(namespace.concat("create"), pojo);
	}
}