package com.pay.pe.exception.coa;

import com.pay.inf.exception.AppException;
import com.pay.pe.exception.ErrorLevel;

/**
 * Subclass of <code>AppException</code> generated by tool
 * g
 *
 */
public class SubjectIsExistException extends AppException {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6041188082271005200L;

	/**
     * Constructs an exception
     *
     */
    public SubjectIsExistException() {
        super("30003", ErrorLevel.WARN);
    }

    /**
     * Constructs an exception with root cause
     * @param cause The root cause
     */
    public SubjectIsExistException(Throwable cause) {
		super("30003", cause, ErrorLevel.WARN);
    }

}
