package com.pay.pe.exception.coa;

import com.pay.inf.exception.AppException;
import com.pay.pe.exception.ErrorLevel;

/**
 * Subclass of <code>AppException</code> generated by tool
 * g
 *
 */
public class SummarizeAccountNotNullException extends AppException {

    /**
	 * 
	 */
	private static final long serialVersionUID = 2227203943737618502L;

	/**
     * Constructs an exception
     *
     */
    public SummarizeAccountNotNullException() {
        super("30006", ErrorLevel.WARN);
    }

    /**
     * Constructs an exception with root cause
     * @param cause The root cause
     */
    public SummarizeAccountNotNullException(Throwable cause) {
		super("30006", cause, ErrorLevel.WARN);
    }

}
