/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.rm.service.dao.rmnamelist;

import com.pay.inf.dao.BaseDAO;

public interface RcNameListDAO<RcNameList> extends BaseDAO<RcNameList> {
}