package com.pay.fo.order.dao.batchpayment;

import java.util.List;

import com.pay.fo.order.model.batchpayment.BatchPaymentReqBaseInfo;
import com.pay.fo.order.model.batchpayment.BatchPaymentReqBaseInfoExample;

public interface BatchPaymentReqBaseInfoDAO {
	

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	int countByExample(BatchPaymentReqBaseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	Long insert(BatchPaymentReqBaseInfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	Long insertSelective(BatchPaymentReqBaseInfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	List selectByExample(BatchPaymentReqBaseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	BatchPaymentReqBaseInfo selectByPrimaryKey(Long requestSeq);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	int updateByExampleSelective(BatchPaymentReqBaseInfo record,
			BatchPaymentReqBaseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	int updateByExample(BatchPaymentReqBaseInfo record,
			BatchPaymentReqBaseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	int updateByPrimaryKeySelective(BatchPaymentReqBaseInfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	int updateByPrimaryKey(BatchPaymentReqBaseInfo record);
}