package com.pay.fo.order.dao.batchpayment;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pay.fo.order.model.base.FundoutOrder;
import com.pay.fo.order.model.base.PayToAcctOrder;
import com.pay.fo.order.model.batchpayment.BatchPaymentOrder;
import com.pay.fo.order.model.batchpayment.BatchPaymentOrderExample;
import com.pay.fo.order.model.batchpayment.BatchPaymentTotalInfo;

public class BatchPaymentOrderDAOImpl extends SqlMapClientDaoSupport implements BatchPaymentOrderDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public BatchPaymentOrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public Long insert(BatchPaymentOrder record) {
        Object newKey = getSqlMapClientTemplate().insert("FO_BATCH_PAYMENTORDER.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public int updateByPrimaryKey(BatchPaymentOrder record) {
        int rows = getSqlMapClientTemplate().update("FO_BATCH_PAYMENTORDER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public int updateByPrimaryKeySelective(BatchPaymentOrder record) {
        int rows = getSqlMapClientTemplate().update("FO_BATCH_PAYMENTORDER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public List selectByExample(BatchPaymentOrderExample example) {
        List list = getSqlMapClientTemplate().queryForList("FO_BATCH_PAYMENTORDER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public BatchPaymentOrder selectByPrimaryKey(Long orderId) {
        BatchPaymentOrder key = new BatchPaymentOrder();
        key.setOrderId(orderId);
        BatchPaymentOrder record = (BatchPaymentOrder) getSqlMapClientTemplate().queryForObject("FO_BATCH_PAYMENTORDER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public int deleteByExample(BatchPaymentOrderExample example) {
        int rows = getSqlMapClientTemplate().delete("FO_BATCH_PAYMENTORDER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public int deleteByPrimaryKey(Long orderId) {
        BatchPaymentOrder key = new BatchPaymentOrder();
        key.setOrderId(orderId);
        int rows = getSqlMapClientTemplate().delete("FO_BATCH_PAYMENTORDER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public int countByExample(BatchPaymentOrderExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("FO_BATCH_PAYMENTORDER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public int updateByExampleSelective(BatchPaymentOrder record, BatchPaymentOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("FO_BATCH_PAYMENTORDER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    public int updateByExample(BatchPaymentOrder record, BatchPaymentOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("FO_BATCH_PAYMENTORDER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table FO.BATCH_PAYMENTORDER
     *
     * @abatorgenerated Thu Jun 16 10:55:44 CST 2011
     */
    private static class UpdateByExampleParms extends BatchPaymentOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, BatchPaymentOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List getCompleteBatchPay2AcctOrders() {
		return getSqlMapClientTemplate().queryForList("FO_BATCH_PAYMENTORDER.getCompleteBatchPay2AcctOrders");
	}

	@Override
	public List getCompleteBatchPay2BankOrders() {
		return getSqlMapClientTemplate().queryForList("FO_BATCH_PAYMENTORDER.getCompleteBatchPay2BankOrders");
	}

	@Override
	public BatchPaymentTotalInfo getTotalComplateBatchPay2BankOrder(
			Long parentOrderId) {
		BatchPaymentTotalInfo info = new BatchPaymentTotalInfo();
		info.setParentOrderId(parentOrderId);
		info = (BatchPaymentTotalInfo)getSqlMapClientTemplate().queryForObject("FO_BATCH_PAYMENTORDER.getTotalComplateBatchPay2BankOrder", info);
		return info;
	}

	@Override
	public BatchPaymentTotalInfo getTotalComplateBatchPay2AcctOrder(
			Long parentOrderId) {
		BatchPaymentTotalInfo info = new BatchPaymentTotalInfo();
		info.setParentOrderId(parentOrderId);
		info = (BatchPaymentTotalInfo)getSqlMapClientTemplate().queryForObject("FO_BATCH_PAYMENTORDER.getTotalComplateBatchPay2AcctOrder", info);
		return info;
	}

	/* (non-Javadoc)
	 * @see com.pay.fo.order.dao.batchpayment.BatchPaymentOrderDAO#getAcctDetailOrderByParentId(java.lang.Long)
	 */
	@SuppressWarnings("unchecked")
	@Override
	public List<PayToAcctOrder> getAcctDetailOrderByParentId(Long parentId) {
		return getSqlMapClientTemplate().queryForList("FO_BATCH_PAYMENTORDER.getAcctDetailOrderByParentId",parentId);
	}

	/* (non-Javadoc)
	 * @see com.pay.fo.order.dao.batchpayment.BatchPaymentOrderDAO#getBankDetailOrderByParentId(java.lang.Long)
	 */
	@SuppressWarnings("unchecked")
	@Override
	public List<FundoutOrder> getBankDetailOrderByParentId(Long parentId) {
		return getSqlMapClientTemplate().queryForList("FO_BATCH_PAYMENTORDER.getBankDetailOrderByParentId",parentId);
	}
}