package com.pay.fo.order.dao.batchpayment;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pay.fo.order.model.batchpayment.BatchPaymentToAcctReqDetail;
import com.pay.fo.order.model.batchpayment.BatchPaymentToAcctReqDetailExample;
import com.pay.inf.exception.AppException;

public class BatchPaymentToAcctReqDetailDAOImpl extends SqlMapClientDaoSupport implements BatchPaymentToAcctReqDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public BatchPaymentToAcctReqDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public void insert(BatchPaymentToAcctReqDetail record) {
		getSqlMapClientTemplate().insert(
				"FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public int updateByPrimaryKey(BatchPaymentToAcctReqDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public int updateByPrimaryKeySelective(BatchPaymentToAcctReqDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public List selectByExample(BatchPaymentToAcctReqDetailExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public BatchPaymentToAcctReqDetail selectByPrimaryKey(Long detailSeq) {
		BatchPaymentToAcctReqDetail key = new BatchPaymentToAcctReqDetail();
		key.setDetailSeq(detailSeq);
		BatchPaymentToAcctReqDetail record = (BatchPaymentToAcctReqDetail) getSqlMapClientTemplate()
				.queryForObject(
						"FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public int deleteByExample(BatchPaymentToAcctReqDetailExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public int deleteByPrimaryKey(Long detailSeq) {
		BatchPaymentToAcctReqDetail key = new BatchPaymentToAcctReqDetail();
		key.setDetailSeq(detailSeq);
		int rows = getSqlMapClientTemplate()
				.delete("FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public int countByExample(BatchPaymentToAcctReqDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_countByExample",
						example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public int updateByExampleSelective(BatchPaymentToAcctReqDetail record,
			BatchPaymentToAcctReqDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	public int updateByExample(BatchPaymentToAcctReqDetail record,
			BatchPaymentToAcctReqDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	private static class UpdateByExampleParms extends
			BatchPaymentToAcctReqDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				BatchPaymentToAcctReqDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public void insert(List<BatchPaymentToAcctReqDetail> records) throws AppException {
		try {
			getSqlMapClient().startBatch();
			for (BatchPaymentToAcctReqDetail record : records) {
				getSqlMapClient().insert("FO_BATCH_PAYMENTTOACCTREQDETAIL.abatorgenerated_insert", record);
			}
			getSqlMapClient().executeBatch();
		} catch (SQLException e) {
			throw new AppException(e);
		}
		
	}
}