package com.pay.fo.order.dao.batchpayment;

import java.util.List;

import com.pay.fo.order.model.batchpayment.BatchPaymentToAcctReqDetail;
import com.pay.fo.order.model.batchpayment.BatchPaymentToAcctReqDetailExample;
import com.pay.inf.exception.AppException;

public interface BatchPaymentToAcctReqDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	void insert(BatchPaymentToAcctReqDetail record);
	
	void insert(List<BatchPaymentToAcctReqDetail> records) throws AppException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	int updateByPrimaryKey(BatchPaymentToAcctReqDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	int updateByPrimaryKeySelective(BatchPaymentToAcctReqDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	List selectByExample(BatchPaymentToAcctReqDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	BatchPaymentToAcctReqDetail selectByPrimaryKey(Long detailSeq);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	int deleteByExample(BatchPaymentToAcctReqDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	int deleteByPrimaryKey(Long detailSeq);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	int countByExample(BatchPaymentToAcctReqDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	int updateByExampleSelective(BatchPaymentToAcctReqDetail record,
			BatchPaymentToAcctReqDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FO.BATCH_PAYMENTTOACCTREQDETAIL
	 * @abatorgenerated  Mon Jun 13 17:29:12 CST 2011
	 */
	int updateByExample(BatchPaymentToAcctReqDetail record,
			BatchPaymentToAcctReqDetailExample example);
}