package com.pay.fo.order.dao.batchpayment;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pay.fo.order.model.batchpayment.BatchPaymentReqBaseInfo;
import com.pay.fo.order.model.batchpayment.BatchPaymentReqBaseInfoExample;

public class BatchPaymentReqBaseInfoDAOImpl extends SqlMapClientDaoSupport implements BatchPaymentReqBaseInfoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public BatchPaymentReqBaseInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public int countByExample(BatchPaymentReqBaseInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long insert(BatchPaymentReqBaseInfo record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long insertSelective(BatchPaymentReqBaseInfo record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_insertSelective",
				record);
		return (Long) newKey;
	}
	

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public List selectByExample(BatchPaymentReqBaseInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public BatchPaymentReqBaseInfo selectByPrimaryKey(Long requestSeq) {
		BatchPaymentReqBaseInfo key = new BatchPaymentReqBaseInfo();
		key.setRequestSeq(requestSeq);
		BatchPaymentReqBaseInfo record = (BatchPaymentReqBaseInfo) getSqlMapClientTemplate()
				.queryForObject(
						"FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public int updateByExampleSelective(BatchPaymentReqBaseInfo record,
			BatchPaymentReqBaseInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public int updateByExample(BatchPaymentReqBaseInfo record,
			BatchPaymentReqBaseInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public int updateByPrimaryKeySelective(BatchPaymentReqBaseInfo record) {
		int rows = getSqlMapClientTemplate()
				.update("FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public int updateByPrimaryKey(BatchPaymentReqBaseInfo record) {
		int rows = getSqlMapClientTemplate()
				.update("FO_BATCH_PAYMENTREQBASEINFO.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table FO.BATCH_PAYMENTREQBASEINFO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private static class UpdateByExampleParms extends
			BatchPaymentReqBaseInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				BatchPaymentReqBaseInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}