package com.pay.fo.order.dao.batchpayment;

import java.util.List;

import com.pay.fo.order.model.batchpayment.BatchPaymentToBankReqDetail;
import com.pay.fo.order.model.batchpayment.BatchPaymentToBankReqDetailExample;
import com.pay.inf.exception.AppException;

public interface BatchPaymentToBankReqDetailDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    void insert(BatchPaymentToBankReqDetail record);

    void insert(List<BatchPaymentToBankReqDetail> records) throws AppException;
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    int updateByPrimaryKey(BatchPaymentToBankReqDetail record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    int updateByPrimaryKeySelective(BatchPaymentToBankReqDetail record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    List selectByExample(BatchPaymentToBankReqDetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    BatchPaymentToBankReqDetail selectByPrimaryKey(Long detailSeq);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    int deleteByExample(BatchPaymentToBankReqDetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    int deleteByPrimaryKey(Long detailSeq);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    int countByExample(BatchPaymentToBankReqDetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    int updateByExampleSelective(BatchPaymentToBankReqDetail record, BatchPaymentToBankReqDetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    int updateByExample(BatchPaymentToBankReqDetail record, BatchPaymentToBankReqDetailExample example);

}