package com.pay.fo.order.dao.batchpayment;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pay.fo.order.model.batchpayment.BatchPaymentToBankReqDetail;
import com.pay.fo.order.model.batchpayment.BatchPaymentToBankReqDetailExample;
import com.pay.inf.exception.AppException;

public class BatchPaymentToBankReqDetailDAOImpl extends SqlMapClientDaoSupport implements BatchPaymentToBankReqDetailDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public BatchPaymentToBankReqDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public void insert(BatchPaymentToBankReqDetail record) {
       getSqlMapClientTemplate().insert("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public int updateByPrimaryKey(BatchPaymentToBankReqDetail record) {
        int rows = getSqlMapClientTemplate().update("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public int updateByPrimaryKeySelective(BatchPaymentToBankReqDetail record) {
        int rows = getSqlMapClientTemplate().update("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public List selectByExample(BatchPaymentToBankReqDetailExample example) {
        List list = getSqlMapClientTemplate().queryForList("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public BatchPaymentToBankReqDetail selectByPrimaryKey(Long detailSeq) {
        BatchPaymentToBankReqDetail key = new BatchPaymentToBankReqDetail();
        key.setDetailSeq(detailSeq);
        BatchPaymentToBankReqDetail record = (BatchPaymentToBankReqDetail) getSqlMapClientTemplate().queryForObject("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public int deleteByExample(BatchPaymentToBankReqDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public int deleteByPrimaryKey(Long detailSeq) {
        BatchPaymentToBankReqDetail key = new BatchPaymentToBankReqDetail();
        key.setDetailSeq(detailSeq);
        int rows = getSqlMapClientTemplate().delete("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public int countByExample(BatchPaymentToBankReqDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public int updateByExampleSelective(BatchPaymentToBankReqDetail record, BatchPaymentToBankReqDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public int updateByExample(BatchPaymentToBankReqDetail record, BatchPaymentToBankReqDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    private static class UpdateByExampleParms extends BatchPaymentToBankReqDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, BatchPaymentToBankReqDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    @Override
	public void insert(List<BatchPaymentToBankReqDetail> records) throws AppException {
		try {
			getSqlMapClient().startBatch();
			for (BatchPaymentToBankReqDetail record : records) {
				getSqlMapClient().insert("FO_BATCH_PAYMENTTOBANKREQDETAIL.abatorgenerated_insert", record);
			}
			getSqlMapClient().executeBatch();
		} catch (SQLException e) {
			throw new AppException(e);
		}
		
	}
}