/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.fundout.withdraw.dto.bank;
/**
* WITHDRAW_BANK_CONFIG
*/

public class WithdrawBankConfigDTO  implements java.io.Serializable {

    private java.util.Date creationDate;
    private Integer withdrawTypeId;
    private Integer status;
    private String bankName;
    private Integer sequenceId;
    private Integer withdrawBusiId;
    private java.util.Date updateDate;
    private String bankCode;
    private String typeName;
    private String businessName;

    public java.util.Date getCreationDate (){
        return creationDate;
    }
    
    public void setCreationDate (java.util.Date creationDate){
        this.creationDate = creationDate;
    }
    public Integer getWithdrawTypeId (){
        return withdrawTypeId;
    }
    
    public void setWithdrawTypeId (Integer withdrawTypeId){
        this.withdrawTypeId = withdrawTypeId;
    }
    public Integer getStatus (){
        return status;
    }
    
    public void setStatus (Integer status){
        this.status = status;
    }
    public String getBankName (){
        return bankName;
    }
    
    public void setBankName (String bankName){
        this.bankName = bankName;
    }
    public Integer getSequenceId (){
        return sequenceId;
    }
    
    public void setSequenceId (Integer sequenceId){
        this.sequenceId = sequenceId;
    }
    public Integer getWithdrawBusiId (){
        return withdrawBusiId;
    }
    
    public void setWithdrawBusiId (Integer withdrawBusiId){
        this.withdrawBusiId = withdrawBusiId;
    }
    public java.util.Date getUpdateDate (){
        return updateDate;
    }
    
    public void setUpdateDate (java.util.Date updateDate){
        this.updateDate = updateDate;
    }
    public String getBankCode (){
        return bankCode;
    }
    
    public void setBankCode (String bankCode){
        this.bankCode = bankCode;
    }

	/**
	 * @return the typeName
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * @param typeName the typeName to set
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * @return the businessName
	 */
	public String getBusinessName() {
		return businessName;
	}

	/**
	 * @param businessName the businessName to set
	 */
	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}



}