/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.poss.base.calendar.dao;

import java.util.Date;
import java.util.Map;

import com.pay.inf.dao.BaseDAO;
import com.pay.inf.dao.Page;
import com.pay.poss.base.model.CalendarDto;

public interface CalendarDAO extends BaseDAO {

	public Page<CalendarDto> getCalendarList(Page<CalendarDto> page,
			Map<String, Object> params);

	public CalendarDto findByDate(Date date);

	public Date getActualWorkDay(Date date);

}