/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.model.masspaytobank;

/**
 * 
 * @author Sean_yi
 * @createtime 2010-12-20
 * @filename MassPaytobankImportDetail.java
 * @version 1.0
 */

public class MassPaytobankImportDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String businessOrderId;
	private String errorMessage;
	private String remark;
	private String cityName;
	private Integer provinceCode;
	private Integer cityCode;
	private String bankName;
	private String provinceName;
	private Integer validateStatus;
	private Long detailSeq;
	private String bankCode;
	private Long amount;
	private String uploadAmount;
	private String payeeName;
	private Long uploadSeq;
	private String openingBankName;
	private String payeeBankAcct;
	private Long fee;
	private Integer orderStatus;
	private String tradeType;

	public Integer getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	public String getBusinessOrderId() {
		return businessOrderId;
	}

	public void setBusinessOrderId(String businessOrderId) {
		this.businessOrderId = businessOrderId;
	}

	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public Integer getProvinceCode() {
		return provinceCode;
	}

	public void setProvinceCode(Integer provinceCode) {
		this.provinceCode = provinceCode;
	}

	public Integer getCityCode() {
		return cityCode;
	}

	public void setCityCode(Integer cityCode) {
		this.cityCode = cityCode;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	public Integer getValidateStatus() {
		return validateStatus;
	}

	public void setValidateStatus(Integer validateStatus) {
		this.validateStatus = validateStatus;
	}

	public Long getDetailSeq() {
		return detailSeq;
	}

	public void setDetailSeq(Long detailSeq) {
		this.detailSeq = detailSeq;
	}

	public String getBankCode() {
		return bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public Long getAmount() {
		return amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	public String getPayeeName() {
		return payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	public Long getUploadSeq() {
		return uploadSeq;
	}

	public void setUploadSeq(Long uploadSeq) {
		this.uploadSeq = uploadSeq;
	}

	public String getOpeningBankName() {
		return openingBankName;
	}

	public void setOpeningBankName(String openingBankName) {
		this.openingBankName = openingBankName;
	}

	public String getPayeeBankAcct() {
		return payeeBankAcct;
	}

	public void setPayeeBankAcct(String payeeBankAcct) {
		this.payeeBankAcct = payeeBankAcct;
	}

	public String getUploadAmount() {
		return uploadAmount;
	}

	public void setUploadAmount(String uploadAmount) {
		this.uploadAmount = uploadAmount;
	}

	public Long getFee() {
		return fee;
	}

	public void setFee(Long fee) {
		this.fee = fee;
	}

	public String getTradeType() {
		return tradeType;
	}

	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}
	
	

}