package com.pay.fo.order.model.batchpayment;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BatchPaymentToBankReqDetailExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public BatchPaymentToBankReqDetailExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    protected BatchPaymentToBankReqDetailExample(BatchPaymentToBankReqDetailExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table FO.BATCH_PAYMENTTOBANKREQDETAIL
     *
     * @abatorgenerated Mon Jun 13 17:37:36 CST 2011
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDetailSeqIsNull() {
            addCriterion("DETAIL_SEQ is null");
            return this;
        }

        public Criteria andDetailSeqIsNotNull() {
            addCriterion("DETAIL_SEQ is not null");
            return this;
        }

        public Criteria andDetailSeqEqualTo(Long value) {
            addCriterion("DETAIL_SEQ =", value, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqNotEqualTo(Long value) {
            addCriterion("DETAIL_SEQ <>", value, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqGreaterThan(Long value) {
            addCriterion("DETAIL_SEQ >", value, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("DETAIL_SEQ >=", value, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqLessThan(Long value) {
            addCriterion("DETAIL_SEQ <", value, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqLessThanOrEqualTo(Long value) {
            addCriterion("DETAIL_SEQ <=", value, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqIn(List values) {
            addCriterion("DETAIL_SEQ in", values, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqNotIn(List values) {
            addCriterion("DETAIL_SEQ not in", values, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqBetween(Long value1, Long value2) {
            addCriterion("DETAIL_SEQ between", value1, value2, "detailSeq");
            return this;
        }

        public Criteria andDetailSeqNotBetween(Long value1, Long value2) {
            addCriterion("DETAIL_SEQ not between", value1, value2, "detailSeq");
            return this;
        }

        public Criteria andRequestSeqIsNull() {
            addCriterion("REQUEST_SEQ is null");
            return this;
        }

        public Criteria andRequestSeqIsNotNull() {
            addCriterion("REQUEST_SEQ is not null");
            return this;
        }

        public Criteria andRequestSeqEqualTo(Long value) {
            addCriterion("REQUEST_SEQ =", value, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqNotEqualTo(Long value) {
            addCriterion("REQUEST_SEQ <>", value, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqGreaterThan(Long value) {
            addCriterion("REQUEST_SEQ >", value, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("REQUEST_SEQ >=", value, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqLessThan(Long value) {
            addCriterion("REQUEST_SEQ <", value, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqLessThanOrEqualTo(Long value) {
            addCriterion("REQUEST_SEQ <=", value, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqIn(List values) {
            addCriterion("REQUEST_SEQ in", values, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqNotIn(List values) {
            addCriterion("REQUEST_SEQ not in", values, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqBetween(Long value1, Long value2) {
            addCriterion("REQUEST_SEQ between", value1, value2, "requestSeq");
            return this;
        }

        public Criteria andRequestSeqNotBetween(Long value1, Long value2) {
            addCriterion("REQUEST_SEQ not between", value1, value2, "requestSeq");
            return this;
        }

        public Criteria andForeignOrderIdIsNull() {
            addCriterion("FOREIGN_ORDERID is null");
            return this;
        }

        public Criteria andForeignOrderIdIsNotNull() {
            addCriterion("FOREIGN_ORDERID is not null");
            return this;
        }

        public Criteria andForeignOrderIdEqualTo(String value) {
            addCriterion("FOREIGN_ORDERID =", value, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdNotEqualTo(String value) {
            addCriterion("FOREIGN_ORDERID <>", value, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdGreaterThan(String value) {
            addCriterion("FOREIGN_ORDERID >", value, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("FOREIGN_ORDERID >=", value, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdLessThan(String value) {
            addCriterion("FOREIGN_ORDERID <", value, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdLessThanOrEqualTo(String value) {
            addCriterion("FOREIGN_ORDERID <=", value, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdLike(String value) {
            addCriterion("FOREIGN_ORDERID like", value, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdNotLike(String value) {
            addCriterion("FOREIGN_ORDERID not like", value, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdIn(List values) {
            addCriterion("FOREIGN_ORDERID in", values, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdNotIn(List values) {
            addCriterion("FOREIGN_ORDERID not in", values, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdBetween(String value1, String value2) {
            addCriterion("FOREIGN_ORDERID between", value1, value2, "foreignOrderId");
            return this;
        }

        public Criteria andForeignOrderIdNotBetween(String value1, String value2) {
            addCriterion("FOREIGN_ORDERID not between", value1, value2, "foreignOrderId");
            return this;
        }

        public Criteria andPayeeNameIsNull() {
            addCriterion("PAYEE_NAME is null");
            return this;
        }

        public Criteria andPayeeNameIsNotNull() {
            addCriterion("PAYEE_NAME is not null");
            return this;
        }

        public Criteria andPayeeNameEqualTo(String value) {
            addCriterion("PAYEE_NAME =", value, "payeeName");
            return this;
        }

        public Criteria andPayeeNameNotEqualTo(String value) {
            addCriterion("PAYEE_NAME <>", value, "payeeName");
            return this;
        }

        public Criteria andPayeeNameGreaterThan(String value) {
            addCriterion("PAYEE_NAME >", value, "payeeName");
            return this;
        }

        public Criteria andPayeeNameGreaterThanOrEqualTo(String value) {
            addCriterion("PAYEE_NAME >=", value, "payeeName");
            return this;
        }

        public Criteria andPayeeNameLessThan(String value) {
            addCriterion("PAYEE_NAME <", value, "payeeName");
            return this;
        }

        public Criteria andPayeeNameLessThanOrEqualTo(String value) {
            addCriterion("PAYEE_NAME <=", value, "payeeName");
            return this;
        }

        public Criteria andPayeeNameLike(String value) {
            addCriterion("PAYEE_NAME like", value, "payeeName");
            return this;
        }

        public Criteria andPayeeNameNotLike(String value) {
            addCriterion("PAYEE_NAME not like", value, "payeeName");
            return this;
        }

        public Criteria andPayeeNameIn(List values) {
            addCriterion("PAYEE_NAME in", values, "payeeName");
            return this;
        }

        public Criteria andPayeeNameNotIn(List values) {
            addCriterion("PAYEE_NAME not in", values, "payeeName");
            return this;
        }

        public Criteria andPayeeNameBetween(String value1, String value2) {
            addCriterion("PAYEE_NAME between", value1, value2, "payeeName");
            return this;
        }

        public Criteria andPayeeNameNotBetween(String value1, String value2) {
            addCriterion("PAYEE_NAME not between", value1, value2, "payeeName");
            return this;
        }

        public Criteria andPayeeBankAcctCodeIsNull() {
            addCriterion("PAYEE_BANKACCTCODE is null");
            return this;
        }

        public Criteria andPayeeBankAcctCodeIsNotNull() {
            addCriterion("PAYEE_BANKACCTCODE is not null");
            return this;
        }

        public Criteria andPayeeBankAcctCodeEqualTo(String value) {
            addCriterion("PAYEE_BANKACCTCODE =", value, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeNotEqualTo(String value) {
            addCriterion("PAYEE_BANKACCTCODE <>", value, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeGreaterThan(String value) {
            addCriterion("PAYEE_BANKACCTCODE >", value, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKACCTCODE >=", value, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeLessThan(String value) {
            addCriterion("PAYEE_BANKACCTCODE <", value, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeLessThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKACCTCODE <=", value, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeLike(String value) {
            addCriterion("PAYEE_BANKACCTCODE like", value, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeNotLike(String value) {
            addCriterion("PAYEE_BANKACCTCODE not like", value, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeIn(List values) {
            addCriterion("PAYEE_BANKACCTCODE in", values, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeNotIn(List values) {
            addCriterion("PAYEE_BANKACCTCODE not in", values, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKACCTCODE between", value1, value2, "payeeBankAcctCode");
            return this;
        }

        public Criteria andPayeeBankAcctCodeNotBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKACCTCODE not between", value1, value2, "payeeBankAcctCode");
            return this;
        }

        public Criteria andTradeTypeIsNull() {
            addCriterion("TRADE_TYPE is null");
            return this;
        }

        public Criteria andTradeTypeIsNotNull() {
            addCriterion("TRADE_TYPE is not null");
            return this;
        }

        public Criteria andTradeTypeEqualTo(String value) {
            addCriterion("TRADE_TYPE =", value, "tradeType");
            return this;
        }

        public Criteria andTradeTypeNotEqualTo(String value) {
            addCriterion("TRADE_TYPE <>", value, "tradeType");
            return this;
        }

        public Criteria andTradeTypeGreaterThan(String value) {
            addCriterion("TRADE_TYPE >", value, "tradeType");
            return this;
        }

        public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_TYPE >=", value, "tradeType");
            return this;
        }

        public Criteria andTradeTypeLessThan(String value) {
            addCriterion("TRADE_TYPE <", value, "tradeType");
            return this;
        }

        public Criteria andTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_TYPE <=", value, "tradeType");
            return this;
        }

        public Criteria andTradeTypeLike(String value) {
            addCriterion("TRADE_TYPE like", value, "tradeType");
            return this;
        }

        public Criteria andTradeTypeNotLike(String value) {
            addCriterion("TRADE_TYPE not like", value, "tradeType");
            return this;
        }

        public Criteria andTradeTypeIn(List values) {
            addCriterion("TRADE_TYPE in", values, "tradeType");
            return this;
        }

        public Criteria andTradeTypeNotIn(List values) {
            addCriterion("TRADE_TYPE not in", values, "tradeType");
            return this;
        }

        public Criteria andTradeTypeBetween(String value1, String value2) {
            addCriterion("TRADE_TYPE between", value1, value2, "tradeType");
            return this;
        }

        public Criteria andTradeTypeNotBetween(String value1, String value2) {
            addCriterion("TRADE_TYPE not between", value1, value2, "tradeType");
            return this;
        }

        public Criteria andPayeeBankCodeIsNull() {
            addCriterion("PAYEE_BANKCODE is null");
            return this;
        }

        public Criteria andPayeeBankCodeIsNotNull() {
            addCriterion("PAYEE_BANKCODE is not null");
            return this;
        }

        public Criteria andPayeeBankCodeEqualTo(Long value) {
            addCriterion("PAYEE_BANKCODE =", value, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeNotEqualTo(Long value) {
            addCriterion("PAYEE_BANKCODE <>", value, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeGreaterThan(Long value) {
            addCriterion("PAYEE_BANKCODE >", value, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("PAYEE_BANKCODE >=", value, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeLessThan(Long value) {
            addCriterion("PAYEE_BANKCODE <", value, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeLessThanOrEqualTo(Long value) {
            addCriterion("PAYEE_BANKCODE <=", value, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeIn(List values) {
            addCriterion("PAYEE_BANKCODE in", values, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeNotIn(List values) {
            addCriterion("PAYEE_BANKCODE not in", values, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeBetween(Long value1, Long value2) {
            addCriterion("PAYEE_BANKCODE between", value1, value2, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankCodeNotBetween(Long value1, Long value2) {
            addCriterion("PAYEE_BANKCODE not between", value1, value2, "payeeBankCode");
            return this;
        }

        public Criteria andPayeeBankNameIsNull() {
            addCriterion("PAYEE_BANKNAME is null");
            return this;
        }

        public Criteria andPayeeBankNameIsNotNull() {
            addCriterion("PAYEE_BANKNAME is not null");
            return this;
        }

        public Criteria andPayeeBankNameEqualTo(String value) {
            addCriterion("PAYEE_BANKNAME =", value, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameNotEqualTo(String value) {
            addCriterion("PAYEE_BANKNAME <>", value, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameGreaterThan(String value) {
            addCriterion("PAYEE_BANKNAME >", value, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKNAME >=", value, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameLessThan(String value) {
            addCriterion("PAYEE_BANKNAME <", value, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameLessThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKNAME <=", value, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameLike(String value) {
            addCriterion("PAYEE_BANKNAME like", value, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameNotLike(String value) {
            addCriterion("PAYEE_BANKNAME not like", value, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameIn(List values) {
            addCriterion("PAYEE_BANKNAME in", values, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameNotIn(List values) {
            addCriterion("PAYEE_BANKNAME not in", values, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKNAME between", value1, value2, "payeeBankName");
            return this;
        }

        public Criteria andPayeeBankNameNotBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKNAME not between", value1, value2, "payeeBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameIsNull() {
            addCriterion("PAYEE_OPENINGBANKNAME is null");
            return this;
        }

        public Criteria andPayeeOpeningBankNameIsNotNull() {
            addCriterion("PAYEE_OPENINGBANKNAME is not null");
            return this;
        }

        public Criteria andPayeeOpeningBankNameEqualTo(String value) {
            addCriterion("PAYEE_OPENINGBANKNAME =", value, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameNotEqualTo(String value) {
            addCriterion("PAYEE_OPENINGBANKNAME <>", value, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameGreaterThan(String value) {
            addCriterion("PAYEE_OPENINGBANKNAME >", value, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("PAYEE_OPENINGBANKNAME >=", value, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameLessThan(String value) {
            addCriterion("PAYEE_OPENINGBANKNAME <", value, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameLessThanOrEqualTo(String value) {
            addCriterion("PAYEE_OPENINGBANKNAME <=", value, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameLike(String value) {
            addCriterion("PAYEE_OPENINGBANKNAME like", value, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameNotLike(String value) {
            addCriterion("PAYEE_OPENINGBANKNAME not like", value, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameIn(List values) {
            addCriterion("PAYEE_OPENINGBANKNAME in", values, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameNotIn(List values) {
            addCriterion("PAYEE_OPENINGBANKNAME not in", values, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameBetween(String value1, String value2) {
            addCriterion("PAYEE_OPENINGBANKNAME between", value1, value2, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeOpeningBankNameNotBetween(String value1, String value2) {
            addCriterion("PAYEE_OPENINGBANKNAME not between", value1, value2, "payeeOpeningBankName");
            return this;
        }

        public Criteria andPayeeBankProvinceIsNull() {
            addCriterion("PAYEE_BANKPROVINCE is null");
            return this;
        }

        public Criteria andPayeeBankProvinceIsNotNull() {
            addCriterion("PAYEE_BANKPROVINCE is not null");
            return this;
        }

        public Criteria andPayeeBankProvinceEqualTo(String value) {
            addCriterion("PAYEE_BANKPROVINCE =", value, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceNotEqualTo(String value) {
            addCriterion("PAYEE_BANKPROVINCE <>", value, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceGreaterThan(String value) {
            addCriterion("PAYEE_BANKPROVINCE >", value, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKPROVINCE >=", value, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceLessThan(String value) {
            addCriterion("PAYEE_BANKPROVINCE <", value, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceLessThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKPROVINCE <=", value, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceLike(String value) {
            addCriterion("PAYEE_BANKPROVINCE like", value, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceNotLike(String value) {
            addCriterion("PAYEE_BANKPROVINCE not like", value, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceIn(List values) {
            addCriterion("PAYEE_BANKPROVINCE in", values, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceNotIn(List values) {
            addCriterion("PAYEE_BANKPROVINCE not in", values, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKPROVINCE between", value1, value2, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceNotBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKPROVINCE not between", value1, value2, "payeeBankProvince");
            return this;
        }

        public Criteria andPayeeBankProvinceNameIsNull() {
            addCriterion("PAYEE_BANKPROVINCENAME is null");
            return this;
        }

        public Criteria andPayeeBankProvinceNameIsNotNull() {
            addCriterion("PAYEE_BANKPROVINCENAME is not null");
            return this;
        }

        public Criteria andPayeeBankProvinceNameEqualTo(String value) {
            addCriterion("PAYEE_BANKPROVINCENAME =", value, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameNotEqualTo(String value) {
            addCriterion("PAYEE_BANKPROVINCENAME <>", value, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameGreaterThan(String value) {
            addCriterion("PAYEE_BANKPROVINCENAME >", value, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameGreaterThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKPROVINCENAME >=", value, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameLessThan(String value) {
            addCriterion("PAYEE_BANKPROVINCENAME <", value, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameLessThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKPROVINCENAME <=", value, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameLike(String value) {
            addCriterion("PAYEE_BANKPROVINCENAME like", value, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameNotLike(String value) {
            addCriterion("PAYEE_BANKPROVINCENAME not like", value, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameIn(List values) {
            addCriterion("PAYEE_BANKPROVINCENAME in", values, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameNotIn(List values) {
            addCriterion("PAYEE_BANKPROVINCENAME not in", values, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKPROVINCENAME between", value1, value2, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankProvinceNameNotBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKPROVINCENAME not between", value1, value2, "payeeBankProvinceName");
            return this;
        }

        public Criteria andPayeeBankCityIsNull() {
            addCriterion("PAYEE_BANKCITY is null");
            return this;
        }

        public Criteria andPayeeBankCityIsNotNull() {
            addCriterion("PAYEE_BANKCITY is not null");
            return this;
        }

        public Criteria andPayeeBankCityEqualTo(String value) {
            addCriterion("PAYEE_BANKCITY =", value, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityNotEqualTo(String value) {
            addCriterion("PAYEE_BANKCITY <>", value, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityGreaterThan(String value) {
            addCriterion("PAYEE_BANKCITY >", value, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityGreaterThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKCITY >=", value, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityLessThan(String value) {
            addCriterion("PAYEE_BANKCITY <", value, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityLessThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKCITY <=", value, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityLike(String value) {
            addCriterion("PAYEE_BANKCITY like", value, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityNotLike(String value) {
            addCriterion("PAYEE_BANKCITY not like", value, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityIn(List values) {
            addCriterion("PAYEE_BANKCITY in", values, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityNotIn(List values) {
            addCriterion("PAYEE_BANKCITY not in", values, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKCITY between", value1, value2, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityNotBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKCITY not between", value1, value2, "payeeBankCity");
            return this;
        }

        public Criteria andPayeeBankCityNameIsNull() {
            addCriterion("PAYEE_BANKCITYNAME is null");
            return this;
        }

        public Criteria andPayeeBankCityNameIsNotNull() {
            addCriterion("PAYEE_BANKCITYNAME is not null");
            return this;
        }

        public Criteria andPayeeBankCityNameEqualTo(String value) {
            addCriterion("PAYEE_BANKCITYNAME =", value, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameNotEqualTo(String value) {
            addCriterion("PAYEE_BANKCITYNAME <>", value, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameGreaterThan(String value) {
            addCriterion("PAYEE_BANKCITYNAME >", value, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKCITYNAME >=", value, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameLessThan(String value) {
            addCriterion("PAYEE_BANKCITYNAME <", value, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameLessThanOrEqualTo(String value) {
            addCriterion("PAYEE_BANKCITYNAME <=", value, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameLike(String value) {
            addCriterion("PAYEE_BANKCITYNAME like", value, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameNotLike(String value) {
            addCriterion("PAYEE_BANKCITYNAME not like", value, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameIn(List values) {
            addCriterion("PAYEE_BANKCITYNAME in", values, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameNotIn(List values) {
            addCriterion("PAYEE_BANKCITYNAME not in", values, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKCITYNAME between", value1, value2, "payeeBankCityName");
            return this;
        }

        public Criteria andPayeeBankCityNameNotBetween(String value1, String value2) {
            addCriterion("PAYEE_BANKCITYNAME not between", value1, value2, "payeeBankCityName");
            return this;
        }

        public Criteria andRequestAmountIsNull() {
            addCriterion("REQUEST_AMOUNT is null");
            return this;
        }

        public Criteria andRequestAmountIsNotNull() {
            addCriterion("REQUEST_AMOUNT is not null");
            return this;
        }

        public Criteria andRequestAmountEqualTo(String value) {
            addCriterion("REQUEST_AMOUNT =", value, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountNotEqualTo(String value) {
            addCriterion("REQUEST_AMOUNT <>", value, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountGreaterThan(String value) {
            addCriterion("REQUEST_AMOUNT >", value, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_AMOUNT >=", value, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountLessThan(String value) {
            addCriterion("REQUEST_AMOUNT <", value, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_AMOUNT <=", value, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountLike(String value) {
            addCriterion("REQUEST_AMOUNT like", value, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountNotLike(String value) {
            addCriterion("REQUEST_AMOUNT not like", value, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountIn(List values) {
            addCriterion("REQUEST_AMOUNT in", values, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountNotIn(List values) {
            addCriterion("REQUEST_AMOUNT not in", values, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountBetween(String value1, String value2) {
            addCriterion("REQUEST_AMOUNT between", value1, value2, "RequestAmount");
            return this;
        }

        public Criteria andRequestAmountNotBetween(String value1, String value2) {
            addCriterion("REQUEST_AMOUNT not between", value1, value2, "RequestAmount");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("REMARK in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("REMARK not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return this;
        }

        public Criteria andValidStatusIsNull() {
            addCriterion("VALID_STATUS is null");
            return this;
        }

        public Criteria andValidStatusIsNotNull() {
            addCriterion("VALID_STATUS is not null");
            return this;
        }

        public Criteria andValidStatusEqualTo(Integer value) {
            addCriterion("VALID_STATUS =", value, "validStatus");
            return this;
        }

        public Criteria andValidStatusNotEqualTo(Integer value) {
            addCriterion("VALID_STATUS <>", value, "validStatus");
            return this;
        }

        public Criteria andValidStatusGreaterThan(Integer value) {
            addCriterion("VALID_STATUS >", value, "validStatus");
            return this;
        }

        public Criteria andValidStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("VALID_STATUS >=", value, "validStatus");
            return this;
        }

        public Criteria andValidStatusLessThan(Integer value) {
            addCriterion("VALID_STATUS <", value, "validStatus");
            return this;
        }

        public Criteria andValidStatusLessThanOrEqualTo(Integer value) {
            addCriterion("VALID_STATUS <=", value, "validStatus");
            return this;
        }

        public Criteria andValidStatusIn(List values) {
            addCriterion("VALID_STATUS in", values, "validStatus");
            return this;
        }

        public Criteria andValidStatusNotIn(List values) {
            addCriterion("VALID_STATUS not in", values, "validStatus");
            return this;
        }

        public Criteria andValidStatusBetween(Integer value1, Integer value2) {
            addCriterion("VALID_STATUS between", value1, value2, "validStatus");
            return this;
        }

        public Criteria andValidStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("VALID_STATUS not between", value1, value2, "validStatus");
            return this;
        }

        public Criteria andErrorMsgIsNull() {
            addCriterion("ERROR_MSG is null");
            return this;
        }

        public Criteria andErrorMsgIsNotNull() {
            addCriterion("ERROR_MSG is not null");
            return this;
        }

        public Criteria andErrorMsgEqualTo(String value) {
            addCriterion("ERROR_MSG =", value, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgNotEqualTo(String value) {
            addCriterion("ERROR_MSG <>", value, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgGreaterThan(String value) {
            addCriterion("ERROR_MSG >", value, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_MSG >=", value, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgLessThan(String value) {
            addCriterion("ERROR_MSG <", value, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgLessThanOrEqualTo(String value) {
            addCriterion("ERROR_MSG <=", value, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgLike(String value) {
            addCriterion("ERROR_MSG like", value, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgNotLike(String value) {
            addCriterion("ERROR_MSG not like", value, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgIn(List values) {
            addCriterion("ERROR_MSG in", values, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgNotIn(List values) {
            addCriterion("ERROR_MSG not in", values, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgBetween(String value1, String value2) {
            addCriterion("ERROR_MSG between", value1, value2, "errorMsg");
            return this;
        }

        public Criteria andErrorMsgNotBetween(String value1, String value2) {
            addCriterion("ERROR_MSG not between", value1, value2, "errorMsg");
            return this;
        }

        public Criteria andPaymentAmountIsNull() {
            addCriterion("PAYMENT_AMOUNT is null");
            return this;
        }

        public Criteria andPaymentAmountIsNotNull() {
            addCriterion("PAYMENT_AMOUNT is not null");
            return this;
        }

        public Criteria andPaymentAmountEqualTo(Long value) {
            addCriterion("PAYMENT_AMOUNT =", value, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountNotEqualTo(Long value) {
            addCriterion("PAYMENT_AMOUNT <>", value, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountGreaterThan(Long value) {
            addCriterion("PAYMENT_AMOUNT >", value, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("PAYMENT_AMOUNT >=", value, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountLessThan(Long value) {
            addCriterion("PAYMENT_AMOUNT <", value, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountLessThanOrEqualTo(Long value) {
            addCriterion("PAYMENT_AMOUNT <=", value, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountIn(List values) {
            addCriterion("PAYMENT_AMOUNT in", values, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountNotIn(List values) {
            addCriterion("PAYMENT_AMOUNT not in", values, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountBetween(Long value1, Long value2) {
            addCriterion("PAYMENT_AMOUNT between", value1, value2, "paymentAmount");
            return this;
        }

        public Criteria andPaymentAmountNotBetween(Long value1, Long value2) {
            addCriterion("PAYMENT_AMOUNT not between", value1, value2, "paymentAmount");
            return this;
        }

        public Criteria andIsPayerPayFeeIsNull() {
            addCriterion("IS_PAYERPAYFEE is null");
            return this;
        }

        public Criteria andIsPayerPayFeeIsNotNull() {
            addCriterion("IS_PAYERPAYFEE is not null");
            return this;
        }

        public Criteria andIsPayerPayFeeEqualTo(Integer value) {
            addCriterion("IS_PAYERPAYFEE =", value, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeNotEqualTo(Integer value) {
            addCriterion("IS_PAYERPAYFEE <>", value, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeGreaterThan(Integer value) {
            addCriterion("IS_PAYERPAYFEE >", value, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_PAYERPAYFEE >=", value, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeLessThan(Integer value) {
            addCriterion("IS_PAYERPAYFEE <", value, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeLessThanOrEqualTo(Integer value) {
            addCriterion("IS_PAYERPAYFEE <=", value, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeIn(List values) {
            addCriterion("IS_PAYERPAYFEE in", values, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeNotIn(List values) {
            addCriterion("IS_PAYERPAYFEE not in", values, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeBetween(Integer value1, Integer value2) {
            addCriterion("IS_PAYERPAYFEE between", value1, value2, "isPayerPayFee");
            return this;
        }

        public Criteria andIsPayerPayFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_PAYERPAYFEE not between", value1, value2, "isPayerPayFee");
            return this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("FEE is null");
            return this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("FEE is not null");
            return this;
        }

        public Criteria andFeeEqualTo(Long value) {
            addCriterion("FEE =", value, "fee");
            return this;
        }

        public Criteria andFeeNotEqualTo(Long value) {
            addCriterion("FEE <>", value, "fee");
            return this;
        }

        public Criteria andFeeGreaterThan(Long value) {
            addCriterion("FEE >", value, "fee");
            return this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(Long value) {
            addCriterion("FEE >=", value, "fee");
            return this;
        }

        public Criteria andFeeLessThan(Long value) {
            addCriterion("FEE <", value, "fee");
            return this;
        }

        public Criteria andFeeLessThanOrEqualTo(Long value) {
            addCriterion("FEE <=", value, "fee");
            return this;
        }

        public Criteria andFeeIn(List values) {
            addCriterion("FEE in", values, "fee");
            return this;
        }

        public Criteria andFeeNotIn(List values) {
            addCriterion("FEE not in", values, "fee");
            return this;
        }

        public Criteria andFeeBetween(Long value1, Long value2) {
            addCriterion("FEE between", value1, value2, "fee");
            return this;
        }

        public Criteria andFeeNotBetween(Long value1, Long value2) {
            addCriterion("FEE not between", value1, value2, "fee");
            return this;
        }

        public Criteria andRealpayAmountIsNull() {
            addCriterion("REALPAY_AMOUNT is null");
            return this;
        }

        public Criteria andRealpayAmountIsNotNull() {
            addCriterion("REALPAY_AMOUNT is not null");
            return this;
        }

        public Criteria andRealpayAmountEqualTo(Long value) {
            addCriterion("REALPAY_AMOUNT =", value, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountNotEqualTo(Long value) {
            addCriterion("REALPAY_AMOUNT <>", value, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountGreaterThan(Long value) {
            addCriterion("REALPAY_AMOUNT >", value, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("REALPAY_AMOUNT >=", value, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountLessThan(Long value) {
            addCriterion("REALPAY_AMOUNT <", value, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountLessThanOrEqualTo(Long value) {
            addCriterion("REALPAY_AMOUNT <=", value, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountIn(List values) {
            addCriterion("REALPAY_AMOUNT in", values, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountNotIn(List values) {
            addCriterion("REALPAY_AMOUNT not in", values, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountBetween(Long value1, Long value2) {
            addCriterion("REALPAY_AMOUNT between", value1, value2, "realpayAmount");
            return this;
        }

        public Criteria andRealpayAmountNotBetween(Long value1, Long value2) {
            addCriterion("REALPAY_AMOUNT not between", value1, value2, "realpayAmount");
            return this;
        }

        public Criteria andRealoutAmountIsNull() {
            addCriterion("REALOUT_AMOUNT is null");
            return this;
        }

        public Criteria andRealoutAmountIsNotNull() {
            addCriterion("REALOUT_AMOUNT is not null");
            return this;
        }

        public Criteria andRealoutAmountEqualTo(Long value) {
            addCriterion("REALOUT_AMOUNT =", value, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountNotEqualTo(Long value) {
            addCriterion("REALOUT_AMOUNT <>", value, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountGreaterThan(Long value) {
            addCriterion("REALOUT_AMOUNT >", value, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("REALOUT_AMOUNT >=", value, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountLessThan(Long value) {
            addCriterion("REALOUT_AMOUNT <", value, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountLessThanOrEqualTo(Long value) {
            addCriterion("REALOUT_AMOUNT <=", value, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountIn(List values) {
            addCriterion("REALOUT_AMOUNT in", values, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountNotIn(List values) {
            addCriterion("REALOUT_AMOUNT not in", values, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountBetween(Long value1, Long value2) {
            addCriterion("REALOUT_AMOUNT between", value1, value2, "realoutAmount");
            return this;
        }

        public Criteria andRealoutAmountNotBetween(Long value1, Long value2) {
            addCriterion("REALOUT_AMOUNT not between", value1, value2, "realoutAmount");
            return this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("ORDER_STATUS is null");
            return this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("ORDER_STATUS is not null");
            return this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("ORDER_STATUS =", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("ORDER_STATUS <>", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("ORDER_STATUS >", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_STATUS >=", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("ORDER_STATUS <", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_STATUS <=", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusIn(List values) {
            addCriterion("ORDER_STATUS in", values, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotIn(List values) {
            addCriterion("ORDER_STATUS not in", values, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_STATUS between", value1, value2, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_STATUS not between", value1, value2, "orderStatus");
            return this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateIn(List values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateNotIn(List values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateIn(List values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return this;
        }

        public Criteria andUpdateDateNotIn(List values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return this;
        }
    }
}