package com.pay.fo.order.model.batchpayment;

import java.util.Date;

public class BatchPaymentReqBaseInfo {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SEQ
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Long requestSeq;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_TYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Integer requestType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.BUSINESS_BATCHNO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private String businessBatchNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_NAME
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private String payerName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_LOGINNAME
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private String payerLoginName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERCODE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Long payerMemberCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERTYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Integer payerMemberType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTCODE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private String payerAcctCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTTYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Integer payerAcctType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.CREATOR
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private String creator;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.CREATE_DATE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Date createDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.UPDATE_DATE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Date updateDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.STATUS
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Integer status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.AUDITOR
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private String auditor;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Long requestAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_COUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Integer requestCount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.VALID_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Long validAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.VALID_COUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Integer validCount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.IS_PAYERPAYFEE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Integer isPayerPayFee;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.FEE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Long fee;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.REALPAY_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Long realpayAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.REALOUT_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Long realoutAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SRC
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private String requestSrc;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.AUDIT_REMARK
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private String auditRemark;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FO.BATCH_PAYMENTREQBASEINFO.PROCESS_TYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	private Integer processType;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SEQ
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SEQ
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long getRequestSeq() {
		return requestSeq;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SEQ
	 * @param requestSeq  the value for FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SEQ
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setRequestSeq(Long requestSeq) {
		this.requestSeq = requestSeq;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_TYPE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.REQUEST_TYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Integer getRequestType() {
		return requestType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_TYPE
	 * @param requestType  the value for FO.BATCH_PAYMENTREQBASEINFO.REQUEST_TYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setRequestType(Integer requestType) {
		this.requestType = requestType;
	}

	
	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.BUSINESS_BATCHNO
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.BUSINESS_BATCHNO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public String getBusinessBatchNo() {
		return businessBatchNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.BUSINESS_BATCHNO
	 * @param businessBatchNo  the value for FO.BATCH_PAYMENTREQBASEINFO.BUSINESS_BATCHNO
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setBusinessBatchNo(String businessBatchNo) {
		this.businessBatchNo = businessBatchNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_NAME
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.PAYER_NAME
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public String getPayerName() {
		return payerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_NAME
	 * @param payerName  the value for FO.BATCH_PAYMENTREQBASEINFO.PAYER_NAME
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_LOGINNAME
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.PAYER_LOGINNAME
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public String getPayerLoginName() {
		return payerLoginName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_LOGINNAME
	 * @param payerLoginName  the value for FO.BATCH_PAYMENTREQBASEINFO.PAYER_LOGINNAME
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setPayerLoginName(String payerLoginName) {
		this.payerLoginName = payerLoginName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERCODE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERCODE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long getPayerMemberCode() {
		return payerMemberCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERCODE
	 * @param payerMemberCode  the value for FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERCODE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setPayerMemberCode(Long payerMemberCode) {
		this.payerMemberCode = payerMemberCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERTYPE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERTYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Integer getPayerMemberType() {
		return payerMemberType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERTYPE
	 * @param payerMemberType  the value for FO.BATCH_PAYMENTREQBASEINFO.PAYER_MEMBERTYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setPayerMemberType(Integer payerMemberType) {
		this.payerMemberType = payerMemberType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTCODE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTCODE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public String getPayerAcctCode() {
		return payerAcctCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTCODE
	 * @param payerAcctCode  the value for FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTCODE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setPayerAcctCode(String payerAcctCode) {
		this.payerAcctCode = payerAcctCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTTYPE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTTYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Integer getPayerAcctType() {
		return payerAcctType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTTYPE
	 * @param payerAcctType  the value for FO.BATCH_PAYMENTREQBASEINFO.PAYER_ACCTTYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setPayerAcctType(Integer payerAcctType) {
		this.payerAcctType = payerAcctType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.CREATOR
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.CREATOR
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.CREATOR
	 * @param creator  the value for FO.BATCH_PAYMENTREQBASEINFO.CREATOR
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.CREATE_DATE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.CREATE_DATE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.CREATE_DATE
	 * @param createDate  the value for FO.BATCH_PAYMENTREQBASEINFO.CREATE_DATE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.UPDATE_DATE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.UPDATE_DATE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.UPDATE_DATE
	 * @param updateDate  the value for FO.BATCH_PAYMENTREQBASEINFO.UPDATE_DATE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.STATUS
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.STATUS
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.STATUS
	 * @param status  the value for FO.BATCH_PAYMENTREQBASEINFO.STATUS
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.AUDITOR
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.AUDITOR
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public String getAuditor() {
		return auditor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.AUDITOR
	 * @param auditor  the value for FO.BATCH_PAYMENTREQBASEINFO.AUDITOR
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setAuditor(String auditor) {
		this.auditor = auditor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_AMOUNT
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.REQUEST_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long getRequestAmount() {
		return requestAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_AMOUNT
	 * @param requestAmount  the value for FO.BATCH_PAYMENTREQBASEINFO.REQUEST_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setRequestAmount(Long requestAmount) {
		this.requestAmount = requestAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_COUNT
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.REQUEST_COUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Integer getRequestCount() {
		return requestCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_COUNT
	 * @param requestCount  the value for FO.BATCH_PAYMENTREQBASEINFO.REQUEST_COUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setRequestCount(Integer requestCount) {
		this.requestCount = requestCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.VALID_AMOUNT
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.VALID_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long getValidAmount() {
		return validAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.VALID_AMOUNT
	 * @param validAmount  the value for FO.BATCH_PAYMENTREQBASEINFO.VALID_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setValidAmount(Long validAmount) {
		this.validAmount = validAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.VALID_COUNT
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.VALID_COUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Integer getValidCount() {
		return validCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.VALID_COUNT
	 * @param validCount  the value for FO.BATCH_PAYMENTREQBASEINFO.VALID_COUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setValidCount(Integer validCount) {
		this.validCount = validCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.IS_PAYERPAYFEE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.IS_PAYERPAYFEE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Integer getIsPayerPayFee() {
		return isPayerPayFee;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.IS_PAYERPAYFEE
	 * @param isPayerPayFee  the value for FO.BATCH_PAYMENTREQBASEINFO.IS_PAYERPAYFEE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setIsPayerPayFee(Integer isPayerPayFee) {
		this.isPayerPayFee = isPayerPayFee;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.FEE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.FEE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long getFee() {
		return fee;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.FEE
	 * @param fee  the value for FO.BATCH_PAYMENTREQBASEINFO.FEE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setFee(Long fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REALPAY_AMOUNT
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.REALPAY_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long getRealpayAmount() {
		return realpayAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REALPAY_AMOUNT
	 * @param realpayAmount  the value for FO.BATCH_PAYMENTREQBASEINFO.REALPAY_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setRealpayAmount(Long realpayAmount) {
		this.realpayAmount = realpayAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REALOUT_AMOUNT
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.REALOUT_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Long getRealoutAmount() {
		return realoutAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REALOUT_AMOUNT
	 * @param realoutAmount  the value for FO.BATCH_PAYMENTREQBASEINFO.REALOUT_AMOUNT
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setRealoutAmount(Long realoutAmount) {
		this.realoutAmount = realoutAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SRC
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SRC
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public String getRequestSrc() {
		return requestSrc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SRC
	 * @param requestSrc  the value for FO.BATCH_PAYMENTREQBASEINFO.REQUEST_SRC
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setRequestSrc(String requestSrc) {
		this.requestSrc = requestSrc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.AUDIT_REMARK
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.AUDIT_REMARK
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public String getAuditRemark() {
		return auditRemark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.AUDIT_REMARK
	 * @param auditRemark  the value for FO.BATCH_PAYMENTREQBASEINFO.AUDIT_REMARK
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setAuditRemark(String auditRemark) {
		this.auditRemark = auditRemark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PROCESS_TYPE
	 * @return  the value of FO.BATCH_PAYMENTREQBASEINFO.PROCESS_TYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public Integer getProcessType() {
		return processType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FO.BATCH_PAYMENTREQBASEINFO.PROCESS_TYPE
	 * @param processType  the value for FO.BATCH_PAYMENTREQBASEINFO.PROCESS_TYPE
	 * @ibatorgenerated  Wed Nov 02 11:31:22 CST 2011
	 */
	public void setProcessType(Integer processType) {
		this.processType = processType;
	}
}