/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.channel.model.product;

/**
 * FUNDOUT_BUSINESS
 */

public class FundoutProduct implements java.io.Serializable {

	private String name;
	private String mark;
	private java.util.Date createDate;
	private Long status;
	private String code;

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Long getStatus() {
		return status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	public java.util.Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

}