/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.fundout.withdraw.dto.type;
/**
* WITHDRAW_TYPE
*/

public class WithdrawTypeDTO  implements java.io.Serializable {

    private String typeName;
    private java.util.Date creationDate;
    private Integer status;
    private Integer sequenceId;
    private java.util.Date updateDate;
    private String typeDesc;

    public String getTypeName (){
        return typeName;
    }
    
    public void setTypeName (String typeName){
        this.typeName = typeName;
    }
    public java.util.Date getCreationDate (){
        return creationDate;
    }
    
    public void setCreationDate (java.util.Date creationDate){
        this.creationDate = creationDate;
    }
    public Integer getStatus (){
        return status;
    }
    
    public void setStatus (Integer status){
        this.status = status;
    }
    
    public String getStatusStr (){
        return status==1?"关闭":"开启";
    }
    
    public Integer getSequenceId (){
        return sequenceId;
    }
    
    public void setSequenceId (Integer sequenceId){
        this.sequenceId = sequenceId;
    }
    public java.util.Date getUpdateDate (){
        return updateDate;
    }
    
    public void setUpdateDate (java.util.Date updateDate){
        this.updateDate = updateDate;
    }
    public String getTypeDesc (){
        return typeDesc;
    }
    
    public void setTypeDesc (String typeDesc){
        this.typeDesc = typeDesc;
    }
}