/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.masspaytobank;

import java.util.List;
import java.util.Map;

import com.pay.fundout.withdraw.model.masspaytobank.MassPaytobankImportBase;
import com.pay.inf.dao.BaseDAO;

public interface MassPaytobankImportBaseDAO extends
		BaseDAO<MassPaytobankImportBase> {
	/**
	 * 查询上传列表(分页)
	 * 
	 * @param page
	 * @param params
	 * @return
	 */
	public List getUploadFileInfoList(Map params);

	/**
	 * 记录总数
	 * 
	 * @param params
	 * @return
	 */
	public Integer getTotalCount(Map params);

}