/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.pay.fundout.withdraw.dao.withdrawbankconfig;

import com.pay.inf.dao.BaseDAO;

public interface WithdrawBankConfigDAO extends BaseDAO {

}