/**
*
* auto generated by ibatis tools 
*
**/
package com.pay.txncore.model;
/**
* COMMON_AUDIT
*/

public class CommonAudit  implements java.io.Serializable {

    private String remark;
    private Integer statusB;
    private Integer statusC;
    private Long commonAuditNo;
    private String operatorA;
    private String operatorB;
    private java.util.Date updateDate;
    private String operatorC;
    private String transType;
    private Integer auditType;
    private Long orderNo;
    private Integer statusA;
    private java.util.Date createDate;
    private String descC;
    private String descB;
    private String descA;

    public String getRemark (){
        return remark;
    }
    
    public void setRemark (String remark){
        this.remark = remark;
    }
    public Integer getStatusB (){
        return statusB;
    }
    
    public void setStatusB (Integer statusB){
        this.statusB = statusB;
    }
    public Integer getStatusC (){
        return statusC;
    }
    
    public void setStatusC (Integer statusC){
        this.statusC = statusC;
    }
    public Long getCommonAuditNo (){
        return commonAuditNo;
    }
    
    public void setCommonAuditNo (Long commonAuditNo){
        this.commonAuditNo = commonAuditNo;
    }
    public String getOperatorA (){
        return operatorA;
    }
    
    public void setOperatorA (String operatorA){
        this.operatorA = operatorA;
    }
    public String getOperatorB (){
        return operatorB;
    }
    
    public void setOperatorB (String operatorB){
        this.operatorB = operatorB;
    }
    public java.util.Date getUpdateDate (){
        return updateDate;
    }
    
    public void setUpdateDate (java.util.Date updateDate){
        this.updateDate = updateDate;
    }
    public String getOperatorC (){
        return operatorC;
    }
    
    public void setOperatorC (String operatorC){
        this.operatorC = operatorC;
    }
 
    public String getTransType() {
		return transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}

	public Integer getAuditType (){
        return auditType;
    }
    
    public void setAuditType (Integer auditType){
        this.auditType = auditType;
    }
    public Long getOrderNo (){
        return orderNo;
    }
    
    public void setOrderNo (Long orderNo){
        this.orderNo = orderNo;
    }
    public Integer getStatusA (){
        return statusA;
    }
    
    public void setStatusA (Integer statusA){
        this.statusA = statusA;
    }
    public java.util.Date getCreateDate (){
        return createDate;
    }
    
    public void setCreateDate (java.util.Date createDate){
        this.createDate = createDate;
    }
    public String getDescC (){
        return descC;
    }
    
    public void setDescC (String descC){
        this.descC = descC;
    }
    public String getDescB (){
        return descB;
    }
    
    public void setDescB (String descB){
        this.descB = descB;
    }
    public String getDescA (){
        return descA;
    }
    
    public void setDescA (String descA){
        this.descA = descA;
    }

}